### ISSUE TITLE
Autocomplete in imports doesn't work when we have packages that are symlinks

### ISSUE THREAD

**Issue by wesleybl** [microsoft/pylance-release#1031]
## Environment data

-   Language Server version: 2021.3.1
-   OS and version: Ubuntu 18.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.9

## Expected behaviour

Fill the configuration in settings.json:

```json
"python.analysis.extraPaths": ["/home/user/lib"],
```

Packages inside `/home/user/lib` are symlinks to real path.

Type in the code:

```python
from my
```

I hope the autocomplete will suggest all packages that start with my inside the `/home/user/lib` folder.

## Actual behaviour

The autocomplete doesn't suggest packages inside the /home/user/lib folder .

## Logs

```
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py:1:6 ...
[FG]   parsing: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (0ms)
[FG]   binding: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (0ms)
[FG] completion at /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py:1:6 [found 74 items] (6ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (0ms)
[BG(1)] binding: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (0ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py ...
[BG(1)]   parsing: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (1ms)
[BG(1)]   binding: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (0ms)
[BG(1)]   checking: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (0ms)
[BG(1)] analyzing: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (1ms)
Background analysis message: resumeAnalysis
Background analysis message: getSemanticTokens
[FG] parsing: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (1ms)
[FG] binding: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (0ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py:1:6 ...
[FG]   parsing: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (0ms)
[FG]   binding: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (1ms)
[FG] completion at /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py:1:6 [found 74 items] (5ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (1ms)
[BG(1)] binding: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (1ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py:1:7 ...
[FG]   parsing: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (1ms)
[FG]   binding: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (0ms)
[FG] completion at /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py:1:7 [found 6 items] (4ms)
Background analysis message: analyze
[BG(1)] analyzing: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py ...
[BG(1)]   parsing: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (1ms)
[BG(1)]   binding: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (1ms)
[BG(1)]   checking: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (0ms)
[BG(1)] analyzing: /home/wesleybl/symbolic.package/src/symbolic/package/__init__.py (2ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
```

## Code Snippet / Additional information

See:

![autocomplete](https://user-images.githubusercontent.com/3297795/110788779-d3a79500-824d-11eb-9232-b22384392f9d.png)

In the figure, `lib` is a folder that is in `python.analysis.extraPaths`. `my`, inside the lib folder is a symbolic link to the real package.

I created a repository to simulate this:

https://github.com/wesleybl/symbolic.package

See: 

https://github.com/wesleybl/symbolic.package#symbolicpackage

It appears that there has been an increase in support for symbolic links in:

https://github.com/microsoft/pyright/pull/1607

But that didn’t solve the autocomplete problem.

@jakebailey @erictraut FYI

**Comment by jakebailey** [comment]
Just to precheck, does the import itself work if you were to just say `import my`, or does only completion break for the module?

**Comment by wesleybl** [comment]
Yes it works. After typing it doesn't give a module not found error. The problem is only in the autocomplete.

**Comment by jakebailey** [comment]
Thanks, that's very helpful.

**Comment by wesleybl** [comment]
Oops I think I got it wrong. autocomplete doesn't work with `import my`

**Comment by jakebailey** [comment]
As in when you write `import my` and then do `my.` you do not see the expected results? Or just that the autocompletion for `import my` fails?

**Comment by wesleybl** [comment]
Typing `import my` doesn't give me the expected results, if my is a symbolic link. I fix my answer above.

**Comment by jakebailey** [comment]
So long as no import resolution error happens (e.g. we find the module when manually specified), then things are still getting narrowed down to the completion provider, which is what I'm looking for. 🙂

**Comment by wesleybl** [comment]
No import error occurs:

![import](https://user-images.githubusercontent.com/3297795/110836837-48df8e00-827f-11eb-9f4a-7877aa30d7c8.png)

**Comment by jakebailey** [comment]
This is a simple copy/paste error here: https://github.com/microsoft/pyright/blob/2eba7458eb38952822a144bb2e111b7c0d90ff72/packages/pyright-internal/src/common/pathUtils.ts#L600

If I fix it so that it's adding the directory to the directories list, things work as expected.

**Comment by jakebailey** [comment]
This will be fixed in the next version of Pylance. Many thanks for the test case, it was very helpful!

**Comment by wesleybl** [comment]
Awesome! Thanks for the great work!

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.3.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202132-17-march-2021

**Comment by Hadatko** [comment]
Pleace take look to this mine comment: https://github.com/microsoft/vscode-python/issues/13198#issuecomment-827376631

**Comment by jakebailey** [comment]
@Hadatko Can you please file a new issue with your reproduction?

**Comment by Hadatko** [comment]
Sure. Sorry.

**Comment by Hadatko** [comment]
Sorry nevermind. Fixed with python.analysis.extraPaths

**Comment by Benkendorfer** [comment]
Hello, this is no longer working for me in v2023.09.30

It is not just autocomplete not working; Pylance is also throwing an import not resolved error. I have tried python.analysis.extraPaths to no avail

**Comment by wesleybl** [comment]
@Benkendorfer I tested the symbolic link issue in version v2023.09.30 and autocomplete worked. You must have another problem. I suggest you open another issue detailing your problem in more detail.
