### ISSUE TITLE
Parent class's __init__ docstring shown when child has a class docstring

### ISSUE THREAD

**Issue by Prunoideae** [microsoft/pylance-release#1047]
## Environment data

- Language Server version : 2021.3.1
- OS and version: Windows 10 Pro Insider Preview Build 21313
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.1 64-bit

## Expected behaviour

```python
class foo():
    '''
    Hello
    '''

    def __init__(self) -> None:
        pass

foo()
```

In this case `Hello` should be displayed when cursor is hovered on `foo()`.

## Actual behaviour

![image](https://user-images.githubusercontent.com/24620047/111068986-ea781100-8505-11eb-93e9-f7eb704804e2.png)
![image](https://user-images.githubusercontent.com/24620047/111069158-c7019600-8506-11eb-80ad-059783c6d2cb.png)

The very first doc of `__init__` is displayed, other than the `Hello`, if we add `'''Hello'''` in the `__init__`'s spec then it will be displayed. And if we remove the `__init__` definition, the class's docstring will be displayed.

This may cause inconvenience when reviewing large code blocks with objects, since docstrings are not directly displayed, and the case is inevitable even in packages like `pandas` because most code will not add same, or independent docstring for `__init__`, and it's repetitive if such a docstring is required other than a class's own docstring.

**Comment by judej** [comment]
Will investigate showing the most appropriate docstring. Thanks for the report.

**Comment by jakebailey** [comment]
The next release changes our docstring code to ignore `object`'s docs for classes that aren't `object` itself. That will fix the above example, but won't fix something like this:

```python
class A:
    """Class doc for A"""
    def __init__(self):
        """__init__ doc for A"""

class B(A):
    """Class doc for B"""

B()
```

As we search down the `__init__` chain first, finding `A.__init__` and using its doc, when we should probably be  using `B.__doc__`.

![image](https://user-images.githubusercontent.com/5341706/132409297-1be502c2-2c60-4cca-bb90-4eb8e38f6dd0.png)

**Comment by jakebailey** [comment]
This also begs the question of whether or not the class doc is the most appropriate doc in the above example; the method doc may have useful information on how to call it that the class doc would effectively hide. I'm thinking this issue was really only reported due to the 2021.3.0 fixing #550/#877, and previously 2020.9.6 added support for the builtin's docstrings (including object's pesky docs).

Perhaps the "right" solution is to call this fixed and see if anyone believes we should be showing B's doc in the example above later.

`help` shows both docs, since it's just listing everything, so that's not a useful comparison.

```
Help on class B in module __main__:

class B(A)
 |  Class doc for B
 |
 |  Method resolution order:
 |      B
 |      A
 |      builtins.object
 |
 |  Methods inherited from A:
 |
 |  __init__(self)
 |      __init__ doc for A
```

**Comment by jakebailey** [comment]
Yeah, I'm going to call this fixed for now. It seems like it's more consistent to not offer this doc if a parent `__init__` has one.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.9.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202191-8-september-2021

**Comment by leinaxd** [comment]
This Bug isn't fixed yet. isn't it? 
i've also try with pytorch nn.Module, same bug for the same reason ~_~

Excellent test case by the way!
