### ISSUE TITLE
Unstable annotation errors about unions using "|", with overloads and 3rd party classes

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1180]
## Environment data

-   Language Server version: 2021.4.2
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5 Anaconda

# Sample code

```python
from __future__ import annotations

from typing import Any, Generic, Sequence, TypeVar, oveload

import numpy

VT = TypeVar("VT")

class _iLocIndexer(Generic[VT]):
    @overload
    def __setitem__(self, key: int, value: VT, /) -> None:
        ...

    @overload
    def __setitem__(
        self,
        key: Sequence[int] | Sequence[bool] | numpy.ndarray,
        value: VT | Sequence[VT] | numpy.ndarray,
        /,
    ) -> None:
        ...

    def __setitem__(self, key: Any, value: Any, /) -> None:
        ...

_ = _iLocIndexer
```

## Actual behavior

Some unstable errors/warnings can be seen.

- If I make some tiny modification to the code, they may disappear for some while.
- If I remove the first overload, they disappear for good.
- If I don't use `numpy.ndarray`, they disppear for good.

## Expected behavior

No errors/warnings.

## Logs

Didn't found anything useful. Will add later if needed.

## Screenshots

![image](https://user-images.githubusercontent.com/15389744/115677552-2b740880-a383-11eb-9587-35b923b5bea5.png)
![image](https://user-images.githubusercontent.com/15389744/115677583-33cc4380-a383-11eb-9b7b-a8b4f1e75310.png)
There are errors/warnings.

<hr>

![image](https://user-images.githubusercontent.com/15389744/115677619-3d55ab80-a383-11eb-8dfa-23b710d0d96a.png)
Errors/warnings disappear after a blank line being added.

<hr>

![image](https://user-images.githubusercontent.com/15389744/115680418-1d73b700-a386-11eb-9795-ae6a73b84583.png)
No errors/warnings at all if there are no overloads.

<hr>

![image](https://user-images.githubusercontent.com/15389744/115679897-a2120580-a385-11eb-95bf-b4617605e4f6.png)
No errors/warnings at all if `numpy.ndarray` is not used.

**Comment by Azureblade3808** [comment]
# Simplified code sample
```python
from __future__ import annotations

from typing import overload

import numpy

@overload
def f(x: str | None, /) -> None:  # Union here isn't treated as an error.
    ...

@overload
def f(x: int | numpy.ndarray, /) -> None:
    ...

def f(x):
    ...
```

# Screenshot
![image](https://user-images.githubusercontent.com/15389744/115682636-3da47580-a388-11eb-88df-6694073bf2c6.png)

**Comment by Azureblade3808** [comment]
A more concise code sample:
```python
from __future__ import annotations

import builtins
from typing import overload

@overload
def f(x: builtins.int | None, /) -> None:  # Union here isn't treated as an error.
    ...

@overload
def f(x: int | None, /) -> None:  # Union here isn't treated as an error.
    ...

@overload
def f(x: builtins.int | None, /) -> None:
    ...

def f(x: int | None, /) -> None:
    ...
```

![image](https://user-images.githubusercontent.com/15389744/115685451-d0deaa80-a38a-11eb-9cb4-57b39daa4548.png)

It seems the following condition should be met to reproduce the issue:

- Python with version earlier to 3.10 is used (not confirmed).
- `from __future__ import annotations` must be present to avoid real syntax errors.
- A union is annotated with the alternative syntax ("|").
- The union exists in an overload which is not the first overload.
- The union contains at least one type using pattern of `[module.name]`.

**Comment by erictraut** [comment]
Thanks for the bug report. This appears to be due to inconsistent behavior based on evaluation ordering. It doesn't readily occur in pyright, but it always occurs in pylance because the semantic highlighting feature subtly changes the evaluation ordering, which triggers the bug. I'll look into the problem.

**Comment by erictraut** [comment]
I'm pretty sure I've fixed this bug in the pyright source base. 

@jakebailey, we should double check that the problem no longer appears in pylance when you pull the code over and integrate next time.

**Comment by jakebailey** [comment]
Unfortunately this still appears to be happen after I pulled.

![image](https://user-images.githubusercontent.com/5341706/115799209-d6d58b00-a38c-11eb-8824-7d47fa0d7d02.png)

Adding another newline makes it go away, and sometimes it comes back too.

**Comment by erictraut** [comment]
@jakebailey, I found and fixed another issue. Just pushed that fix to pyright. It should work now.

**Comment by jakebailey** [comment]
Yep, seems to work now.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.4.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202143-29-april-2021
