### ISSUE TITLE
No intellisense for instances of subprocess.Popen

### ISSUE THREAD

**Issue by russelldavis** [microsoft/pylance-release#121]
To reproduce:

```python
from subprocess import Popen
foo: Popen
```

## Expected behaviour
When typing `foo.`, intellisense should pop up the list of members.

## Actual behaviour
Nothing happens.

## Additional information
I'm guessing this is caused by the stubs for `Popen` using `__new__` instead of `__init__`, which is a weird/nonstandard thing (but pylance should support it). You can see some more context for that here: https://github.com/python/typeshed/pull/3113#discussion_r308975785.

**Comment by erictraut** [comment]
What are you seeing when you type "foo."? Are you receiving no suggestions? Here's what I'm seeing, which appears correct to me.

<img width="414" alt="Screen Shot 2020-07-15 at 3 51 33 PM" src="https://user-images.githubusercontent.com/7040122/87607911-4b1f2780-c6b3-11ea-93fd-7f27dfaf8fd6.png">

**Comment by russelldavis** [comment]
Oh, yeah that's what I was expecting to see. I'm not getting any popup at all.

**Comment by erictraut** [comment]
@russelldavis, we just released Pylance version 2020.7.2. Could you please verify that you are running that version and see if you are still able to repro the problem? It seems to be working fine for me.

**Comment by russelldavis** [comment]
Still seeing the problem on 2020.7.2. I tried tweaking various settings and creating a new project with just one file, and nothing seems to fix it. Here are my logs (logLevel set to trace):

```
[Info  - 5:51:57 PM] Pylance language server 2020.7.2 starting
[Info  - 5:51:57 PM] Server root directory: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server
[Info  - 5:51:57 PM] No configuration file found.
[Info  - 5:51:57 PM] Setting pythonPath for service "test1": "/usr/local/opt/python@3.8/bin/python3.8"
[Info  - 5:51:57 PM] stubPath /Users/russell/dev/python/test1/typings is not a valid directory.
[Info  - 5:51:57 PM] Assuming Python version 3.8
[Info  - 5:51:57 PM] Assuming Python platform Darwin
[Info  - 5:51:57 PM] Searching for source files
[Info  - 5:51:57 PM] Found 1 source file
[FG] parsing: /Users/russell/dev/python/test1/foo.py (10ms)
[FG] parsing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/2and3/builtins.pyi (102ms)
[FG] binding: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/2and3/builtins.pyi (44ms)
[FG] binding: /Users/russell/dev/python/test1/foo.py (0ms)
[Info  - 5:51:57 PM] Background analysis root directory: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server
[Info  - 5:51:57 PM] Background analysis started
[BG] analyzing: /Users/russell/dev/python/test1/foo.py ...
[BG]   parsing: /Users/russell/dev/python/test1/foo.py (50ms)
[BG]   parsing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/2and3/builtins.pyi (108ms)
[BG]   binding: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/2and3/builtins.pyi (46ms)
[BG]   binding: /Users/russell/dev/python/test1/foo.py (1ms)
[BG]   checking: /Users/russell/dev/python/test1/foo.py ...
[BG]     parsing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/subprocess.pyi (25ms)
[BG]     binding: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/subprocess.pyi (8ms)
[BG]     parsing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/typing.pyi (18ms)
[BG]     binding: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/typing.pyi (9ms)
[BG]     parsing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/abc.pyi (2ms)
[BG]     binding: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/abc.pyi (5ms)
[BG]   checking: /Users/russell/dev/python/test1/foo.py (91ms)
[BG] analyzing: /Users/russell/dev/python/test1/foo.py (297ms)
[BG] analyzing: /Users/russell/dev/python/test1/foo.py [cache hit] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/2and3/builtins.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/typing.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/subprocess.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/sys.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/2and3/_typeshed/__init__.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/abc.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/ast.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/io.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/types.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/third_party/2and3/typing_extensions.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/collections/__init__.pyi [analysis not needed] (0ms)
[FG] parsing: /Users/russell/dev/python/test1/foo.py (1ms)
[FG] binding: /Users/russell/dev/python/test1/foo.py (0ms)
[FG] parsing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/subprocess.pyi (41ms)
[FG] binding: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/subprocess.pyi (9ms)
[FG] parsing: /Users/russell/dev/python/test1/foo.py (2ms)
[FG] binding: /Users/russell/dev/python/test1/foo.py (0ms)
[FG] parsing: /Users/russell/dev/python/test1/foo.py (1ms)
[FG] binding: /Users/russell/dev/python/test1/foo.py (0ms)
[FG] parsing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/typing.pyi (20ms)
[FG] binding: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/typing.pyi (12ms)
[FG] parsing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/abc.pyi (1ms)
[FG] binding: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/abc.pyi (0ms)
[FG] parsing: /Users/russell/dev/python/test1/foo.py (1ms)
[FG] binding: /Users/russell/dev/python/test1/foo.py (0ms)
[BG] analyzing: /Users/russell/dev/python/test1/foo.py ...
[BG]   parsing: /Users/russell/dev/python/test1/foo.py (1ms)
[BG]   binding: /Users/russell/dev/python/test1/foo.py (1ms)
[BG]   checking: /Users/russell/dev/python/test1/foo.py (9ms)
[BG] analyzing: /Users/russell/dev/python/test1/foo.py (11ms)
[BG] analyzing: /Users/russell/dev/python/test1/foo.py [cache hit] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/2and3/builtins.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/typing.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/subprocess.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/sys.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/2and3/_typeshed/__init__.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/abc.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/ast.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/io.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/types.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/third_party/2and3/typing_extensions.pyi [analysis not needed] (0ms)
[BG] analyzing: /Users/russell/.vscode/extensions/ms-python.vscode-pylance-2020.7.2/server/typeshed-fallback/stdlib/3/collections/__init__.pyi [analysis not needed] (0ms)
```

**Comment by russelldavis** [comment]
I'm wondering if the trouble reproducing this is related to the race condition you mentioned at https://github.com/microsoft/pyright/issues/848#issuecomment-659805814. Does it reproduce if you try it in pylance (to avoid that race condition) and in a project with a fresh virtualenv, with Python 3.8.x?

**Comment by erictraut** [comment]
This race condition has been eliminated. Please see if you can repro it with the latest version of Pylance or Pyright. Thanks!

**Comment by russelldavis** [comment]
Thanks — still reproduces unfortunately.

**Comment by russelldavis** [comment]
I did some more investigating. `Popen` seems to be a red herring — this looks like an issue with unbound variables. (I did see the issue with a *bound* variable when I filed this, but that must've been caused by something that either I or pyright has fixed since then.)

Simple repro case not involving `Popen`:

```python
class Bar:
    def bla(self): ...

x: Bar # No intellisense if you type `x.`
y = Bar() # No problem
```

If you hover over `x` in that example, vscode shows the type as `Bar`. But if you hover over `x` on any line after that, it shows the type as `Unbound`, which I'm guessing is the reason the intellisense popup doesn't appear.

Perhaps this is by design, but it'd be nice if it worked (it works in the jedi language server, and with the equivalent typescript in vscode).

This still leaves a mystery as to how this is working for @erictraut. Is it possible you have another language server (jedi?) also running?

**Comment by erictraut** [comment]
You are correct. This has to do with the fact that it's unbound. The type has been declared, but the actual type of the variable at the time that it's used is unbound. The completion logic is designed to show only suggestions that are legal in the current context (i.e. those that won't generate runtime errors). Since the symbol is unbound, any member access operation is illegal.

I'm currently not able to repro the problem, so I'm not sure how to explain what I was seeing before, I don't think I had another LS installed, but I can't think of any better explanation. In any case, I can repro the problem now. 

Changing this behavior would actually be a lot of work, plus it would introduce an inconsistency in that everywhere else we try to stick to the principle that we present only valid completions.

**Comment by russelldavis** [comment]
Yeah, that seems fine. I'll go ahead and close this.
