### ISSUE TITLE
Extract method always fails when code includes comments

### ISSUE THREAD

**Issue by taldcroft** [microsoft/pylance-release#1262]
## Environment data

-   Language Server version: 2021.5.2-pre.1 (pyright df8b6b3c)
-   OS and version: MacOS 11.2.1
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda Python 3.7.9

## Expected behaviour

Refactor the first two lines of this script:
```python
# Comment
z = 1

print(z)
```
Should give:
```python
def new_func():
    # Comment
    z = 1
    return z

z = new_func()

print(z)
```

## Actual behaviour

This gives:
```python
z = new_func()

print(z)def new_func():
    z = 1
    return z
```

Basically extracting a method is consistently mishandling comment lines. I have not had success refactoring any code block using PyLance if the code contains any comments. If I delete all the comment lines then it seems to function correctly, but this is not a desirable workaround.

## Logs

```
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: /Users/aldcroft/git/astropy/go.py ...
[BG(1)]   parsing: /Users/aldcroft/git/astropy/go.py (0ms)
[BG(1)]   binding: /Users/aldcroft/git/astropy/go.py (0ms)
[BG(1)]   checking: /Users/aldcroft/git/astropy/go.py (4ms)
[BG(1)] analyzing: /Users/aldcroft/git/astropy/go.py (5ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: resumeAnalysis
[BG(1)] indexing: /Users/aldcroft/git/astropy/go.py [found 2] (0ms)
Indexing Done: /Users/aldcroft/git/astropy/go.py
Background analysis message: getDiagnosticsForRange
[FG] parsing: /Users/aldcroft/git/astropy/go.py (0ms)
[FG] binding: /Users/aldcroft/git/astropy/go.py (1ms)
Background analysis message: getSemanticTokens delta
[BG(1)] getSemanticTokens delta previousResultId:1620685102704 at /Users/aldcroft/git/astropy/go.py (0ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: markFilesDirty
Background analysis message: analyze
```

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.5.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202153-19-may-2021

**Comment by taldcroft** [comment]
Thanks for the fix, but this is still not fully working. I confirm my original example is fixed, but the following ones still fail:
```
z = 1  # comment
if z:
    print(z)
```
After method extraction I get:
```
def new_func1():
    z = 1
    # commentif z:
        print(z)
```

Another case:
```
z = 1
# comment
if z:
    print(z)
```
Gives:
```
def new_func1():
    z = 1
    # commentif z:
        print(z)
```

**Comment by taldcroft** [comment]
And I guess this is a repeat of #1091, but it is not just an `if` block, it also applies to at least a `for` block and a `try` block.

**Comment by jakebailey** [comment]
Can you add your examples to that issue, so we can ensure they get fixed together?
