### ISSUE TITLE
pd.DataFrame not in completion results

### ISSUE THREAD

**Issue by qubitron** [microsoft/pylance-release#13]
## Environment data

- Language Server version: 2020.6.1
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.0 32-bit virtualenv

## Expected behaviour

pd.DataFrame is in completion results

## Actual behaviour

![image](https://user-images.githubusercontent.com/17804393/86256732-84ad4a00-bb6d-11ea-9d84-49f98f551008.png)

**Comment by gokturksm** [comment]
Same behavior with `pd.Series`, `pd.Timestamp` etc. They are not exactly functions I guess, maybe that's the cause of the problem?

**Comment by gramster** [comment]
I think the stubs are alright here, but the only class that's showing as a completion off `pd.` is the public one defined in `__init__.py` itself, not the ones that are imported from other modules by `__init__.py`. Those classes work fine once you have them; i.e. you get completions for `pd.DataFrame().` etc. So there's something odd going on.

**Comment by erictraut** [comment]
Is this perhaps related to this bug? https://github.com/microsoft/pyright/issues/782

**Comment by gramster** [comment]
Looks like it but I will wait to confirm before marking this as fixed.

**Comment by Minituff** [comment]
I am getting this error as well. For example, Pylance thinks this is invalid because it cannot see the types of DataFrame:
`df = pd.DataFrame.from_dict(my_dict)`
I get IntelliSense when I use Jedi alone without Pylance.

Pylance Version: 2020.6.1
Python Language Server Version: 2020.6.91350
Python: 3.7.6
OS: Windows 10

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.7.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202070-9-july-2020

**Comment by Minituff** [comment]
That was a fast update!
I just tried out the new 2020.7.0 release. It looks like the errors have stopped, but I am still not getting IntelliSense like I get with Pyright for pandas dataframes. Should I open a new issue for this?

**Comment by jakebailey** [comment]
Yes, please do. Pyright doesn't ship any pandas stubs, but we do, so there may be a difference there where it's reading the "real" code.
