### ISSUE TITLE
Symlink support

### ISSUE THREAD

**Issue by wesleybl** [microsoft/pylance-release#131]
## Environment data

-   Language Server version: 2020.7.2
-   OS and version: Ubuntu 18.04
-   Python version (& distribution if applicable, e.g. Anaconda): Python 2.7.17

## Expected behaviour

Fill the configuration in settings.json:

```json
"python.analysis.extraPaths": ["/home/user/lib"],
```

Packages inside `/home/user/lib` are symlinks to real path.

Type in the code:

```python
from my
```

I hope the autocomplete will suggest all packages that start with my inside the `/home/user/lib` folder.

## Actual behaviour

The autocomplete doesn't suggest packages inside the /home/user/lib folder.

## Logs

```
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py:1:1 ...
[FG]   parsing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (1ms)
[FG]   binding: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
[FG] completion at /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py:1:1 [found 23 items] (3ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py:1:2 ...
[FG]   parsing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
[FG]   binding: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
[FG] completion at /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py:1:2 [found 15 items] (3ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (1ms)
[BG(1)] binding: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
[FG] completion at /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py:1:3 ...
[FG]   parsing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
[FG]   binding: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (1ms)
[FG] completion at /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py:1:3 [found 11 items] (3ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (1ms)
[BG(1)] binding: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py ...
[BG(1)]   parsing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (2ms)
[BG(1)]   binding: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
[BG(1)]   checking: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
[BG(1)] analyzing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (2ms)
Background analysis message: resumeAnalysis
Background analysis message: getSemanticTokens
[FG] parsing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (2ms)
[FG] binding: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py:1:6 ...
[FG]   parsing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
[FG]   binding: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
[FG] completion at /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py:1:6 [found 78 items] (8ms)
Background analysis message: analyze
[BG(1)] analyzing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py ...
[BG(1)]   parsing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (1ms)
[BG(1)]   binding: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
[BG(1)]   checking: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
[BG(1)] analyzing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (1ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py:1:7 ...
[FG]   parsing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (1ms)
[FG]   binding: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
[FG] completion at /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py:1:7 [found 7 items] (12ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (1ms)
[BG(1)] binding: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (0ms)
Background analysis message: analyze
[BG(1)] analyzing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py ...
[BG(1)]   checking: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (1ms)
[BG(1)] analyzing: /home/wesleybl/git/symbolic.package/src/symbolic/package/__init__.py (1ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
```

In this case, `/home/wesleybl/lib/my` is a symbolic link.

**Comment by wesleybl** [comment]
In fact, the problem only occurs if we have symlinks. I updated the title and description.

**Comment by wesleybl** [comment]
@judej @jakebailey I created a repository to simulate the problem. To see:

https://github.com/wesleybl/symbolic.package

**Comment by cnaccio** [comment]
Also running into this issue. On OSX/Mac

**Comment by wesleybl** [comment]
@judej @jakebailey added the log in the description.

**Comment by sid22** [comment]
Getting same issue in MacOS. Pylance isn't recognising the extraPaths property.

**Comment by judej** [comment]
We need to add support for symlinks. Marked as enhancement

**Comment by jakebailey** [comment]
FWIW, the next release includes some better handling of symlinks (https://github.com/microsoft/pyright/commit/4bd1c58ee58da9a4a7d587f261b6bc348848467e) which I believe should fix most of these issues. Specifically, when the import resolver iterates over the contents of a directory and encounters a symlink, it will follow the symlink to check to see if it's a file/directory (and therefore recognize them as importable modules). I believe that covers explicitly the original issue (a directory containing symlinks).

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.3.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202131-10-march-2021

Since symlinks are tricky, if you encounter some issues with this support we'd appreciate a new issue to pin things down. 🙂

**Comment by wesleybl** [comment]
@jakebailey unfortunately it did not solve the autocomplete problem: #1031 

Would it be possible to prioritize this? Thanks for the great job!
