### ISSUE TITLE
Auto-import extremely unreliable for files inside workspace

### ISSUE THREAD

**Issue by daydev** [microsoft/pylance-release#139]
## Environment data

-   Language Server version: 2020.7.2
-   OS and version: Linux Mint 20, VS Code 1.47.2
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.2

UPD: Also reproduced on Windows 8.1, VS Code 1.47.2, Python 3.8.4. The system didn't have neither VS Code, nor Python before today, completely clean case. No settings were changed after install other than: I installed Python and Pylance extensions, and I disabled linting. The abnormal behavior was the same, as shown on screenshots below. 

## Expected behaviour

Things in the workspace show up in auto-import suggestions.

## Actual behaviour

Auto-import seems extremely unreliable when it comes to things in the workspace. Auto-import appears to discover names in the workspace only if the relevant file is opened and brought into focus. Some time later it may forget about them, even if the file remains open. I also tried changing Diagnostic Mode setting to "workspace", didn't seem to have any effect. Manual imports work fine, the suggestions are there.  Additionally, if I write out a manual import and then remove it, the auto-import temporarily "learns" the path as well. 

## Additional information

I've attached some screenshots of a minimal example on a clean project: 

1. The suggestion to import from 'test' is not there.
2. Once 'test.py' is opened, the suggestion appears.
3. Contents of 'test.py'.
4. Manual imports see the path always. 

![no-auto-1](https://user-images.githubusercontent.com/2521566/87880884-f60a4b00-c9fd-11ea-9b69-aaaec9b6fc37.png)
![no-auto-2](https://user-images.githubusercontent.com/2521566/87880887-f9053b80-c9fd-11ea-8902-bfbe73eebf99.png)
![no-auto-3](https://user-images.githubusercontent.com/2521566/87880888-fb679580-c9fd-11ea-85f7-a44409390c3d.png)
![no-auto-4](https://user-images.githubusercontent.com/2521566/87880941-6e710c00-c9fe-11ea-8acb-6274bdebbbd8.png)

**Comment by erictraut** [comment]
Thanks for the bug report. We're working on improving the behavior.

In the meantime, one way you can improve the behavior is to change the `python.analysis.diagnosticMode` setting to `workspace`. This will cause all of the files in your workspace to be analyzed. All symbols within all files will then be considered as candidates for auto-import.

**Comment by daydev** [comment]
Actually, as I mentioned in passing in the report, ```"python.analysis.diagnosticMode": "workspace"``` seems to have no impact on this issue. I tried it already before reporting and the behavior was the same. I confirmed just now that with ```"python.analysis.diagnosticMode": "workspace"``` it's the same. The setting itself is working because errors and warnings do show up from all across the project, but auto-imports are unchanged.

**Comment by Leedehai** [comment]
I have the same issue. Wondering if there is a way to just disable auto-imports (while keeping other features in place)?

**Comment by jakebailey** [comment]
There isn't a way at the moment, but we are working on all aspects of this (improving the suggestions, allowing control over which if any are shown, etc).

**Comment by heejaechang** [comment]
should be fixed in the next release.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202090-3-september-2020

**Comment by Axzurey** [comment]
While this issue was marked as resolved, I still have the exact same problem on v2022.9.10 of pylance with vscode 1.71.0 even wth diagnostic mode set to workspace. I have installed the older version for now, which appears to be working(version 2022.9.0), but a fix would be nice for the later version
