### ISSUE TITLE
Wrong attribute prompt about the built-in attribute  “__name__" of class.

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/pylance-release#154]
According to the python official doc, the attribute  "__name__" is just the class ,type ,etc.  So the instance can not get the attribute "__name__", but the pyplance show the "__name__" attr in instance .

![image](https://user-images.githubusercontent.com/33288114/88130343-de54e180-cc0c-11ea-8729-b4ee4bc1f196.png)

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next version of Pyright and Pylance.

**Comment by CatNofishing** [comment]
@erictraut Thanks for your reply.😁
 Besides  attribute "__name__" has this problem, I find that all attributes marked by the flag below have this problem.
![image](https://user-images.githubusercontent.com/33288114/88166772-63aab700-cc4a-11ea-8672-ae6a706480d6.png)

This flag represents "Class" instead of attributes. 
![image](https://user-images.githubusercontent.com/33288114/88167275-25fa5e00-cc4b-11ea-99b3-d45cc5c4b339.png)

**Comment by erictraut** [comment]
Thanks, this will be fixed as well.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.7.40, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202074-29-july-2020

**Comment by CatNofishing** [comment]
@jakebailey  @erictraut   
I noticed that you solve this problem by improving grammar checking (linting) , but these attribute hints still exist in smart suggestions. I think you should completely hide these attributes that are not instance attributes from the parameter prompt list
![image](https://user-images.githubusercontent.com/33288114/91118425-80139680-e6c3-11ea-9fef-0c4a32e602ff.png)
![image](https://user-images.githubusercontent.com/33288114/91118367-63775e80-e6c3-11ea-9d26-633859c0dc10.png)

**Comment by erictraut** [comment]
Thanks for the bug report. You are correct that most of these attributes should not appear on instances. The `__annotations__` attribute is found on objects (as defined in `builtins.pyi`), but the others should appear as attributes in classes.

This will be fixed in the next release of Pylance.

**Comment by CatNofishing** [comment]
![image](https://user-images.githubusercontent.com/33288114/91145688-72243c80-e6e8-11ea-90b6-327c69929a3d.png)
https://docs.python.org/3/library/stdtypes.html?highlight=built
I am not sure if other special attributes and methods have similar problems, this is the relevant information I can find according to the official documentation.

**Comment by erictraut** [comment]
We previously hard-coded some of these attribute names. I've removed these hard-coded names and now use the `type` metaclass and the `object` base class (both defined in `builtins.pyi`) to determine which attributes to include for classes and instances. The attributes should now match what you see in builtins.pyi. If that list defined in the `type` or `object` class looks wrong to you, you can submit a PR to the typeshed repo to add or remove attributes.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.8.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202083-28-august-2020
