### ISSUE TITLE
False-positive cannot assign expression to yield type (with TypeVar, overload, and Union)

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#1809]
<h3> Environment data </h3>

-   Language Server version: 2021.9.1
-   OS and version: darwin x64
-   Python version: 3.10.0rc2
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

_no error_

<h3> Actual behaviour </h3>

```
Expression of type "X" cannot be assigned to yield type "T1@return_iter | T2@return_iter"
  Type "X" cannot be assigned to type "T1@return_iter | T2@return_iter"
    Type "X" cannot be assigned to type "T1@return_iter"
    Type "X" cannot be assigned to type "T2@return_iter"
```

<h3> Logs </h3>

--

<h3> Code Snippet / Additional information </h3>

```python
from typing import TypeVar, overload, Iterator

T1 = TypeVar("T1", bound="X")
T2 = TypeVar("T2", bound="X")

class X:
    element_list: list["X"]

    @overload
    def return_iter(self, klass: type[T1]) -> Iterator[T1]:
        ...

    @overload
    def return_iter(self, klass: tuple[type[T1], type[T2]]) -> Iterator[T1] | Iterator[T2]:
        ...

    def return_iter(self, klass: type[T1] | tuple[type[T1], type[T2]]) -> Iterator[T1] | Iterator[T2]:
        for item in self.element_list:
            if isinstance(item, klass):
                yield item  # error
```

**Mypy output**
_no error_

**Comment by judej** [comment]
Thanks for the report.

**Comment by erictraut** [comment]
Thanks, this will be fixed in the next release.

The code that handles `isinstance` and `issubclass` type narrowing was handling the case where the second argument was a union of classes or a tuple of classes, but it didn't properly handle a union that included both classes and tuples of classes. That's now fixed.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.9.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202192-16-september-2021

**Comment by cdce8p** [comment]
This is still an issue when modified slightly:
```py
from typing import TypeVar, Iterator

T1 = TypeVar("T1", bound="X")
T2 = TypeVar("T2", bound="X")


class X:
    element_list: list["X"]

    def return_iter(
        self, klass: type[T1] | tuple[type[T1], type[T2]] | tuple[type[T1], ...]
    ) -> Iterator[T1] | Iterator[T2]:
        for item in self.element_list:
            if isinstance(item, klass):
                yield item  # error
```

Added `tuple[type[T1], ...]` as fallback for tuples with `len > 2`. No error when tested with mypy.

**Comment by erictraut** [comment]
You're right — I didn't handle the required special casing for open-ended tuples (the `...` form) in this code path. It will be fixed in the next release.

**Comment by cdce8p** [comment]
> You're right — I didn't handle the required special casing for open-ended tuples (the `...` form) in this code path. It will be fixed in the next release.

Thank you @erictraut! I appreciate how fast you and the team address these issues. It's amazing to see pylance and pyright getting better.
