### ISSUE TITLE
Non-defined variable does not get reported when defined inside a loop

### ISSUE THREAD

**Issue by meollab** [microsoft/pylance-release#1888]
## Environment data

- Language Server version: 2021.9.4
- OS and version: Linux x64
- Python version (and distribution if applicable, e.g. Anaconda): Python 3.7.5 (64bit)
- python.analysis.indexing: undefined
- python.analysis.typeCheckingMode: basic

## Expected behaviour

In these two cases

```python
for a in [1, 2, 3]:
    if b == 1:
        b = 2
```

```python
while True:
    if b == 1:
        b = 2
```
The variable b should be reported as non defined.

## Actual behaviour
No error is reported. If run in the interpreter both codes throw a `NameError: name 'b' is not defined`

## Code Snippet / Additional information
- Neither mypy nor pylint report this error either
- Could it be related to #1858 ?

**Comment by erictraut** [comment]
Thanks for reporting this. I've created a tracking bug in the pyright issue tracker.

**Comment by erictraut** [comment]
This will be fixed in the next release.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.10.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2021100-6-october-2021

**Comment by hanpari** [comment]
> This issue has been fixed in version 2021.10.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2021100-6-october-2021

Not true

The issue still persists or just reappeared.

https://github.com/microsoft/pyright/issues/10676

I checked the code from this issue and PyLance does not report anything even in the strict mode.
