### ISSUE TITLE
AsyncGenerator abstractmethods typechecked as coroutine incorrectly

### ISSUE THREAD

**Issue by SandyChapman** [microsoft/pylance-release#2287]
I'm trying to define an abstract base class with an `abstractmethod` that returns an `AsyncGenerator`. The typechecker appears to operate inconsistently between usages of the abstract base vs concrete implementations.

E.g.

```python
"""Base class for Extractors."""

import abc
from typing import AsyncGenerator
import asyncio


class AbstractBase(abc.ABC):
    """ABC for Extractors."""

    @abc.abstractmethod
    async def get_entries(self) -> AsyncGenerator[str, None]:
        """Retrieves all of the entries given by this extractor."""
        ...

class Concrete(AbstractBase):

    async def get_entries(self) -> AsyncGenerator[str, None]:
        await asyncio.sleep(0.5)
        yield "Implement2-1"
        await asyncio.sleep(1.5)
        yield "Implement2-2"

async def async_main(base: AbstractBase):
    async for x in base.get_entries():  # "Coroutine[Any, Any, AsyncGenerator[str, None]]" is not iterable  "__aiter__" method not defined reportGeneralTypeIssues
        print(x)
    async for x in Concrete().get_entries():
        print(x)


def main():
    impl = Concrete()
    asyncio.run(async_main(impl))

if __name__ == '__main__':
    main()
```

Removing `async` from the `abstractmethod` causes the error to disappear, but I don't believe this is the correct annotation (and pylint also reports it as an error that the base class signature does not match the concrete class). This doesn't appear to report an error when running pyright 1.1.208 directly.

pyrightconfig.json:
```json
{
    "typeCheckingMode": "basic"
}
```

I'm running Pylance v2022.1.3 on VS Code Version: 1.63.2 (Universal) (Mac OS)

![image](https://user-images.githubusercontent.com/3920249/151053688-a8df4eba-61e6-4edc-a481-d7b851736336.png)

**Comment by erictraut** [comment]
The problem is that the abstract method is missing a `yield` statement, so it's being treated differently. If you add a `yield ""` statement before the `...`, it will work as expected. Without a yield statement, it's not considered a generator. Given that you've annotated it explicitly as returning a generator object, it should probably still be considered a generator. I'll look into fixing that.

For what it's worth, mypy issues the same error in this case.

**Comment by SandyChapman** [comment]
Thanks, @erictraut ! This seems like a less common usage, so thanks for addressing it.

**Comment by erictraut** [comment]
I've added special-case code to handle this condition. It will be fixed in the next release.

**Comment by debonte** [comment]
This issue was fixed in version 2022.1.5. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202215-27-January-2022)

**Comment by nbilgrien-hbs** [comment]
This still appears to be a problem. Here is a minimum example:

```python
from abc import abstractmethod
from collections.abc import AsyncGenerator


class A():
    @abstractmethod
    async def foo() -> AsyncGenerator[int, None]:
        pass


    async def bar(self):
        generator = self.foo()
        async for i in generator:
            print(i)
```

![Image](https://github.com/user-attachments/assets/ea07b943-cb97-479c-b590-d01adf61694a)

I am on the vscode pylance extension version v2024.11.3

**Comment by shoang22** [comment]
> It seems the `pass` is not supported. If you change it to this it works:
> 
> from abc import abstractmethod
> from collections.abc import AsyncGenerator
> 
> 
> class A():
>     @abstractmethod
>     async def foo() -> AsyncGenerator[int, None]:
>         ...
> 
> 
>     async def bar(self):
>         generator = self.foo()
>         async for i in generator:
>             print(i)

Still getting this error with Pylance 2025.7.1

**Comment by rchiodo** [comment]
This is by design actually. See this here:

https://github.com/microsoft/pyright/issues/9949
