### ISSUE TITLE
Completions for a DataFrame not showing up anymore

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#2302]
Create python code like so:

```python
import pandas as pd
df = pd.read_csv("path to csv")
df.
```

With this version of Pylance:
![image](https://user-images.githubusercontent.com/19672699/151622338-87f38e6c-9958-46e8-8add-3aaaab80fc7c.png)

I get this set of completions:

![image](https://user-images.githubusercontent.com/19672699/151622472-3c4b941b-52c8-4b34-bb28-c4f737cd2233.png)

After upgrading to this version of Pylance:

![image](https://user-images.githubusercontent.com/19672699/151622688-775be953-c869-4f13-9744-bbeda4d89166.png)

I get this set of completions

![image](https://user-images.githubusercontent.com/19672699/151622588-16a7e8a1-c17c-4069-a965-0b26fa0c1777.png)

It looks to me like the newer pylance thinks the ```df``` variable is a TextFileReader and not a DataFrame:

![image](https://user-images.githubusercontent.com/19672699/151622650-70604ed2-e22b-4bc8-9d73-d34f2d51ff0a.png)

**Comment by rchiodo** [comment]
This causes Jupyter extension CI tests to fail:
https://github.com/microsoft/vscode-jupyter/issues/8842

**Comment by matthewkeating** [comment]
FWIW, I am experiencing the same issue.

**Comment by bschnurr** [comment]
for a work around you can 'go to declaration' on read_csv and in the pyi file add 'IO' to the 'typing' import.

fixing coming today

**Comment by debonte** [comment]
This issue has been fixed in version 2022.2.0, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202220-2-February-2022)

**Comment by bicofevo** [comment]
Problem still persists with 2022.2.0 @debonte 
![v2022 2 0](https://user-images.githubusercontent.com/99279651/153042106-d1bdce58-de86-4f10-8b70-96bf9716e3e4.png)
![v2022 1 3](https://user-images.githubusercontent.com/99279651/153042115-4bae9893-ae7c-40e7-aed8-b66d13f00681.png)

**Comment by rchiodo** [comment]
I'm still seeing this too. Doesn't seem to be fixed.

**Comment by Dr-Irv** [comment]
This has definitely been fixed.  pylance 2022.2.4 doesn't exhibit this.
![image](https://user-images.githubusercontent.com/15113894/155582300-7466557f-b464-41d6-8af3-e2108a9e1224.png)
