### ISSUE TITLE
pylance 2022.1.5 updated pandas type stub for read_csv incorrectly

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#2319]
## Environment data

-   Language Server version: 2022.1.5
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda python 3.8

Something happened between the distribution of pylance 2202.1.3 and pylance 2202.1.5 in the pandas type stubs for `read_csv()` (and maybe elsewhere??)

In pylance 2202.1.3, the beginning of `/dist/bundled/stubs/pandas/io/parsers.pyi` is:
```python
from __future__ import annotations
from collections import abc
import sys
from pandas._typing import FilePathOrBuffer as FilePathOrBuffer, Scalar
from pandas.core.frame import DataFrame as DataFrame
from typing import Any, Callable, List, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 8):
    from typing import Literal
else:
    from typing_extensions import Literal

@overload
def read_csv(
    reader: FilePathOrBuffer,
    *,
    sep: str = ...,
```

In pylance 2202.1.5, the beginning of the same file is:
```python
from __future__ import annotations
from collections import abc
import sys
from pandas._typing import FilePathOrBuffer as FilePathOrBuffer, Scalar
from pandas.core.frame import DataFrame as DataFrame
from typing import Any, Callable, List, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 8):
    from typing import Literal
else:
    from typing_extensions import Literal

@overload
def read_csv(
    reader: IO,
    sep: str = ...,
```

The symbol `IO` is not defined, and now all the type checking breaks for `read_csv()`.  This was fixed in a PR here:
https://github.com/microsoft/python-type-stubs/pull/109

I don't know if this is a `pylance` issue or `pyright` issue or a `microsoft-type-stubs` issue, because it really has to do with how you put the stubs into the `pylance` distribution.

**Comment by bschnurr** [comment]
Thanks, we are aware of the issue. We are reverting back to `FilePathOrBuffer` which I think is what you added to `python-type-stubs`

**Comment by Dr-Irv** [comment]
Also, this might be related:  https://github.com/microsoft/python-type-stubs/issues/137

**Comment by Dr-Irv** [comment]
I think all the type stubs for pandas shipped with 2202.1.5 are messed up.  See #139 .  We have gone back to 2202.1.3

**Comment by debonte** [comment]
This issue has been fixed in version 2022.2.0, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202220-2-February-2022)

**Comment by Dr-Irv** [comment]
It's partially fixed.  See https://github.com/microsoft/python-type-stubs/pull/143
