### ISSUE TITLE
Type incorrectly inferred as Literal

### ISSUE THREAD

**Issue by gasparattila** [microsoft/pylance-release#2324]
<h3> Environment data </h3>

-   Language Server version: 2022.1.5
-   Python version: 3.10.1

Open the following code in VSCode:
```python
def f(x):
    e = 0
    for _ in [0]:
        e += x
        # print(e)
    return e
```
Hovering over `f` shows the incorrect type `(x) -> Literal[0]`, even though `f(1) == 1`. Note that the problem seems to disappear when `e` is used after `e += x`, for example, when `print(e)` is uncommented.

**Comment by erictraut** [comment]
I'm not able to repro what you're seeing. For me, the inferred type of `f` is `(x) -> Any | Literal[0]`, which is correct in this case.

![Screen Shot 2022-02-02 at 12 32 24 PM](https://user-images.githubusercontent.com/7040122/152232660-e2dd0cab-892c-4a3b-8a9f-597f21f49cff.png)

Are you sure you're seeing `(x) -> Literal[0]`?

If you add a type annotation for the input parameter (presumably `x` is meant to be either an `int` or `float`?), then the return type inference is more accurate.

```python
def f(x: int):
    e = 0
    for _ in [0]:
        e += x
        # print(e)
    return e

reveal_type(f) # (x: int) -> int
```

**Comment by gasparattila** [comment]
I could reproduce the issue using https://vscode.dev after installing the Python extension.

Adding a type annotation does fix the issue. However, it can be confusing in unannotated code, for example, in `y = f(1)` it shows an incorrect value for `y`.

**Comment by erictraut** [comment]
I suspect that you're using an old version of Pylance in vscode.dev. Please go to the extensions panel and click on the Pylance extension to see what version it is. You may see a "reload" button if it's out of date. Once I updated to the latest version of Pylance, I received the expected inferred type within the hover text.

**Comment by gasparattila** [comment]
I have no idea what is causing the difference. I could reproduce the issue in a private browser window:

![Screenshot_20220203_123553](https://user-images.githubusercontent.com/58485900/152335724-3de2151b-6649-4f5e-b8d0-7f90c66d096c.png)

The issue might have been introduced in version 2021.9.2, I get the correct type using 2021.9.1.

**Comment by erictraut** [comment]
I was able to repro the problem. It depends on the order in which expressions are evaluated, so it's nondeterministic. Since this is a problem in the core type checker, I've created a tracking bug in the pyright repo: https://github.com/microsoft/pyright/issues/2983.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.3.1, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202231-9-March-2022)

**Comment by gasparattila** [comment]
I can still reproduce the problem in both 2022.3.1 and 2022.3.2. When I hover over only the last `e`, I still get the wrong type:

![Screenshot_20220317_201123](https://user-images.githubusercontent.com/58485900/158878302-9b13b2fe-f6de-4ebe-b851-0296e627e526.png)

**Comment by erictraut** [comment]
I've reopened the tracking bug for investigation: https://github.com/microsoft/pyright/issues/2983.

**Comment by erictraut** [comment]
This will be addressed in the next release.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.3.4, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202234-30-March-2022)
