### ISSUE TITLE
Activating IntelliCode for Python failed.

### ISSUE THREAD

**Issue by YUMEYA** [microsoft/pylance-release#2434]
Original issue: [intellicode/issues/325](https://github.com/MicrosoftDocs/intellicode/issues/325)
IntelliCode team members believe this is an issue of Pylance, hence I transfered it here.

<h3> Environment data </h3>

-   Language Server version: 2022.2.0
-   OS and version: PC running Windows 11, Server running Ubuntu 20.04.3 LTS
-   Python version (and distribution if applicable, e.g. Anaconda): Python 3.10.1
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off
-   VS Code is running on PC, connect to server via Remote Development SSH extension.
-   Python 3.10.1 and virtualenv are installed and managed by Pyenv, the dependencies of my project are managed by Poetry, witch is installed via Pipx.

<h3> Expected behaviour </h3>

1. Install Python and Pylance extensions on sever, open a .py file and both of them are successfully loaded.
2. Install IntelliCode extension, after downloading model the extension should be loaded successfully as well.

<h3> Actual behaviour </h3>

1. Install Python and Pylance extensions on sever, open a .py file and both of them are successfully loaded.
2. Install IntelliCode extension, after downloading model an error message pops up:

> Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.

<h3> Logs </h3>

Python Language Server Log

[python_language_server(before activating IntelliCode extension).log](https://github.com/microsoft/pylance-release/files/8015687/python_language_server.before.activating.IntelliCode.extension.log)
[python_language_server(after activating IntelliCode extension).log](https://github.com/microsoft/pylance-release/files/8015692/python_language_server.after.activating.IntelliCode.extension.log)

<h3> Code Snippet / Additional information </h3>

This is the log in Output-Python:
```
用户属于 'pythonaa' 实验组
用户属于 'pythonTensorboardExperiment' 实验组
用户属于 'pythonSurveyNotification' 实验组
用户属于 'PythonPyTorchProfiler' 实验组
用户属于 'pythonDeprecatePythonPath' 实验组
> conda info --json
> poetry env list --full-path
cwd: .
> ~/.pyenv/versions/3.10.1/envs/d2manifest-venv/bin/python ~/.vscode-server/extensions/ms-python.python-2022.0.1786462952/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.0.1786462952/pythonFiles/interpreterInfo.py
> ~/.pyenv/versions/3.10.1/bin/python ~/.vscode-server/extensions/ms-python.python-2022.0.1786462952/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.0.1786462952/pythonFiles/interpreterInfo.py
Python 解释器路径: ~/.pyenv/versions/3.10.1/envs/d2manifest-venv/bin/python
> ~/.pyenv/versions/3.10.1/envs/qqbot-venv/bin/python ~/.vscode-server/extensions/ms-python.python-2022.0.1786462952/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.0.1786462952/pythonFiles/interpreterInfo.py
> /usr/bin/python ~/.vscode-server/extensions/ms-python.python-2022.0.1786462952/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.0.1786462952/pythonFiles/interpreterInfo.py
> . ~/.pyenv/versions/3.10.1/envs/d2manifest-venv/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.vscode-server/extensions/ms-python.python-2022.0.1786462952/pythonFiles/printEnvVariables.py
> poetry config virtualenvs.path
cwd: .
正在启动 Pylance 语言服务器。
> ~/.pyenv/versions/3.10.1/envs/d2manifest-venv/bin/python ~/.vscode-server/extensions/ms-python.python-2022.0.1786462952/pythonFiles/linter.py -m flake8 ./src/destiny2_manifest_api/app/__init__.py
cwd: .
##########Linting Output - flake8##########
```

This is the log in Output-VS IntelliCode:
```
Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: Connection got disposed.
	at Object.dispose (/root/.vscode-server/extensions/ms-python.python-2022.0.1786462952/out/client/extension.js:67:144918)
	at Object.dispose (/root/.vscode-server/extensions/ms-python.python-2022.0.1786462952/out/client/extension.js:24:153999)
	at S.handleConnectionClosed (/root/.vscode-server/extensions/ms-python.python-2022.0.1786462952/out/client/extension.js:24:154211)
	at S.handleConnectionClosed (/root/.vscode-server/extensions/ms-python.python-2022.0.1786462952/out/client/extension.js:32:10900)
	at t (/root/.vscode-server/extensions/ms-python.python-2022.0.1786462952/out/client/extension.js:24:152304)
	at invoke (/root/.vscode-server/extensions/ms-python.python-2022.0.1786462952/out/client/extension.js:24:278068)
	at o.fire (/root/.vscode-server/extensions/ms-python.python-2022.0.1786462952/out/client/extension.js:24:278829)
	at X (/root/.vscode-server/extensions/ms-python.python-2022.0.1786462952/out/client/extension.js:67:134280)
	at invoke (/root/.vscode-server/extensions/ms-python.python-2022.0.1786462952/out/client/extension.js:24:278068)
	at o.fire (/root/.vscode-server/extensions/ms-python.python-2022.0.1786462952/out/client/extension.js:24:278829)
	at d.fireClose (/root/.vscode-server/extensions/ms-python.python-2022.0.1786462952/out/client/extension.js:67:124349)
	at ChildProcess.<anonymous> (/root/.vscode-server/extensions/ms-python.python-2022.0.1786462952/out/client/extension.js:24:273798)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Socket.<anonymous> (internal/child_process.js:439:11)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
Error while activating Python: {}
```

According to @markw-t and @luabud 's advice, I tried the "Python: Restart Language Server" command, this is the log after restarting:
[python_language_server(after restarting).log](https://github.com/microsoft/pylance-release/files/8015773/python_language_server.after.restarting.log)
But the logs of IntelliCode stays the same, I think it's still in failed state.

**Comment by judej** [comment]
@joyceerhl, is this related to https://github.com/microsoft/vscode/issues/143834?

**Comment by joyceerhl** [comment]
Unlikely--that issue was fixed in the 1.65 stable release. Also perhaps you meant to @-mention `@jrieken` instead of me?

**Comment by judej** [comment]
@YUMEYA, Tried this on VS 1.65.2 and Pylance v2022.3.3 and I was not able to reproduce it. Please let me know if you are still seeing this?

**Comment by YUMEYA** [comment]
@judej Yes, I'm still seeing this error on VS Code 1.66.0 + Python 2022.4.0 + Pylance 2022.3.4 + IntelliCode 1.2.18

Python Language Server Log:
[python_language_server(before activating IntelliCode extension).log](https://github.com/microsoft/pylance-release/files/8414472/python_language_server.before.activating.IntelliCode.extension.log)
[python_language_server(after activating IntelliCode extension).log](https://github.com/microsoft/pylance-release/files/8414473/python_language_server.after.activating.IntelliCode.extension.log)

VS IntelliCode Log:
```
Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: Connection got disposed.
	at Object.dispose (/root/.vscode-server/extensions/ms-python.python-2022.4.0/out/client/extension.js:47:145778)
	at Object.dispose (/root/.vscode-server/extensions/ms-python.python-2022.4.0/out/client/extension.js:24:155505)
	at S.handleConnectionClosed (/root/.vscode-server/extensions/ms-python.python-2022.4.0/out/client/extension.js:24:155717)
	at S.handleConnectionClosed (/root/.vscode-server/extensions/ms-python.python-2022.4.0/out/client/extension.js:32:10610)
	at t (/root/.vscode-server/extensions/ms-python.python-2022.4.0/out/client/extension.js:24:153810)
	at invoke (/root/.vscode-server/extensions/ms-python.python-2022.4.0/out/client/extension.js:24:281641)
	at o.fire (/root/.vscode-server/extensions/ms-python.python-2022.4.0/out/client/extension.js:24:282402)
	at X (/root/.vscode-server/extensions/ms-python.python-2022.4.0/out/client/extension.js:47:135140)
	at invoke (/root/.vscode-server/extensions/ms-python.python-2022.4.0/out/client/extension.js:24:281641)
	at o.fire (/root/.vscode-server/extensions/ms-python.python-2022.4.0/out/client/extension.js:24:282402)
	at d.fireClose (/root/.vscode-server/extensions/ms-python.python-2022.4.0/out/client/extension.js:47:125209)
	at ChildProcess.<anonymous> (/root/.vscode-server/extensions/ms-python.python-2022.4.0/out/client/extension.js:24:277371)
	at ChildProcess.emit (node:events:402:35)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
Error while activating Python: {}
```

**Comment by RookieTars** [comment]
@judej Has this problem been  solved yet? I run into the same problem. What could I do to help?

**Comment by mioxyz** [comment]
I have the same problem
```
$ code --version                                                                                                                               1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
x64
$ python --version                                                                                                                            
Python 3.10.5
$ lsb_release --all                                                                                                                                   
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.3.2
Codename:	Ruah
```
using `ms-python.python-2022.9.11821004.vsix` downloaded on the [Microsoft Marketplace](https://marketplace.visualstudio.com/items?itemName=ms-python.python) by clicking on Resources -> Download Extension.

**Comment by rchiodo** [comment]
This seems to be working fine for me now.



![Image](https://user-images.githubusercontent.com/19672699/195464953-f391d3fa-fae8-45d0-ba1a-d6d0f369f579.png)

(Intellicode puts the * on the completions)

 If somebody else can repro this still, please comment below. Closing for now.

**Comment by rchiodo** [comment]
If you can repro, we need the "Python Language Server" and "VS Intellicode" output from the 'Output panel'



![Image](https://user-images.githubusercontent.com/19672699/195465087-19ffb287-52d7-4752-b2ac-393803bf64d6.png)

**Comment by Bryan-Stearns** [comment]
In case it helps anyone else who also gets to this page from Googling the error, I just started getting this same behavior, with the same VS Intellicode output. (`vs-intellicode-python was passed a model: {}.`)
But my Python Language Server output was different, and that showed me the solution in my instance.
```
2024-04-11 10:25:27.741 [info] [Info  - 10:25:27 AM] (60532) Setting pythonPath for service "MyVSProject": "/Users/blah/.pyenv/versions/3.10.10/bin/python"
2024-04-11 10:25:27.741 [info] [Info  - 10:25:27 AM] (60532) Setting environmentName for service "MyVSProject": "3.10.10 (global)"
2024-04-11 10:25:27.775 [info] Error: EACCES: permission denied, scandir '/Users/blah/blah/blah/mydirectory'
```

That "/mydirectory" folder was part of my PYTHONPATH env variable. Somehow it lost its read/execute permissions, so pylance failed and passed {} to VS Intellicode.

I added permissions back to that directory and everything runs fine again.

**Comment by rubtobar** [comment]
I just solved the issue in my case. In case it helps:

Searching for logs to get info about the problem I found a line in the Output of the `Pyhton Language Server`.

The line just said something like "expecting version 1.96 but found version 1.89"

I just realized that the version this line was complaining about was my vscode version. I alwais open VSCode from the WSL enviroment. This seems to let the VSCode version without updates. I noticed that it updates automatically when is being used from windows directly sometimes on closing. This don't seem to happen if it's always opened from WSL, and it getts stuck in some older version.

After realizing it, I just upgrade my vscode version in windows using this winget command:
```ps1
winget upgrade --id Microsoft.VisualStudioCode
```

this got me the latest version 1.96.4.

Afterwards I did ejecute in WSL the command:
```bash
code .
```
in order to open my workspace again. This triggered WSL to download the new vscode server version:

![Image](https://github.com/user-attachments/assets/c602b694-8b2b-4ea6-807e-29442a4ffeb5)

After that I installed the python related plugins and intellisense just works fine. Now the `Pyhton Language Server` Output terminal got filled with info logs.

![Image](https://github.com/user-attachments/assets/721194a3-0814-4e40-a1ee-e2f01f678336)

I hope it helps :)
