### ISSUE TITLE
`sqlalchemy.orm.declarative_base` not known with default stubs

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#2480]
## Environment data

-   Language Server version: v2022.3.2-pre.1
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.12 Anaconda

## Sample Code

```python
from sqlalchemy.orm import declarative_base
```

## Expected behavior

`declarative_base` is a known symbol and is correctly typed.

## Actual behavior

`declarative_base` is unknown.

## Additional info

I'm using SQLAlchemy v1.4.27.

When I removed  ".../dist/bundled/stubs/sqlalchemy", ".../dist/typeshed-fallback/stubs/SQLAlchemy" got used and it seemed to work completely OK in my whole codebase.

**Comment by heejaechang** [comment]
it looks like SQLAlchemy stubs are added to typeshed on dec/2021, we should remove our bundled stub from bundled folder.

**Comment by Azureblade3808** [comment]
I see that this issue gets addressed in v2022.3.2. Is it supposed to be closed?

**Comment by Azureblade3808** [comment]
Closing.

**Comment by dbolser** [comment]
I'm using SQLAlchemy '2.0.37' but I'm still seeing this in vscode. 
```
SQLAlchemy>=2.0.0
sqlalchemy-stubs>=0.4.0
```

**Comment by rchiodo** [comment]
> I'm using SQLAlchemy '2.0.37' but I'm still seeing this in vscode.
> 
> ```
> SQLAlchemy>=2.0.0
> sqlalchemy-stubs>=0.4.0
> ```

@dbolser can you open a new issue so we can gather more information?
