### ISSUE TITLE
Always require restart when installing new package and cannot find python interpreter... further update#2501

### ISSUE THREAD

**Issue by Zaeem20** [microsoft/pylance-release#2505]
I am reopening issue #2501 

• i am not using conda & virtual env
• i am at root folder which is D:\MyFolder

Below are the issues require restart to be fixed...
• it occurs when i open vscode first
• give me warning whenever i install new pkg through integrated ps,  but it work fine when i run it

**Comment by judej** [comment]
Would you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by heejaechang** [comment]
meanwhile, you can use "Python: Restart Language Server" command to manually ask server to scan packages. it is the same command we internally call when we discover library changes by file watcher.

**Comment by Zaeem20** [comment]
how do i do that @heejaechang

**Comment by Zaeem20** [comment]
means without doing it manually how do i automate this

**Comment by heejaechang** [comment]
@Zaeem20 we only support auto restart when packages are installed under project root. 
ex) ... project_root/.venv/lib/site-packages/...

we don't support packages installed outside of project root for auto refresh for now.

but that being said, even for the supported case, our restart timeout is 10 mins. which means you won't see the changes for at least 10 mins since the last library changes (such as installing new package)

if 10 mins are too long, only option you have is forcing update using the command ("Python: Restart Language Server" ) above. you can find the command from the command palette (https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)

**Comment by Zaeem20** [comment]
means i have to wait 10 mins

**Comment by RobertCraigie** [comment]
Seems like this is related to #2473.

Adding an option to either reduce or turn off this delay would be a great solution for me.

**Comment by heejaechang** [comment]
@RobertCraigie we could consider changing static 10 min to something like exponential back off time (10 seconds -> 20 seconds -> 40 seconds -> 10 mins) but until we can come up with better way to handle multi workspaces or some tools that keep writing and deleting temp file in lib path, we probably will leave it to 10 min and ask to use restart command as workaround for now.

**Comment by heejaechang** [comment]
in next release, we will support detecting outside of workspace root site-package (python search path) changes. but delay will be still 10 mins.

**Comment by Zaeem20** [comment]
ok thanks for your cooperation

**Comment by heejaechang** [comment]
unfortunately, I found issue on the fix. we need to move to newer version of LSP for the fix to work. re-activated the issue and I will hold onto it until we move to newer version of LSP.

**Comment by Zaeem20** [comment]
@heejaechang still doing same thing sir
but packages were detecting instantly in virtualenv when i install them via pip,
and still i need to restart vs code coz it not detect python interpreter first

**Comment by Zaeem20** [comment]
@heejaechang i am still getting error of no python interpreter is selected, it is not fixed yet
shall i send settings.json screen shot

**Comment by heejaechang** [comment]
outside workspace fix is now in prerelease build.

**Comment by heejaechang** [comment]
outside workspace fix should be fixed in next release.

**Comment by debonte** [comment]
@Zaeem20, the fix is available in the latest Pylance insiders build ([2022.5.0-pre.1](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202250-pre1-4-may-2022)). We're not shipping a stable build this week. If you're not using Pylance insiders, you'll see the fix in next week's stable build.

**Comment by Zaeem20** [comment]
@debonte its not fixed yet it showing me reportMissingImports while installing new library from pip
im am using it inside of workspace without virtual env

**Comment by heejaechang** [comment]
@Zaeem20 only detection is fixed, the 10 min delay is same as before (https://github.com/microsoft/pylance-release/issues/2505#issuecomment-1082420292)

we will take a look at 10 min delay once we address issues on multi workspace support.

**Comment by Zaeem20** [comment]
ok i understand, but it was instantly detecting all packages in virtualenv
when i install any package with pip,
is that another issue

@heejaechang

**Comment by heejaechang** [comment]
@Zaeem20 if there is an issue you want us to take a look? can you open a new issue? using 1 issue for everything make it really hard to track progress.

and when you open an issue, please put logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

also, providing some repro steps will make it easier for us to track down the issue.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.5.1, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202251-11-May-2022)
