### ISSUE TITLE
"heap limit Allocation failed" when background indexing entire workspace

### ISSUE THREAD

**Issue by joelhock** [microsoft/pylance-release#254]
## Environment data
-   Language Server version: Pylance language server 2020.8.1 (pyright 0916fb9e)
-   OS and version: linux
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.6

When indexing a couple large projects via `"python.analysis.diagnosticMode":"workspace"`, I can consistently get Pylance to exhaust its heap.  This does not require any attempts to use Pylance (e.g. jump-to-definition), but simply happens during background indexing.  I've included a few examples in the Logs section--I think they all came from background indexing, but it's possible some came from active use.

I'm not sure if this is a clue, but the memory failures often come after a series of analyzing cache hits, e.g.
```
[BG] analyzing: redacted.py [cache hit] (0ms)
[BG] analyzing: redacted.py [cache hit] (0ms)
[BG] analyzing: redacted.py [cache hit] (0ms)
[BG] analyzing: redacted.py [cache hit] (0ms)
[BG] analyzing: redacted.py [cache hit] (0ms)
[BG] analyzing: redacted.py [cache hit] (0ms)
[BG] analyzing: redacted.py [cache hit] (0ms)
(lots more cache hits)
[BG] analyzing: redacted.py ...
[BG]   parsing: redacted.py (19ms)
[BG]   binding: redacted.py (1ms)
[BG]   checking: redacted.py (9ms)
[BG] analyzing: redacted.py (29ms)
[BG] analyzing: redacted.py ...
[BG]   parsing: redacted.py (1379ms)
[BG]   binding: redacted.py (10ms)
[BG]   checking: redacted.py ...
[BG]     parsing: /venvs/python3.6/site-packages/torch/__init__.pyi (210ms)
[BG]     binding: /venvs/python3.6/site-packages/torch/__init__.pyi ...
[BG]       parsing: /venvs/python3.6/site-packages/torch/functional.py (85ms)
[BG]       binding: /venvs/python3.6/site-packages/torch/functional.py (6ms)
[BG]     binding: /venvs/python3.6/site-packages/torch/__init__.pyi (3981ms)
[BG]     parsing: /venvs/python3.6/site-packages/torch/distributed/__init__.py (3ms)

<--- Last few GCs --->

[29192:0x7f3d80000ad0]   820636 ms: Mark-sweep 2008.8 (2050.7) -> 2007.7 (2050.7) MB, 1325.3 / 0.0 ms  (average mu = 0.164, current mu = 0.015) allocation failure scavenge might not succeed
[29192:0x7f3d80000ad0]   822900 ms: Mark-sweep 2008.1 (2050.7) -> 2007.7 (2051.2) MB, 2021.5 / 0.0 ms  (average mu = 0.130, current mu = 0.107) allocation failure GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1a93942]
    1: StubFrame [pc: 0x1a94893]
Security context: 0x20828491a2f1 <JSObject>
    2: _skipToEndOfStringLiteral [0x2feec539feb9] [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/extensions/ms-python.vscode-pylance-2020.8.0/server/pyright.bundle.js:~1] [pc=0x17bed98c475f](this=0x031001e937d1 <JSObject>,6)
    3: _handleString [0x2feec539fe81] [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/....

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

```

or

```
BG] analyzing: redacted.py [cache hit] (0ms)
[BG] analyzing: redacted.py [cache hit] (0ms)
[BG] analyzing: redacted.py [cache hit] (0ms)
[BG] analyzing: redacted.py [cache hit] (0ms)
[BG] analyzing: redacted.py [cache hit] (0ms)
(many more cache hits)
[BG] analyzing: redacted.py ...
[BG]   checking: redacted.py (0ms)
[BG] analyzing: redacted.py (0ms)

<--- Last few GCs --->

[25215:0x7f7518000ad0]   882574 ms: Scavenge 1970.7 (2060.4) -> 1955.6 (2062.4) MB, 10.3 / 0.0 ms  (average mu = 0.286, current mu = 0.225) allocation failure
[25215:0x7f7518000ad0]   882644 ms: Scavenge 1971.7 (2062.4) -> 1956.5 (2064.9) MB, 7.3 / 0.0 ms  (average mu = 0.286, current mu = 0.225) allocation failure
[25215:0x7f7518000ad0]   882719 ms: Scavenge 1972.6 (2064.9) -> 1957.6 (2066.9) MB, 7.9 / 0.0 ms  (average mu = 0.286, current mu = 0.225) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1a93942]
Security context: 0x11ab0051a2f1 <JSObject>
    1: set [0x11ab0050b5e9](this=0x14f613b17db9 <Map map = 0x2f16c08015d9>,232456,0x340964e80659 <true>)
    2: e(aka e) [0x14f613b17dd9] [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/extensions/ms-python.vscode-pylance-2020.8.0/server/pyright.bundle.js:~1] [pc=0x1f23fe2f1fb3](this=0x340964e804d1 <undefined>,0x1f2ffd085e99 <Object map = 0x3297d...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x98edf0 node::Abort() [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
 2: 0x98fe56 node::OnFatalError(char const*, char const*) [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
 3: 0xb1552e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
 4: 0xb158a9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
 5: 0xf20105  [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
 6: 0xf2aa6b v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
 7: 0xf2b787 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
 8: 0xf2e225 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
 9: 0xef8f3c v8::internal::Factory::AllocateRawArray(int, v8::internal::PretenureFlag) [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
10: 0xef970c v8::internal::Handle<v8::internal::FixedArray> v8::internal::Factory::NewFixedArrayWithMap<v8::internal::FixedArray>(v8::internal::RootIndex, int, v8::internal::PretenureFlag) [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
11: 0x10cec2e v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate(v8::internal::Isolate*, int, v8::internal::PretenureFlag) [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
12: 0x10cecf7 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
13: 0x10cf37b v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::EnsureGrowable(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>) [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
14: 0x11aea50 v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
15: 0x1a93942  [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/bin/91899dcef7b8110878ea59626991a18c8a6a1b3e/node]
[Error - 12:45:23 PM] Connection to server is erroring. Shutting down server.
[
```

## Logs
more backtraces:
```
83954:[27424:0x7f5fc0000ad0]  5498903 ms: Mark-sweep 2006.9 (2049.7) -> 2006.8 (2049.7) MB, 1488.5 / 0.0 ms  (average mu = 0.091, current mu = 0.001) allocation failure scavenge might not succeed
83955:[27424:0x7f5fc0000ad0]  5500434 ms: Mark-sweep 2006.8 (2049.7) -> 2006.8 (2050.7) MB, 1531.3 / 0.0 ms  (average mu = 0.048, current mu = 0.000) allocation failure scavenge might not succeed
83956-
83957-
83958-<--- JS stacktrace --->
83959-
83960-==== JS stack trace =========================================
83961-
83962-    0: ExitFrame [pc: 0x1a93942]
83963-Security context: 0x1973cd19a2f1 <JSObject>
83964-    1: _addLineRange [0x3e5cc822a131] [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/extensions/ms-python.vscode-pylance-2020.8.1/server/pyright.bundle.js:~1] [pc=0x2caca77c2868](this=0x39625e055c89 <JSObject>)
83965-    2: _skipToEndOfStringLiteral [0x3e5cc822a441] [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/extensions/ms-python....
83966-
83967-FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

```
27117:[30692:0x7f9eb0000ad0]   718059 ms: Mark-sweep 2024.0 (2052.7) -> 2024.0 (2053.7) MB, 2431.6 / 0.0 ms  (average mu = 0.075, current mu = 0.001) allocation failure scavenge might not succeed
27118:[30692:0x7f9eb0000ad0]   720454 ms: Mark-sweep 2025.4 (2053.7) -> 2025.4 (2055.2) MB, 2392.5 / 0.0 ms  (average mu = 0.039, current mu = 0.001) allocation failure scavenge might not succeed
27119-
27120-
27121-<--- JS stacktrace --->
27122-
27123-==== JS stack trace =========================================
27124-
27125-    0: ExitFrame [pc: 0x1a93942]
27126-    1: StubFrame [pc: 0x1a94893]
27127-Security context: 0x3eed301054f9 <JSObject>
27128-    2: _skipToEndOfStringLiteral [0x1295f66763f1] [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/extensions/ms-python.vscode-pylance-2020.8.1/server/pyright.bundle.js:~1] [pc=0x19bcb0255f96](this=0x0cbf7bbca401 <JSObject>,34)
27129-    3: _handleString [0x1295f66763b9] [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/...
27130-
27131-FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

```
194160:[24765:0x7f0e98000ad0]   136409 ms: Mark-sweep 1985.2 (2074.7) -> 1968.6 (2074.2) MB, 1328.1 / 0.0 ms  (average mu = 0.188, current mu = 0.107) allocation failure scavenge might not succeed
194161:[24765:0x7f0e98000ad0]   138044 ms: Mark-sweep 1985.4 (2074.2) -> 1968.8 (2074.7) MB, 1543.0 / 0.0 ms  (average mu = 0.122, current mu = 0.056) allocation failure scavenge might not succeed
194162-
194163-
194164-<--- JS stacktrace --->
194165-
194166-==== JS stack trace =========================================
194167-
194168-    0: ExitFrame [pc: 0x1a93942]
194169-    1: StubFrame [pc: 0x19feb2d]
194170-Security context: 0x0b695b81a2f1 <JSObject>
194171-    2: Zt(aka Zt) [0x288df282241] [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/extensions/ms-python.vscode-pylance-2020.8.1/server/pyright.bundle.js:~1] [pc=0x3af2241704b4](this=0x3b4464e804d1 <undefined>,0x379343f45271 <Object map = 0x2a6eafb27d79>,0x3811c5c86da1 <Object map = 0x2a6eafb07119>,0x3811c5c86f59 <n...
194172-
194173-FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

```
219642:[2999:0x7f9f94000ad0]   635743 ms: Mark-sweep 1976.8 (2050.3) -> 1976.4 (2050.3) MB, 2274.0 / 0.0 ms  (average mu = 0.094, current mu = 0.002) allocation failure scavenge might not succeed
219643:[2999:0x7f9f94000ad0]   637855 ms: Mark-sweep 1977.4 (2050.3) -> 1976.4 (2050.8) MB, 2104.7 / 0.0 ms  (average mu = 0.047, current mu = 0.003) allocation failure scavenge might not succeed
219644-
219645-
219646-<--- JS stacktrace --->
219647-
219648-==== JS stack trace =========================================
219649-
219650-    0: ExitFrame [pc: 0x1a93942]
219651-    1: StubFrame [pc: 0x19feb2d]
219652-Security context: 0x2a2b85c9a2f1 <JSObject>
219653-    2: _parseVarArgsList [0x9929f2aa069] [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/extensions/ms-python.vscode-pylance-2020.8.0/server/pyright.bundle.js:~1] [pc=0x29234caa94ee](this=0x013bc086b111 <y map = 0x3d84bc79c5b9>,14,0x0a4597980659 <true>)
219654-    3: _parseFunctionDef [0x9929f2aa031] [/mnt/harmonix_vol2/...
219655-
219656-FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

```
32554:[16692:0x7f6ec0000ad0]  1144168 ms: Mark-sweep 2007.8 (2067.7) -> 1991.0 (2067.7) MB, 1042.0 / 0.0 ms  (average mu = 0.184, current mu = 0.085) allocation failure scavenge might not succeed
32555:[16692:0x7f6ec0000ad0]  1145433 ms: Mark-sweep 2007.5 (2067.7) -> 1991.6 (2067.7) MB, 1150.4 / 0.0 ms  (average mu = 0.138, current mu = 0.090) allocation failure scavenge might not succeed
32556-
32557-
32558-<--- JS stacktrace --->
32559-
32560-==== JS stack trace =========================================
32561-
32562-    0: ExitFrame [pc: 0x1a93942]
32563-Security context: 0x2afe7891a2f1 <JSObject>
32564-    1: new Map(aka Map) [0x2afe7890b079](this=0x0b9eefe805b1 <the_hole>)
32565-    2: ConstructFrame [pc: 0x19f8bc0]
32566-    3: qt(aka qt) [0xf519252c929] [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/extensions/ms-python.vscode-pylance-2020.8.0/server/pyright.bundle.js:~1] [pc=0x1acce5755e6d](this=0x0b9eefe804d1 <undefined>,0x1f3d5a12e469 <Object map = ...
32567-
32568-FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

```
80145:[28923:0x7f3150000ad0]  2055533 ms: Mark-sweep 1997.8 (2067.6) -> 1984.9 (2069.1) MB, 1220.2 / 0.0 ms  (average mu = 0.198, current mu = 0.139) allocation failure scavenge might not succeed
80146:[28923:0x7f3150000ad0]  2056947 ms: Mark-sweep 2000.2 (2069.6) -> 1988.6 (2073.1) MB, 1269.6 / 0.0 ms  (average mu = 0.152, current mu = 0.102) allocation failure scavenge might not succeed
80147-
80148-
80149-<--- JS stacktrace --->
80150-
80151-==== JS stack trace =========================================
80152-
80153-    0: ExitFrame [pc: 0x1a93942]
80154-Security context: 0x3e4e5c668389 <JSObject>
80155-    1: set [0x3e4e5c66d1c1](this=0x28322dfddef9 <Map map = 0x996d84815d9>,0x3a5e6d60e351 <String[16]: __type_of_minute>,0x0f66669b7fc1 <Object map = 0x996d84ea809>)
80156-    2: lookUpClassMember(aka _) [0xf66669b0e79] [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/extensions/ms-python.vscode-pylance-2020.8.1/server/pyright.bundle.js:~1] [pc=0x2104da3...
80157-
80158-FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

```
8:[25912:0x7fdaa4000ad0]   339489 ms: Mark-sweep 1985.8 (2068.1) -> 1959.8 (2065.6) MB, 1107.7 / 0.0 ms  (average mu = 0.245, current mu = 0.216) allocation failure scavenge might not succeed
9-
10-
11-<--- JS stacktrace --->
12-
13-==== JS stack trace =========================================
14-
15-    0: ExitFrame [pc: 0x1a93942]
16-    1: StubFrame [pc: 0x19feb2d]
17-Security context: 0x01be9ff9a2f1 <JSObject>
18-    2: Jt(aka Jt) [0x1ddfcd75bec1] [/mnt/harmonix_vol2/soporifix_vol3/user/home/joel/.vscode-server/extensions/ms-python.vscode-pylance-2020.8.0/server/pyright.bundle.js:~1] [pc=0x3a4ded3289bc](this=0x3f94f26004d1 <undefined>,0x1ddfcd75be21 <Object map = 0x2f6861c253e9>,0x19f858c10d71 <Object map = 0x2f6861c0ec39>,0x19f858c10f29 <...
19-
20-FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```
## Code Snippet / Additional information

Unfortunately I cannot provide a sample from our codebase.  I'm hoping someone else can repro in a codebase that is publicly accessible or else the given information is enough to fix.

**Comment by jakebailey** [comment]
I think this should be fixed per #228 in the release.

**Comment by joelhock** [comment]
Great!  I was assuming it was a different issue due to the wording

> We have mechanism in place that watches the heap size and empties our internal type cache if we are at risk of overflowing. However, this mechanism was not being invoked during a workspace symbol search, which explains the problem you're seeing.

in that issue, given I'm not doing a workspace search, but I will report back when I can test with the upcoming release.

**Comment by jakebailey** [comment]
Ah, yeah. @erictraut added even more checks in various other places as well.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.8.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202082-20-august-2020

**Comment by dovahcrow** [comment]
I'm still getting the same error with the newest release of pylance.
Error logs:
```
[Info  - 12:14:19 PM] Pylance language server 2020.9.0 (pyright 60eb2cca) starting
[Info  - 12:14:19 PM] Server root directory: /home/youngw/.vscode-server/extensions/ms-python.vscode-pylance-2020.9.0/dist
[Info  - 12:14:19 PM] Background analysis(2) root directory: /home/youngw/.vscode-server/extensions/ms-python.vscode-pylance-2020.9.0/dist
[Info  - 12:14:19 PM] Background analysis(2) started
[Info  - 12:14:19 PM] Background analysis(1) root directory: /home/youngw/.vscode-server/extensions/ms-python.vscode-pylance-2020.9.0/dist
[Info  - 12:14:19 PM] Background analysis(1) started
[Info  - 12:14:19 PM] Background analysis(3) root directory: /home/youngw/.vscode-server/extensions/ms-python.vscode-pylance-2020.9.0/dist
[Info  - 12:14:19 PM] Background analysis(3) started
[Error - 12:14:19 PM] stubPath /home/youngw/projects/dataprep/typings is not a valid directory.
[Error - 12:14:20 PM] stubPath typings is not a valid directory.
[Error - 12:14:20 PM] stubPath typings is not a valid directory.

<--- Last few GCs --->

[116668:0x7f5634000bd0]   102107 ms: Mark-sweep 2017.8 (2049.8) -> 2017.0 (2049.8) MB, 1346.2 / 0.0 ms  (average mu = 0.194, current mu = 0.125) allocation failure scavenge might not succeed
[116668:0x7f5634000bd0]   103713 ms: Mark-sweep 2017.8 (2049.8) -> 2017.4 (2049.8) MB, 1603.1 / 0.0 ms  (average mu = 0.107, current mu = 0.002) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1a93942]
Security context: 0x055bc3b9a2f1 <JSObject>
    1: /* anonymous */ [0x3871035c14a1] [/home/youngw/.vscode-server/extensions/ms-python.vscode-pylance-2020.9.0/dist/pyright.bundle.js:~1] [pc=0x276124391cdb](this=0x1336a803ef29 <Object map = 0x196cad206f39>,0x1a773c77d409 <Object map = 0x2b660012fcf9>)
    2: _parseStringList [0x88e5b247181] [/home/youngw/.vscode-server/extensions/ms-python.vscode-pylance-202...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200909.121604.116668.0.001.json
Node.js report completed
 1: 0x98edf0 node::Abort() [/home/youngw/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/node]
 2: 0x98fe56 node::OnFatalError(char const*, char const*) [/home/youngw/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/node]
 3: 0xb1552e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/youngw/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/node]
 4: 0xb158a9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/youngw/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/node]
 5: 0xf20105  [/home/youngw/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/node]
 6: 0xf2aa6b v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/youngw/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/node]
 7: 0xf2b787 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/youngw/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/node]
 8: 0xf2e225 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/home/youngw/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/node]
 9: 0xef9250 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/home/youngw/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/node]
10: 0x11cb0ce v8::internal::Runtime_AllocateInNewSpace(int, unsigned long*, v8::internal::Isolate*) [/home/youngw/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/node]
11: 0x1a93942  [/home/youngw/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/node]
```

**Comment by erictraut** [comment]
I think the original problem was fixed, but a new issue was unfortunately introduced in last week's version of Pylance that causes a similar problem. We're working on a fix, and it will be in this week's release. Apologies for the problems you're seeing.

**Comment by dovahcrow** [comment]
Thanks @erictraut for the information. I'm looking forward to the new version!
