### ISSUE TITLE
Rename Symbol fails on some varaibles with "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by AlteriusOmega** [microsoft/pylance-release#2550]
![VSCode error rename symbol macimum call stack size exceeded](https://user-images.githubusercontent.com/44767171/162310468-14d04722-0e2b-4639-88ad-6ed42e57ffe3.png)
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual
Expected:
Press F2 or right click and click Rename Symbol
VSCode opens the popup to rename symbol
Hit enter and VSCode renames all instances of that variable

Actual:
Press F2 or right click and click Rename Symbol
VSCode does nothing, gives error message saying "Request textDocument/prepareRename failed with message: Maximum call stack size exceeded"

## Steps to reproduce:

1. Move cursor to variable name, press F2 or right click and click Rename Symbol

This seems to happen with variables that appear more often in the code. For instance, for a variable that only appears 5 times, it will rename it fine, but for a variable that appears 20 times, it will fail.

My RAM and CPU usage are low, at 26% and 6%, respectively

I don't have any extensions installed except the Python one and the associated Jupyter ones.

Running on Windows 10 64 bit on a Dell Precision 5540 laptop with Core i9-9980K and 64Gb of RAM
I am using Anaconda 3 with conda virtual environment for this workspace. I have configured my settings and user settings according to [this page](https://medium.com/analytics-vidhya/efficient-way-to-activate-conda-in-vscode-ef21c4c231f2).

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.2
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.4.0
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (47.41GB free)|
|Process Argv|--crash-reporter-id f59b737e-b5ef-4e72-8dfd-53ab67676639|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvidc:30447482
vscaat:30438848
pynewfile477:30463512

```

</details>

**Comment by erictraut** [comment]
This is likely specific to rename and is instead related to general type analysis, which is used during the rename process. To diagnose this, we'll need to isolate which file in the project is triggering the stack overflow — and then try to isolate the code within that file.

Is this project checked in to an open-source repo? If so, I can try to repro it directly. If not, we'll need some additional help from you. If you could set `diagnosticMode` from "openFilesOnly" to "workspace", that will tell pylance to perform type analysis on all of the files in the project rather than just the open files. You should then be able to look at the Output tab and get a sense for which file was being type checked at the time of the stack overflow. If you're able to do that, I can provide additional instructions for how to further localize the code within that file.

**Comment by AlteriusOmega** [comment]
> 

I edited my workspace settings.json file adding `"python.analysis.diagnosticMode": "workspace"` but I still don't see anything in the OUTPUT tab when I try to use Rename Symbol. I also tried changing diagnosticMode in my global settings.json file, but still there is no output in the OUTPUT tab.

https://user-images.githubusercontent.com/44767171/163853168-11138a6e-84fe-4e93-9f42-1416c9fd45bd.mp4

**Comment by AlteriusOmega** [comment]
Solution: I believe this issue is caused by conflicts with variables of the same name. 

This is code I was handed, and I've found that there are many variables that share the exact same name as a function (horrible, I know). I found that these are the ones that exhibit the call stack error. After renaming the variables to be different from the function name, VSCode will continue giving the rename error until it it restarted. After restarting VSCode, however, the variables (which no longer conflict with other function names) can be renamed using F2 as normal. I am closing this ticket now.

**Comment by AlteriusOmega** [comment]
Update 2: After renaming all variables that had name conflicts, and renaming all global variables, I am no longer getting the call stack error when renaming any variables. I am closing this ticket.

**Comment by debonte** [comment]
Reopening. Although @AlteriusOmega has changed his code an unblocked himself, it sounds like there is still an issue here than could impact other users.

@AlteriusOmega, could you provide a code snippet that shows the kind of code that was causing this problem for you?

**Comment by debonte** [comment]
@AlteriusOmega, can you explain to us how to reproduce this issue? We believe it is impacting other users and we'd love to fix it!

**Comment by AlteriusOmega** [comment]
> 

Sure, here is how to reproduce it.
1. Install VSCode and Python extensions
2. Write program that uses the same name for a variable as a function and uses that variable as a global inside the function
3. Try to use Rename Symbol (F2) on the variable

See the below code which causes the call stack error for me:

`varname = 26
def varname():
    global varname
    varname = 27
    print(f'varname is {varname} ')
varname()`

**Comment by erictraut** [comment]
Thanks @AlteriusOmega. I was expecting some really complex set of repro steps, but I'm able to confirm that I was able to repro the bug with your simple example!

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by debonte** [comment]
This issue has been fixed in version 2022.6.10, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022610-8-June-2022)

**Comment by smackesey** [comment]
I still encounter this error. To repro, try renaming `repository_location` under `WorkspaceLocationEntry` here:

https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/workspace/workspace.py

**Comment by erictraut** [comment]
@smackesey, please open a new bug report and supply the requested logs. I tried to repro your problem, but rename works fine for me. There must be something specific about your setup or configuration, so the logs will be important.

**Comment by LifeJustDLC** [comment]
try this:

```python
import os

for name in next(os.walk("dir1"))[1]:
    print(name) # try rename symbol `name` to anything else, get stack overflow

for name in next(os.walk("dir2"))[1]:
    print(name)

```
I'm not quite familiar with python. Is there a reserved keyword called `name` in python?
