### ISSUE TITLE
Pylance Missing Imports Django Rest Framework.

### ISSUE THREAD

**Issue by Deadlooks** [microsoft/pylance-release#2554]
<h3> Environment data </h3>

-   Language Server version: 2022.4.0
-   OS and version: linux arm64
-   Python version (Python 3.9.9): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

Accept the Django Rest Framework 

<h3> Actual behaviour </h3>

Import "rest_framework.response" could not be resolved Pylance

Import "rest_framework.views" could not be resolved Pylance

<h3> Logs </h3>

Python Language Server Log
```
No Errors Rest Framework is working perfectly as it should work, It's just Pylance the is not recognizing
```

<h3> Code Snippet / Additional information </h3>

```python
from rest_framework.response import Response
from rest_framework.views import APIView
```

**Comment by Deadlooks** [comment]
It is solved
![final](https://user-images.githubusercontent.com/91751103/162631209-3dd650d7-494d-445d-86fe-7e447874615c.png)

**Comment by alifirhas** [comment]
@Deadlooks 

What exactly do you mean by **project file**, is it the app folder or the overall Django project directory?

I still get this error even though my env is already in my project directory.

**Comment by Deadlooks** [comment]
@alifirhas 

**Explanation:**

Django <<- it the folder where i stored the venv folder and the project folder which is creaded using django-admin startproject <folder name> 
So i moved the venv folder in the project folder look in images example

![gitimp](https://user-images.githubusercontent.com/91751103/189917166-801e3458-8267-4866-8545-8134115c73ee.png)


myproject is created using django-admin startproject myproject
