### ISSUE TITLE
Error: command 'pyright.createtypestub' already exists

### ISSUE THREAD

**Issue by shaunm-msft** [microsoft/pylance-release#2765]
[Info  - 7:56:43 AM] (46164) Pylance language server 2022.4.4-pre.1 (pyright 88f2a424) starting
[Info  - 7:56:43 AM] (46164) Server root directory: c:\Users\shaunm\.vscode-insiders\extensions\ms-python.vscode-pylance-2022.4.4-pre.1\dist
[Error - 7:56:43 AM] Server initialization failed.
Error: command 'pyright.createtypestub' already exists
	at o.registerCommand (c:\Users\shaunm\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:29716)
	at Object.registerCommand (c:\Users\shaunm\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:30972)
	at t.ExecuteCommandFeature.register (c:\Users\shaunm\.vscode-insiders\extensions\ms-python.python-2022.5.11231003\out\client\extension.js:2:2220058)
	at t.ExecuteCommandFeature.initialize (c:\Users\shaunm\.vscode-insiders\extensions\ms-python.python-2022.5.11231003\out\client\extension.js:2:2219637)
	at S.initializeFeatures (c:\Users\shaunm\.vscode-insiders\extensions\ms-python.python-2022.5.11231003\out\client\extension.js:2:2172202)
	at S.doInitialize (c:\Users\shaunm\.vscode-insiders\extensions\ms-python.python-2022.5.11231003\out\client\extension.js:2:2160126)
	at async S.start (c:\Users\shaunm\.vscode-insiders\extensions\ms-python.python-2022.5.11231003\out\client\extension.js:2:2157141)
	at async f.start (c:\Users\shaunm\.vscode-insiders\extensions\ms-python.python-2022.5.11231003\out\client\extension.js:2:34030)
[Error - 7:56:43 AM] Python Tools client: couldn't create connection to server.

**Comment by judej** [comment]
Thanks for the report. This can happen if Pyright and Pylance extensions are both installed. Is this the case for you? If so, could you please uninstall one of them?

**Comment by debonte** [comment]
> I have the Pylance extension installed but not the Pyright extension.

Wow, ok. Can you send us a list of the extensions you have installed? You can dump the list of extensions on the command line using `code --list-extensions`

**Comment by shaunm-msft** [comment]
E:\>code-insiders --list-extensions
ms-dotnettools.vscode-dotnet-runtime
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode-remote.remote-wsl
ms-vscode.cpptools
ms-vscode.powershell-preview
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode-completions
VisualStudioExptTeam.vscodeintellicode-insiders

**Comment by Finerestaurant** [comment]
I also head same probelm after changing to conda virtual environment. Here's my extension lists

`(base) C:\Users\user>code --list-extensions
cschlosser.doxdocgen
Equinusocio.vsc-community-material-theme
Equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons
jeff-hykin.better-cpp-syntax
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
oderwat.indent-rainbow
twxs.cmake`

**Comment by arsenie-ciobanu-cko** [comment]
Same thing here - just installed VS Code and getting this error:

```
[Error - 3:47:25 PM] Pylance client: couldn't create connection to server.
Error: command 'pyright.createtypestub' already exists
```

Version: `Pylance language server 2022.4.3 (pyright 88f2a424)`

here's my extensions list:

```
user@xxx ~ % code --list-extensions
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
```

**Comment by 55octet** [comment]
Same issue:
```
code --list-extensions
eamodio.gitlens
michelemelluso.gitignore    
ms-python.python
ms-python.vscode-pylance    
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap   
ms-toolsai.jupyter-renderers
```

**Comment by thomas-oconnell** [comment]
Reverting to Python extension version 2022.4.1 from 2022.6.0 resolved this issue for me, though your mileage may very. I did not touch the Pylance extension version.

With version 2022.6.0, the issue wouldn't appear as long as I had a project folder open and contained my work in that regard.

With version 2022.4.1, the issue was gone, regardless of my current working status.

**Comment by netcore-jroger** [comment]
> Reverting to Python extension version 2022.4.1 from 2022.6.0 resolved this issue for me, though your mileage may very. I did not touch the Pylance extension version.
> 
> With version 2022.6.0, the issue wouldn't appear as long as I had a project folder open and contained my work in that regard.
> 
> With version 2022.4.1, the issue was gone, regardless of my current working status.

how to download 2022.4.1 version.

**Comment by thomas-oconnell** [comment]
> > Reverting to Python extension version 2022.4.1 from 2022.6.0 resolved this issue for me, though your mileage may very. I did not touch the Pylance extension version.
> > With version 2022.6.0, the issue wouldn't appear as long as I had a project folder open and contained my work in that regard.
> > With version 2022.4.1, the issue was gone, regardless of my current working status.
> 
> how to download 2022.4.1 version.

Click on the extension within VS Code, click the arrow next to Uninstall, then "Install Another Version..."

**Comment by Angshuman-Maity** [comment]
I was also facing the same issue. Reverting back to Python extension version 2022.4.1 from 2022.6.0 resolved this issue for me. Thank you

**Comment by erictraut** [comment]
Thanks for the update. Based on these clues, this looks like it's probably a regression in the core Python extension. I wonder if the Python extension is unloading and then reloading Pylance but doing so in a way that the command 'pyright.createtypestub' isn't unregistered upon unload.

**Comment by BobDenny** [comment]
Same here, reverted to 2022.4.1 cured it also. Thanks to you @thomas-oconnell

**Comment by trinatek** [comment]
Samesies:

`code --list-extensions
akamud.vscode-theme-onedark
almenon.arepl
arcsector.vscode-splunk-search-linter
arcsector.vscode-splunk-search-syntax
cantonios.project-templates
DotJoshJohnson.xml
emilast.LogFileHighlighter
formulahendry.auto-rename-tag
KevinRose.vsc-python-indent
mgesbert.python-path
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode-remote.remote-wsl
ms-vscode.powershell
PKief.material-icon-theme
PrateekMahendrakar.prettyxml
richie5um2.vscode-sort-json
ryuta46.multi-command
seanwu.vscode-qt-for-python
Splunk.splunk
stkb.rewrap
vscodevim.vim
zhuangtongfa.material-theme
Zignd.html-css-class-completion`

**Comment by shendin-chrobinson** [comment]
I have experienced the same today, and downgrading the core Python extension to v2022.4.1 fixed it for me.

**Comment by zachsiegel-capsida** [comment]
Same issue, reverting Python core version solved it for me too.

**Comment by BobDenny** [comment]
I just updated to the 2022.7.11291008 Pre-Release version and the problem is also gone.

**Comment by progrunman** [comment]
I'm also v2022.6.0 and the problem occurred after moving the source folder of the existing project. The problem went away when I restarted VSCode after a few minutes. However, the warning below is still occurring.

[Warn] (14348) stubPath 'my project folder path'\typings is not a valid directory.

The 'typings' folder was not created by me and does not exist in the my source folder. So, I don't know what that is.

**Comment by Kein** [comment]
Same issue.
I have 3 versions of Python installed, 3.9.6, 3.10 and 3.8.5 but only switching to 3.8.5 causes this issue.

**Comment by edwardchoijc** [comment]
Same issue. My full log is below.
> [Info  - 11:30:50 AM] (78228) Pylance language server 2022.4.3 (pyright 88f2a424) starting
> [Info  - 11:30:50 AM] (78228) Server root directory: /HOME_PATH/.vscode/extensions/ms-python.vscode-pylance-2022.4.3/dist
> [Warn  - 11:30:50 AM] (78228) stubPath /MY_PROJECT_PATH/typings is not a valid directory.
> [Info  - 11:31:08 AM] (78246) Pylance language server 2022.4.3 (pyright 88f2a424) starting
> [Info  - 11:31:08 AM] (78246) Server root directory: /HOME_PATH/.vscode/extensions/ms-python.vscode-pylance-2022.4.3/dist
> [Error - 11:31:08 AM] Server initialization failed.
> Error: command 'pyright.createtypestub' already exists
>     at o.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:29716)
>     at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:30972)
>     at t.ExecuteCommandFeature.register (/HOME_PATH/.vscode/extensions/ms-python.python-2022.6.1/out/client/extension.js:2:2221856)
>     at t.ExecuteCommandFeature.initialize (/HOME_PATH/.vscode/extensions/ms-python.python-2022.6.1/out/client/extension.js:2:2221435)
>     at S.initializeFeatures (/HOME_PATH/.vscode/extensions/ms-python.python-2022.6.1/out/client/extension.js:2:2174000)
>     at S.doInitialize (/HOME_PATH/.vscode/extensions/ms-python.python-2022.6.1/out/client/extension.js:2:2161924)
>     at async S.start (/HOME_PATH/.vscode/extensions/ms-python.python-2022.6.1/out/client/extension.js:2:2158939)
>     at async S.$start (/HOME_PATH/.vscode/extensions/ms-python.python-2022.6.1/out/client/extension.js:2:2165739)
>     at async t.Delayer.<anonymous> (/HOME_PATH/.vscode/extensions/ms-python.python-2022.6.1/out/client/extension.js:2:2164010)
> [Error - 11:31:08 AM] Pylance client: couldn't create connection to server.


Extensions:

> code --list-extensions
> 2gua.rainbow-brackets
> aaron-bond.better-comments
> alefragnani.project-manager
> DotJoshJohnson.xml
> eamodio.gitlens
> Equinusocio.vsc-community-material-theme
> Equinusocio.vsc-material-theme
> equinusocio.vsc-material-theme-icons
> GrapeCity.gc-excelviewer
> KevinRose.vsc-python-indent
> Lencerf.beancount
> mhutchie.git-graph
> MS-CEINTL.vscode-language-pack-zh-hans
> ms-python.python
> ms-python.vscode-pylance
> ms-toolsai.jupyter
> ms-toolsai.jupyter-keymap
> ms-toolsai.jupyter-renderers
> ms-vscode-remote.remote-wsl
> njpwerner.autodocstring
> Shan.code-settings-sync
> Tyriar.sort-lines
> vscode-icons-team.vscode-icons

**Comment by daydaychen** [comment]
I switch to Python extension pre-release v2022.7.11311004, all of ok.

**Comment by Gakubuchi** [comment]
I have the same issue (and also some of my students).
The list of extensions I have is:
```
C:\Users\xxxxxx>code --list-extensions
alexcvzz.vscode-sqlite
cschlosser.doxdocgen
enriquein.htmlentity-replacer
jeff-hykin.better-cpp-syntax
mborik.z80-macroasm
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-wsl
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
sharksym.asm-msx
tht13.html-preview-vscode
twxs.cmake
```
I haven't tried to revert to an older version of Python extension.
I hope it is useful
![Captura de pantalla 2022-05-12 113800](https://user-images.githubusercontent.com/7223004/168042639-1512f3b9-e379-4d05-b91d-a04fc21d1ab3.png)
.

**Comment by longguzzz** [comment]
I have this problem after I set my defaultProfile with my self-configure commandline.

![image](https://user-images.githubusercontent.com/96779663/168320722-e07c8b8e-70f4-4b6c-b0df-d94b729e0b11.png)

And I solve this problem by setting the terminal with the default one. (PowerShell)

![image](https://user-images.githubusercontent.com/96779663/168320868-1c224d7a-7f72-4d2b-b38b-88a7e7ea3bd3.png)

**Comment by monkeycc** [comment]
vscode 1.67.1

```
[Info  - 16:06:07] (8668) Pylance language server 2022.5.1 (pyright e0e07d31) starting
[Info  - 16:06:07] (8668) Server root directory: c:\Users\MM\.vscode\extensions\ms-python.vscode-pylance-2022.5.1\dist
[Error - 16:06:07] Server initialization failed.
Error: command 'pyright.createtypestub' already exists
	at o.registerCommand (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:29716)
	at Object.registerCommand (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:30972)
	at t.ExecuteCommandFeature.register (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2225181)
	at t.ExecuteCommandFeature.initialize (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2224760)
	at S.initializeFeatures (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2176688)
	at S.doInitialize (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2164589)
	at async S.start (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2161604)
	at async h.start (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:33669)
[Error - 16:06:07] Pylance client: couldn't create connection to server.
Error: command 'pyright.createtypestub' already exists
	at o.registerCommand (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:29716)
	at Object.registerCommand (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:30972)
	at t.ExecuteCommandFeature.register (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2225181)
	at t.ExecuteCommandFeature.initialize (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2224760)
	at S.initializeFeatures (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2176688)
	at S.doInitialize (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2164589)
	at async S.start (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2161604)
	at async h.start (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:33669)
[Error - 16:06:07] Sending notification textDocument/didOpen failed.
Error: command 'pyright.createtypestub' already exists
	at o.registerCommand (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:29716)
	at Object.registerCommand (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:30972)
	at t.ExecuteCommandFeature.register (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2225181)
	at t.ExecuteCommandFeature.initialize (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2224760)
	at S.initializeFeatures (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2176688)
	at S.doInitialize (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2164589)
	at async S.start (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:2161604)
	at async h.start (c:\Users\MM\.vscode\extensions\ms-python.python-2022.6.2\out\client\extension.js:2:33669)
[Error - 16:06:07] Sending notification textDocument/didOpen failed.
Error: command 'pyright.createtypestub' already exists
```

**Comment by citron** [comment]
Same problem here after a fresh installation of vscode and a sync with my other vscode configurations.

**Comment by fritol** [comment]
same here. removed all extensions. reinst VS code.  Still the same problem. In addition cannot run python files in the terminal only notebook exec works! wtf!

**Comment by strobelight** [comment]
I also received same error when using OSX ssh to debug remotely, but noticed a reload was required of python, so did that, and the error went away. 

python v2022.6.2
pylance v2022.5.1

**Comment by TaridaGeorge** [comment]
For me, I think that this error started to occur after I installed pyright by mistake without knowing that pylance has it already in it and after I've uninstalled the pyright extension I started to notice this error.

**Comment by netcore-jroger** [comment]
### DO NOT INSTALL THIS.
![图片](https://user-images.githubusercontent.com/3223890/169217328-82834366-1210-47bc-a3a4-d54bd84cddac.png)

### INSTALL THIS:
![图片](https://user-images.githubusercontent.com/3223890/169217438-e24b821c-49eb-4770-9600-7eaf33ecc1af.png)

**Comment by omidshojaee** [comment]
Had this issue and solved it by reverting to 2022.7.11381657

**Comment by chausner-audeering** [comment]
> I switch to Python extension pre-release v2022.7.11311004, all of ok.

I think I started to run into this issue after the vscode update today from 1.67.1 to 1.67.2. Installing the pre-release version of the Python extension also fixed it for me.

**Comment by joootdooot** [comment]
> Had this issue and solved it by reverting to 2022.7.11381657 and then installing the latest pre-release (2022.7.11381925) again.

This worked for me, thank you so much 😄

**Comment by khurchla** [comment]
I had this error but it went away after I did the following then restarted VSCode.
(possibly a restart of VSCode alone would have done it)
- Shell Command: Uninstall 'code' command from PATH
- Shell Command: Install 'code' command from PATH

this is what I had installed when it first occurred:
- VS code 1.67.7 MacOS Universal
- Miniconda3 macOS Apple M1 64-bit bash
- extensions:
ecmel.vscode-html-css
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers

**Comment by Elypha** [comment]
for my case, I have to revert Python to v2022.4.1 and Pylance to v2022.4.3 as well

**Comment by zptang1210** [comment]
I am also experiencing this problem on both my Windows and MacOS computers.

**Comment by ingmarschuster** [comment]
For me also: Reverting to Python extension version 2022.4.1 resolved the problem

**Comment by dziyaee** [comment]
Same issue here, completely fresh install of vscode. Only happens the first time when I try to switch the Python interpreter to different conda envs.

```sh
$ code --list-extensions --show-versions
ms-python.python@2022.6.2
ms-python.vscode-pylance@2022.5.3
ms-toolsai.jupyter@2022.4.1021342353
ms-toolsai.jupyter-keymap@1.0.0
ms-toolsai.jupyter-renderers@1.0.7
ms-vscode.Theme-PredawnKit@0.1.4
```

Also getting a whole bunch of errors in the output
```
[Info  - 11:11:18 PM] (70156) Pylance language server 2022.5.3 (pyright 73c82fab) starting
[Info  - 11:11:18 PM] (70156) Server root directory: /Users/foo/.vscode/extensions/ms-python.vscode-pylance-2022.5.3/dist
Notebook support: Legacy
[Info  - 11:11:18 PM] (70156) No pyproject.toml file found.
[Info  - 11:11:18 PM] (70156) Setting pythonPath for service "<default>": "/usr/local/bin/python3"
[Warn  - 11:11:18 PM] (70156) stubPath typings is not a valid directory.
[Info  - 11:11:18 PM] (70156) Assuming Python version 3.8
[Info  - 11:11:18 PM] (70156) Assuming Python platform Darwin
[Info  - 11:11:19 PM] (70156) Searching for source files
[Info  - 11:11:19 PM] (70156) No source files found.
[Info  - 11:11:19 PM] (70156) No pyproject.toml file found.
[Info  - 11:11:19 PM] (70156) Setting pythonPath for service "<default>": "/usr/local/bin/python3"
[Warn  - 11:11:19 PM] (70156) stubPath typings is not a valid directory.
[Info  - 11:11:19 PM] (70156) Assuming Python version 3.8
[Info  - 11:11:19 PM] (70156) Assuming Python platform Darwin
[Info  - 11:11:19 PM] (70156) Searching for source files
[Info  - 11:11:19 PM] (70156) No source files found.
[Info  - 11:11:20 PM] (70156) Background analysis(1) root directory: /Users/foo/.vscode/extensions/ms-python.vscode-pylance-2022.5.3/dist
[Info  - 11:11:20 PM] (70156) Background analysis(1) started
[Error - 11:12:24 PM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 11:12:25 PM] (70235) Pylance language server 2022.5.3 (pyright 73c82fab) starting
[Info  - 11:12:25 PM] (70235) Server root directory: /Users/foo/.vscode/extensions/ms-python.vscode-pylance-2022.5.3/dist
[Info  - 11:12:25 PM] (70236) Pylance language server 2022.5.3 (pyright 73c82fab) starting
[Info  - 11:12:25 PM] (70236) Server root directory: /Users/foo/.vscode/extensions/ms-python.vscode-pylance-2022.5.3/dist
Notebook support: Legacy
Notebook support: Legacy
[Error - 11:12:25 PM] Server initialization failed.
Error: command 'pyright.createtypestub' already exists
	at o.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:29716)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:30972)
	at t.ExecuteCommandFeature.register (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2225181)
	at t.ExecuteCommandFeature.initialize (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2224760)
	at S.initializeFeatures (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2176688)
	at S.doInitialize (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2164589)
	at async S.start (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2161604)
	at async h.start (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:33669)
[Error - 11:12:25 PM] Pylance client: couldn't create connection to server.
Error: command 'pyright.createtypestub' already exists
	at o.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:29716)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:30972)
	at t.ExecuteCommandFeature.register (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2225181)
	at t.ExecuteCommandFeature.initialize (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2224760)
	at S.initializeFeatures (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2176688)
	at S.doInitialize (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2164589)
	at async S.start (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2161604)
	at async h.start (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:33669)
[Error - 11:12:25 PM] Sending notification textDocument/didOpen failed.
Error: command 'pyright.createtypestub' already exists
	at o.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:29716)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:30972)
	at t.ExecuteCommandFeature.register (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2225181)
	at t.ExecuteCommandFeature.initialize (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2224760)
	at S.initializeFeatures (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2176688)
	at S.doInitialize (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2164589)
	at async S.start (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2161604)
	at async h.start (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:33669)
[Error - 11:12:25 PM] Sending document notification textDocument/didOpen failed
Error: command 'pyright.createtypestub' already exists
	at o.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:29716)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:30972)
	at t.ExecuteCommandFeature.register (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2225181)
	at t.ExecuteCommandFeature.initialize (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2224760)
	at S.initializeFeatures (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2176688)
	at S.doInitialize (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2164589)
	at async S.start (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2161604)
	at async h.start (/Users/foo/.vscode/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:33669)
[Info  - 11:12:26 PM] (70235) No pyproject.toml file found.
[Info  - 11:12:26 PM] (70235) Setting pythonPath for service "<default>": "/Users/foo/miniconda3/envs/prime/bin/python"
[Warn  - 11:12:26 PM] (70235) stubPath typings is not a valid directory.
[Info  - 11:12:26 PM] (70235) Assuming Python version 3.10
[Info  - 11:12:26 PM] (70235) Assuming Python platform Darwin
[Info  - 11:12:26 PM] (70235) Searching for source files
[Info  - 11:12:26 PM] (70235) No source files found.
[Info  - 11:12:27 PM] (70235) Background analysis(1) root directory: /Users/foo/.vscode/extensions/ms-python.vscode-pylance-2022.5.3/dist
[Info  - 11:12:27 PM] (70235) Background analysis(1) started
[Info  - 11:12:27 PM] (70235) No pyproject.toml file found.
[Info  - 11:12:27 PM] (70235) Setting pythonPath for service "<default>": "/Users/foo/miniconda3/envs/prime/bin/python"
[Warn  - 11:12:27 PM] (70235) stubPath typings is not a valid directory.
[Info  - 11:12:27 PM] (70235) Assuming Python version 3.10
[Info  - 11:12:27 PM] (70235) Assuming Python platform Darwin
[Info  - 11:12:27 PM] (70235) Searching for source files
[Info  - 11:12:27 PM] (70235) No source files found.
```

I can confirm that downgrading to `ms-python.python@2022.4.1` fixed it.

**Comment by spectatorzhang** [comment]
- Same problem with me here, totally new installed latest VSCode and latest stable extensions.

- Happens when opening every .py file:

![image](https://user-images.githubusercontent.com/79626332/170855631-7eb307d9-3451-40ea-9ca3-1423c0063944.png)

- Known solution: downgrade Python extension (not Pylance) to 2022.4.X version would fix it.

- I only installed Python, Pylance and Jupyter in VSCode, so the problem has nothing to do with other extensions.

**Comment by fritol** [comment]
same old same old 
![image](https://user-images.githubusercontent.com/4304520/171023634-a1450e2a-f8f4-4a3e-bf27-a799681dedbb.png)

**Comment by spectatorzhang** [comment]
seems like this issue has been solved after Python extension releases 2022.6.3 upgrade.
![image](https://user-images.githubusercontent.com/79626332/171828359-54a5e7e1-6041-4d34-b6c5-d68638a38773.png)

**Comment by meflouu** [comment]
At least for me, the issue persists. In fact, I just got here after updating to 2022.6.3

> Seems like this issue has been solved after Python extension releases 2022.6.3 upgrade. ![image](https://user-images.githubusercontent.com/79626332/171828359-54a5e7e1-6041-4d34-b6c5-d68638a38773.png)

**Comment by debonte** [comment]
Yes, it's still happening in the latest build of the Python extension. We're actively looking at this.

**Comment by spectatorzhang** [comment]
So the problem may be with Python extension, not Pylance itself.
> Yes, it's still happening in the latest build of the Python extension. We're actively looking at this.

**Comment by debonte** [comment]
> The problem may be with Python extension, not Pylance itself.

Yes, it's an issue with the way that Python is managing the LSP connection with Pylance. But the Pylance team is driving the investigation, so it makes sense for the issue to stay on our issue tracker.

**Comment by lind-ric** [comment]
Hoping this gets resolved soon! best of luck to the mega minds working on this!!

**Comment by heejaechang** [comment]
this will be fixed in python extension once new version is released.

**Comment by babrar** [comment]
This issue still persists in version **2022.8.1** -> latest release version as of Jul 5, 2022

I can confirm that downgrading to ms-python.python@**2022.4.1** fixed it.

**Comment by jibzus** [comment]
> > > Reverting to Python extension version 2022.4.1 from 2022.6.0 resolved this issue for me, though your mileage may very. I did not touch the Pylance extension version.
> > > With version 2022.6.0, the issue wouldn't appear as long as I had a project folder open and contained my work in that regard.
> > > With version 2022.4.1, the issue was gone, regardless of my current working status.
> > 
> > 
> > how to download 2022.4.1 version.
> 
> Click on the extension within VS Code, click the arrow next to Uninstall, then "Install Another Version..."

This seemed to work for me

**Comment by mrinmayik** [comment]
> > > Reverting to Python extension version 2022.4.1 from 2022.6.0 resolved this issue for me, though your mileage may very. I did not touch the Pylance extension version.
> > > With version 2022.6.0, the issue wouldn't appear as long as I had a project folder open and contained my work in that regard.
> > > With version 2022.4.1, the issue was gone, regardless of my current working status.
> > 
> > 
> > how to download 2022.4.1 version.
> 
> Click on the extension within VS Code, click the arrow next to Uninstall, then "Install Another Version..."

Worked for me too. Thanks for the solution @thomas-oconnell !!

**Comment by prerna08** [comment]
The issue persists on 2022.7.40 VSC Version: 1.69.2 2022.7.40

Reverting to 2022.4.1 resolved it for me.

**Comment by astro313** [comment]
Reverting to 2022.4.1 resolved it for me.

**Comment by berkaycagir** [comment]
Why was this issue closed? This is still happening, also had to revert to 2022.4.1.

**Comment by omidshojaee** [comment]
Apparently as soon as a user discovers a workaround they close the issues.

**Comment by jweyrich** [comment]
> this will be fixed in python extension once new version is released.

ms-python.python has a released 2022.10.0 3 weeks ago, and 2022.10.1 2 weeks ago, but the issue still happens. Not sure what exacly to do - maybe just downgrade pylance temporarily?

**Comment by fasapa** [comment]
It's still happening with version v2022.12.1. Brand new vscode installation. Reverting to v2022.4.1 solved it.

**Comment by sammyyap98** [comment]
I still got the same error after trying with Pylance v2022.08.30 and Python v2022.04.01

Is there any other possible solution.

**Comment by debonte** [comment]
@heejaechang, while waiting for this to get fixed properly, would it make sense for Pylance to skip registering the command if it's already registered? Rich suggested this in scrum today.

**Comment by Yura52** [comment]
I have the same issue with Python==v2022.12.1 and Pylance==v2022.8.40. More details:

- the working folder is located on a remote machine, i.e. VSCode connects to it via SSH
- I have two laptops and I am migrating from the old one to the new one
- on the old one, it all works fine, Pylance is operating on the remote working directory without issues
- on the new one, this problem occurs

**Comment by heejaechang** [comment]
@debonte, it is not just that command, it fails on that because that is the first command we register. we need to skip registering all commands and that will make none of our command to work.

**Comment by heejaechang** [comment]
@Yura52 is it repro consistently? if so, can you provide more detail repro steps so we can try as well?

@babrar  @jibzus  @mrinmayik  @locture @prerna08  @astro313 @berkaycagir @jweyrich @sammyyap98 @fasapa if this happen consistently, can you provide a repro step we can follow? currently, we fixed ones we know, but it looks like there are more ways to make it happen.

@midshojaee it is closed since we fixed ones that are reported. now, we found out there are multiple ways to make this exception to throw. so far, we fixed 4 different issues, but it looks like there are even more cases. it would be very helpful if you can provide repro steps if it consistently happening so we can take a look.

we thank you for the reporting, but it would be even more helpful if you can provide us detail repro steps we can follow to repro the issues.

**Comment by heejaechang** [comment]
related issue on python repo that can help us investigate the issue - https://github.com/microsoft/vscode-python/issues/19626

**Comment by debonte** [comment]
@heejaechang, I found a scenario that repros this error consistently:

Python: v2022.17.12791010
Pylance: v2022.10.11
Pyright: v1.1.274

1. Open a Python file or notebook. 
2. Disable Pylance; enable Pyright
3. "Developer: Reload Window" via the command palette
4. Wait for Pyright to initialize. I was testing this by seeing that hover worked.
5. Disable Pyright; Enable Pylance

Result: Pylance fails with "Error: command 'pyright.createtypestub' already exists"

**Comment by shaunm-msft** [comment]
I have Pylance (v2022.4.4-pre.1) installed but not Pyright.

**Comment by debonte** [comment]
> I have Pylance (v2022.4.4-pre.1) installed but not Pyright.

@shaunm-msft, ok, yes, we've found some ways that this can happen with just Pylance installed as well.

Although this issue persists, some of the scenarios that cause it have been fixed. 2022.4.4-pre.1 is very old. Are you also running an old version of the Python extension? If so, you may find that upgrading the Python extension in particular improves the situation.

**Comment by shaunm-msft** [comment]
@debonte,
I am using Pylance v2022.10.10 now. I upgrade code-insiders and all extensions regularly. 

I haven't encountered this issue that I reported in a long time. I think that last post from me was stuck in GitHub's email processing for a really long time. I haven't commented on this issue since May.

**Comment by phrmoy** [comment]
Running on v2023.3.10371010, also encountered the issue.

alefragnani.Bookmarks
arrterian.nix-env-selector
baccata.scaladex-search
betterthantomorrow.calva
bmalehorn.shell-syntax
borkdude.clj-kondo
charliermarsh.ruff
christian-kohler.path-intellisense
DavidAnson.vscode-markdownlint
docsmsft.docs-yaml
dustypomerleau.rust-syntax
EditorConfig.EditorConfig
edonet.vscode-command-runner
emeraldwalk.RunOnSave
fnando.linter
formulahendry.auto-close-tag
formulahendry.code-runner
foxundermoon.shell-format
george3447.docker-run
Gruntfuggly.todo-tree
haskell.haskell
hoovercj.haskell-linter
humao.rest-client
ionutvmi.path-autocomplete
jakob101.RelativePath
jnoortheen.nix-ide
justusadam.language-haskell
KevinRose.vsc-python-indent
mads-hartmann.bash-ide-vscode
matangover.mypy
mechatroner.rainbow-csv
mkhl.shfmt
ms-azuretools.vscode-docker
ms-python.autopep8
ms-python.black-formatter
ms-python.flake8
ms-python.pylint
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.remote-explorer
njpwerner.autodocstring
PascalReitermann93.vscode-yaml-sort
patbenatar.advanced-new-file
pinage404.nix-extension-pack
quicktype.quicktype
rangav.vscode-thunder-client
redhat.vscode-yaml
richie5um2.vscode-sort-json
rioj7.command-variable
rust-lang.rust-analyzer
ryuta46.multi-command
scala-lang.scala
scalameta.metals
shd101wyy.markdown-preview-enhanced
SonarSource.sonarlint-vscode
stoplight.spectral
timonwong.shellcheck
truman.autocomplate-shell
trunk.io
Tyriar.sort-lines
usernamehw.errorlens
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
vscodevim.vim
wayou.vscode-todo-highlight
ypresto.vscode-intelli-refactor
yzane.markdown-pdf
yzhang.markdown-all-in-one
ZainChen.json
zxh404.vscode-proto3

**Comment by heejaechang** [comment]
we are planning to fix the issue by changing how pylance is created from python extension. but it requires major refactoring which will take some time to finish.

**Comment by heejaechang** [comment]
@alexisart the fix is being tested using A/B test. you can try setting this hidden option `python.analysis.pylanceLspClientEnabled` and see whether it still repro. make sure to use latest `prerelease`.

**Comment by 2victor2** [comment]
> @alexisart the fix is being tested using A/B test. you can try setting this hidden option `python.analysis.pylanceLspClientEnabled` and see whether it still repro. make sure to use latest `prerelease`.

I'm in similar scenario as @alexisart and after setting `python.analysis.pylanceLspClientEnabled` and changing Python extension to pre-release as recommended it worked.

**Comment by CarlGao4** [comment]
Mine is not working. 
```
> code -v
1.77.3
704ed70d4fd1c6bd6342c436f1ede30d1cff4710
x64
> code --list-extensions --show-versions
MS-CEINTL.vscode-language-pack-zh-hans@1.77.2023040509
ms-python.python@2023.6.0
ms-python.vscode-pylance@2023.4.30
```

**Comment by heejaechang** [comment]
@CarlGao4 after setting `python.analysis.pylanceLspClientEnabled`? if so, can you give us repro steps?

**Comment by CarlGao4** [comment]
> @CarlGao4 after setting `python.analysis.pylanceLspClientEnabled`? if so, can you give us repro steps?

I realized that only some of the times when I start VSCode will encounter this, both using version 2023.6.0 and 2023.6.1
But only the first time I opened VSCode after setting `python.analysis.pylanceLspClientEnabled` got the error. Then it is ok.

**Comment by heejaechang** [comment]
@CarlGao4 when you said `opened VSCode after setting the option`, you meant `close` and `open` vscode? or `window reload`? or  something else?

**Comment by CarlGao4** [comment]
Close and open it. I haven't encounter this issue since I upgraded to the pre-release and set `python.analysis.pylanceLspClientEnabled`

**Comment by zzzeek** [comment]
hi there -

in the past two weeks ive begun to get this issue constantly, I've been over in #4318 and it appears my issue was mis-diagnosed.   It looks like this is an ongoing issue.  Will try turning on `python.analysis.pylanceLspClientEnabled`.

**Comment by rchiodo** [comment]
`python.analysis.pylanceLspClientEnabled` requires prerelease versions of Python and Pylance extension.

**Comment by zzzeek** [comment]
yup so far so good will keep you posted

**Comment by StijnvanderLippe** [comment]
The issue still occurs for me, but not always. Sometimes it happens on initial startup (after booting my laptop), or when closing VS Code and reopening the window. I am using the prerelease version of both the Python and Pylance extension, and the option "Python › Analysis: Pylance Lsp Client Enabled" is ticked on.

**Comment by zzzeek** [comment]
ive seen no failures at all since applying the new parameter.

**Comment by heejaechang** [comment]
@StijnvanderLippe are you using the latest version of python/pylance extension?

**Comment by StijnvanderLippe** [comment]
@heejaechang I am using Pylance pre-release v2023.5.21 and Python pre-release v2023.9.11361009. 

By the way: I opened VS Code to check the version numbers. First start up: no issue. Just to check, I close VS Code (simply by clicking the x in the top right corner of the window) and re-open and I get the error messages. Subsequently closing and reopening VS Code brings up the error messages every time.

**Comment by heejaechang** [comment]
@StijnvanderLippe Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

I want to check that new client is actually enabled for us.

**Comment by StijnvanderLippe** [comment]
I am using a virtual environment with Python 3.10.11.

Note that this is not the full log, because the output seemed to include the whole source code for vendor.bundle.js to indicate where an error occurred. But it didn't have any formatting, so it was just thousands of lines of code. 

[log.txt](https://github.com/microsoft/pylance-release/files/11491727/log.txt)

**Comment by heejaechang** [comment]
thank you! let me take a look!

**Comment by heejaechang** [comment]
one more question, the folder/workspace you are using? is it trusted workspace or untrusted workspace?

**Comment by StijnvanderLippe** [comment]
It is a trusted workspace.

Also, when I went to open VS Code to check this, I got no error messages. I did not reboot my machine in the mean time. When I reopened shortly after, I get the error messages again.

**Comment by heejaechang** [comment]
can I ask you one more question, if you give it a little bit of time say 15 seconds once you closed the `vscode` before you reopen `vscode` does it still happen? trying to figure out whether there is a race between `shutting down` server and restarting a server

**Comment by StijnvanderLippe** [comment]
Bad news, when I started up VS Code for the first time after booting my machine, the error messages popped up as well. So that is confusing.

I tried various different delays: 10 seconds, 30 seconds, a minute, 3 minutes, and 5 minutes but every time the error messages pop up when opening VS Code again. Some of the times when I reopened VS Code I got slightly different error messages, see attached log messages.
[log.txt](https://github.com/microsoft/pylance-release/files/11495237/log.txt)

**Comment by kielnino** [comment]
This also happens to me. For me it started after I accidentally installed the pyright extension because I didn't know that the functionality is already included in pylance. After I uninstalled the pyright extension the error messages appear now.

**Comment by heejaechang** [comment]
we didn't get any issue over this for long time now. closing.
