### ISSUE TITLE
Auto-import should suggest exact matches with higher priority

### ISSUE THREAD

**Issue by matangover** [microsoft/pylance-release#297]
When showing code actions for `Path`, I get:

![image](https://user-images.githubusercontent.com/5028956/91623217-336ddb00-e9a3-11ea-9e80-a616eb2ef9a7.png)

The fourth item is clearly the one I'm after, as it's an exact match to what I've typed. Personally I'm inclined to think code actions should not suggest 'fuzzy' auto-imports at all (e.g. it's very improbably that I'm looking to import pathccompiler from numpy.distutils). That is, I don't naturally expect auto-complete in code actions, only auto-import of what I've already typed. But my main suggestion is to show the most relevant option (exact match) on top or at least have it initially selected.

**Comment by jakebailey** [comment]
We're currently working on this (#97); by `Path` I'm assuming you are actually interested in `pathlib.Path`, correct? We don't offer values out of modules that we haven't already analyzed, so you'll only get the odd thing that has been analyzed, or mostly, module names.

I believe that this is going to be much, much improved in next week's release (though we're still tweaking things!).

**Comment by matangover** [comment]
Oh, that's great! I see two separate issues:

1. Values from unanalyzed modules do not show up. I was just about to report this: `Add import Path from pathlib` doesn't show up unless I type `import pathlib` manually first (causing the module to be analyzed). I understand I don't need to report this, as it's already being worked on.

2. As I wrote above: When the module is already analyzed, the ordering of the items is not intuitive (exact match doesn't come first). Is this also being worked on / improved in the next release?

Thanks!

**Comment by jakebailey** [comment]
We're aware of both of these things. I know that the former is what we've been focusing on (getting values), and after that, the latter (then after that comes filtering them and ordering the values now that we have them).

**Comment by matangover** [comment]
Great. Thanks.

**Comment by matangover** [comment]
P.S. I believe most other IDEs don't offer 'fuzzy' matches for auto-import, and this is why I'm surprised to see so many options in the dropdown. But as long as the best option is selected first, it doesn't matter that much.

**Comment by heejaechang** [comment]
should be fixed in the next version.

**Comment by heejaechang** [comment]
until we improve the memory/CPU issue with auto-indexing, you need "python.analysis.indexing": true in .vscode/settings.json for add import/auto import feature to be enabled.

**Comment by matangover** [comment]
This is still not fixed, can it be re-opened?

![image](https://user-images.githubusercontent.com/5028956/130356218-62766f18-8296-48d7-a40c-7e9c0cf7fead.png)

Here `sys` should be shown but since it hasn't been analyzed yet (hasn't been manually imported), the auto-import suggestion are only showing results from the `os` module (which has been manually imported).

Using latest version `Pylance language server 2021.8.2 (pyright f462f5bb)`

**Comment by matangover** [comment]
Also:
![image](https://user-images.githubusercontent.com/5028956/130356380-69993846-cf66-42f3-ad69-b1c4b0c7c1f7.png)

The exact match shows up last instead of first.

**Comment by jakebailey** [comment]
Set `"python.analysis.indexing": true`, and if it works, then it will work when we enable indexing for everyone.

**Comment by matangover** [comment]
Thanks for the info. That's great! I confirm that adding this setting fixes issue 1 when having a workspace folder opened. However, it's still not fixed when only a single file is opened (i.e. having no workspace folder open).

Also, it doesn't fix issue 2:
![image](https://user-images.githubusercontent.com/5028956/130524492-6970cb8b-b1a9-48f5-b534-8073361ef8af.png)

**Comment by jakebailey** [comment]
We'd appreciate new issues for each of these, if you could.

**Comment by matangover** [comment]
I can open a new issue for "issue 1 not fixed when single file is opened". For "issue 2 not fixed" this current issue should be reopened, since it is exactly that.

**Comment by jakebailey** [comment]
Yes, thanks. I didn't notice.

**Comment by heejaechang** [comment]
now, we always enable indexing on stdlib and fixed a bug on ranking that got broken when we did file path normalization.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.1.1, which we've just released. You can find the changelog here:  [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202211-12-january-2022)
