### ISSUE TITLE
Code is marked as unreachable, even though it isn't

### ISSUE THREAD

**Issue by max-wittig** [microsoft/pylance-release#31]
## Environment data

-   Language Server version: Pylance language server 2020.6.1
-   OS and version: macOS 10.15.5
-   Python version (& distribution if applicable, e.g. Anaconda): CPython 3.8.3

## Expected behaviour

Code should not be marked as unreachable

## Actual behaviour

Code is marked as unreachable

## Code Snippet / Additional information

```python
import os
import sys

print("Hello Python")
info = os.getenv("URL") or sys.exit("Missing url")

print("Now everything is greyed out and marked as unreachable")
print("But it's not actually unreachable. Only if the env var URL is not defined")
```

**Comment by erictraut** [comment]
Thanks for the bug report. I've fixed the issue, and it will be addressed in a future release of Pylance.

**Comment by max-wittig** [comment]
Awesome thanks :+1:

**Comment by ro-kue** [comment]
Just FYI: The same happens with Django serializers and calling the save method.

**Comment by vhtkrk** [comment]
The print statement in this example also shows up as unreachable:

```python
class Base:

    def get_stuff(self):
        raise NotImplementedError

    def do_stuff(self):
        stuff = self.get_stuff()
        print("Is this unreachable?")

class Child(Base):

    def get_stuff(self):
        return "stuff"

c = Child()
c.do_stuff()
```

**Comment by erictraut** [comment]
This is a different situation. This behavior is expected in this case.

The method `get_stuff` has no return type annotation, so Pylance needs to infer its return type. Since the method always raises an exception and it is not marked as an abstract method, Pylance infers that its return type is `NoReturn`.

There are two ways you can address this in your code. (I recommend doing both.)
1. Declare `Base` as an abstract base class (i.e. derive from `abc.ABC`) and use the `@abstractmethod` decorator on the `get_stuff` method. This tells the type checker (and anyone who is reading your code) that this method must be overridden by a subclass.
2. Provide a return type annotation for method `do_stuff`.

```
from abc import ABC

class Base(ABC):
   @abstractmethod
   def get_stuff(self) -> str:
       raise NotImplementedError
```

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.7.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202070-9-july-2020

**Comment by phantom1299** [comment]
I'm still facing this with asyncio statements:

![Screenshot from 2020-11-23 16-31-57](https://user-images.githubusercontent.com/11743227/99967887-79231f80-2da9-11eb-80ce-d89c9d23363a.png)

**Comment by erictraut** [comment]
If you hover over `Heartbeat`, what type does Pylance indicate? I'm guessing that it will display a function with a return type of `NoReturn`, which means that Pylance believes that the function always raises an exception.

**Comment by phantom1299** [comment]
@erictraut yes, you're correct. But Heartbeat is function which has an endless loop. But since it will run as a task and has asyncio.sleep statements in it, it won't block the execution. Does Pylance support asyncio?

**Comment by VHeusdens** [comment]
Same after self.fail() in a unittest TestCase

**Comment by QuestofIranon** [comment]
Getting this with `start_transaction()` from mysql-connector

**Comment by jakebailey** [comment]
I think we'd appreciate a new issue for that; this one is old and likely not fully related. My expectation is that `start_transaction()` is not typed, and ends up having an inferred type of `NoReturn` or is a context manager missing a specific annotation, etc. It's hard to say without a full issue with a code example.

**Comment by slorg1** [comment]
Hi,

I am having this issue with the current version of Pylance:
Pylance 2021.2.4
Python 3.7.10 (it was the same before the 3.7.10 update, I want to say all 3.7.X have not worked)
VS code: 1.53.2
Ubuntu: 20.04.2 LTS

I boiled it down to this code (see screenshot for Pylance reporting unreachable code in the for loop)

```
from typing import NoReturn


def my_func(input_data: int) -> NoReturn:
    assert input_data >= 0
    print(input_data)


def my_other_func(input_data: int) -> NoReturn:
    assert input_data >= 0
    print(input_data * 2)


print("Hello")

for idx in range(10):

    assert idx >= 0

    if (idx % 2) == 0:
        print("looking fiiine")
        my_func(idx)
    else:
        print("looking good")

        my_other_func(idx)

    print("I'm running!")
    print("I'm reachable!")

print("I'm done!")
```
![image](https://user-images.githubusercontent.com/5043518/109168716-14cb7f80-774d-11eb-8b26-71e83283ff2c.png)


if I remove the asserts, it is the same:

![image](https://user-images.githubusercontent.com/5043518/109169606-f7e37c00-774d-11eb-8a35-ae79162cab80.png)

I hope this helps move this forward! :-)

Thank you!

**Comment by erictraut** [comment]
This is intended behavior. You have annotated `my_func` and `my_other_func` with a return type of `NoReturn`, which indicates to callers that the call to those functions will never return control back to the caller — i.e. they will always raise an exception or terminate the process. I think your intent was to specify `None` as the return type for these two functions.

**Comment by slorg1** [comment]
Hi @erictraut 

Thank you! Interpreted the python doc differently.

**Comment by osbm** [comment]
![image](https://user-images.githubusercontent.com/74963545/135334902-caae6258-d0f7-48bb-a48c-94dd921eaaf0.png)

```python
def notify(title: str, msg: str):
    if sys.platform == "linux":
        os.system(f"notify-send '{title}' '{msg}'")

    elif sys.platform == "win32":
        # pip install win10toast
        from win10toast import ToastNotifier
        toaster = ToastNotifier()
        toaster.show_toast(title, msg)

```

I don't know why this happens, i hope this helps.

**Comment by jakebailey** [comment]
@osbm Presumably, you're on Linux? The code flow analysis uses the platform you're editing on when analyzing the code, as it does for the Python version.

**Comment by osbm** [comment]
@jakebailey thank you i was worried that something about my code was wrong.

**Comment by thatdc** [comment]
Same issue here:

```
def extract_filenames(filepath):
    files_list = []
    print(f"Collecting {filepath}...")
    filenames = os.listdir(filepath)
    dirs = [x for x in filenames if os.path.isdir(os.path.join(filepath, x))]
    files = [x for x in filenames if os.path.isfile(os.path.join(filepath, x))]

    for d in dirs:
        deep_path = os.path.join(filepath, d)
        files_list.extend(extract_filenames(deep_path))
        print('hello')
    
    for f in files:
        files_list.append(os.path.join(filepath, f))
    
    return files_list
```

the `print('hello')` statement is marked as "code unreachable" but from the console I can see the hello printed out

**Comment by erictraut** [comment]
@thatdc, the problem you're seeing here has a different underlying cause than the original bug reported in this thread, but the symptoms are similar. The bug you're seeing is a duplicate of https://github.com/microsoft/pylance-release/issues/2093, which was also coincidentally reported within an hour of your post. I've fixed the underlying problem, and this fix will be included in the next release.

In the meantime, you can work around the issue by providing a return type annotation for your function:

```python
def extract_filenames(filepath) -> list:
   ...
```

**Comment by justingolden21** [comment]
Still getting code that runs that pylance calls unreachable in 2022. Tested it with some prints.

**Comment by erictraut** [comment]
@justingolden21, we would need more details to investigate the particular issue you're seeing. Please open a new issue if you think this is a problem with pylance. If it appears to be a problem with the type annotations or code in the library you are calling, please report the problem to that library author.

**Comment by justingolden21** [comment]
When I hover the unreachable code warning it says "pylance." I'm using vs code. I just assumed it was pylance because of that and found that other people have similar issues. It's not a big deal to me but I just wanted to report it. Should I still make a new ticket?

**Comment by Tobeyforce** [comment]
I'm getting unreachable code for the second block in this piece of code:

```
        try:
            content_type = ContentType.objects.get(app_label=app_label, model=model)
            page_preview = PagePreview.objects.get(content_type=content_type, token=self.request.GET["token"] + "shdhsa")
        
        except ContentType.DoesNotExist:
            raise ValidationError({"content_type": "Invalid value"})

        except PagePreview.DoesNotExist:
            # THIS BLOCK IS UNREACHABLE ACCORDING TO PYLANCE
            raise ValidationError({"preview": "Preview does not exist for this token and content_type combination"})
```
  
These two are exceptions from Django, as documented here:
https://docs.djangoproject.com/en/4.0/ref/exceptions/
The ObjectDoesNotExist one

Any idea how to fix this? I'm thinking it has something to do with both exceptions inheriting from the same base?

**Comment by grudelsud** [comment]
hi, I'm also having an unreachable code problem in vscode, here's what's happening to me.

I have a base class that inherits from a pynamodb Model class, with the following code:
```python
    @classmethod
    def get_or_none(cls, **kwargs):
        pk, sk = cls.build_pk_sk_keys(**kwargs)
        try:
            return cls.get(hash_key=pk, range_key=sk)
        except DoesNotExist:
            return None

    def build_pk_sk_keys(self, *args, **kwargs):
        raise NotImplemented
```

then **in a subclass**, method `build_pk_sk_keys` is implemented

```python
    @classmethod
    def build_pk_sk_keys(cls, user_id: str, company_id: str) -> tuple:
        return (
            f"{KeyPrefixes.USER_STATE}#{user_id}",
            f"{KeyPrefixes.COMPANY}#{company_id}",
        )

    @classmethod
    def get_or_default(cls, user_id: str, company_id: str):
        user_state = cls.get_or_none(user_id=user_id, company_id=company_id)
        # from this point on, this is marked as unreachable
        if not user_state:
            pk, sk = UserState.build_pk_sk_keys(user_id, company_id=company_id)
            user_state = cls(
                id=uuid.uuid4(), state="lp_null", pk=pk, sk=sk, user_id=user_id
            )
            user_state.save()

        return user_state
```

everything below `user_state = ...` is marked as unreachable, which is clearly not the case because get_or_none is going to use method build_pk_sk_keys from the subclass at runtime.

I'd be happy to entirely disable the unreachable code feature, if that's possible?

many thanks in advance for your help!

**Comment by erictraut** [comment]
@grudelsud, you're raising a `NotImplemented`, but you should be raising a `NotImplementedError`. These are unfortunately named similarly, but they are different types that have different purposes. If you fix this issue in your code, you should see the problem go away. Alternatively (or in addition), if you mark `build_pk_sk_keys` as an `@abstractmethod`, the problem will go away.

**Comment by erictraut** [comment]
@MrBr-github, Pylance is designed to be used with Python 3. Any code block that is guarded by a conditional checks for Python 2 will not be analyzed. So while the code block may run on your server, it is treated as unreachable from the perspective of the static code analyzer in Pylance.

Note that there is no "error" reported in this case. There's just a "hint" that causes VS Code to display the line in gray to indicate that the type analyzer is assuming that the code isn't reachable.

We have thought about changing the phrasing of the text associated with the hint because the current text "Code is unreachable" is a bit misleading, but we haven't come up with a clearer message yet.

In any case, the behavior you're seeing here is intended.

If you have code that is intended to run in Python 2, you might find that the Jedi language server serves your needs better.

**Comment by MrBr-github** [comment]
@erictraut 
Pylance is working very well, so I rely on it hints. In this case it's pretty missliding
IMO "Code is not analyzed" with hint of why not or with link to webpage with explanations why not is much better alternative
It's pretty hard to keep mentioned caveats in mind

P.S. thank you for your product :grinning:

**Comment by Reserver06** [comment]
Is there any way to turn off the "Code is unreachable" functionality?

**Comment by jenom** [comment]
I have this problem and get the `NoReturn` type (and hence the unreachable code) with the NumPy cross function. My NumPy version is 1.23.1. However, when I try to create a minimal example it works as expected. 

I think the problem arises, when an input value to `cross` comes from a C extension output with an unknown data type or a data type that VS Code does not correctly understand. Normally, it should show `any` type for the variable and in my code it shows this correctly for the two inputs. 

The return value for those any types is then `NoReturn` for the C-extension data (only known at runtime) while providing two `object()` as input (they have `any` type as well) gives the correct `any` return type for `cross`.

**Comment by erictraut** [comment]
@jenom, please open a new issue with a minimal self-contained code sample. If it depends on any third-party library imports, please include the version numbers of the libraries that you have installed.

**Comment by erictraut** [comment]
I'm going to lock this issue because it has been closed for a long time. If you are seeing similar symptoms and believe it may be a bug, please open a new issue with details.
