### ISSUE TITLE
"Expression value is unused" should not be reported for last expression in notebook cell

### ISSUE THREAD

**Issue by matangover** [microsoft/pylance-release#3282]
Jupyter notebook uses the last expression in each cell as the cell's output. Hence, it should not be reported as unused.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2022.11.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221131-16-November-2022-PreRelease)

**Comment by alecglen** [comment]
I am still seeing this behavior in v2022.11.40 and v2022.11.41 (pre-release).

**Comment by rchiodo** [comment]
What's your version of the jupyter extension? It may be providing its own errors in this situation if it's not the latest prerelease for jupyter too.

**Comment by dream-dasher** [comment]
Hi there.
Is there a way to get this behavior in notebook files saved as `.py`.

A generally preferable (opinion) way of working with notebooks is as raw code -- using something like [Jupytext](https://jupytext.readthedocs.io/en/latest/) or [Zed's Repl environ](https://zed.dev/docs/repl), both of which allow using comments to demarcate cells.  (This allows for tool interoperation between python code and note books, useable git diffs, notebooks to be run as scripts, etc.)

e.g. :
```python
# %%
preproced = "Hello, {{name}}, {{name}},  }}."
procd = replace_placeholder(preproced, "name", "__Alice__")
procd

# %%
procd_counted = extract_placeholders(procd)
len(procd_counted)
```

Pyright, of course, doesn't recognize the comment syntax.  Is there a way to give it a specific file or director over which the "unused expression" can be ignored?

**Comment by rchiodo** [comment]
Sorry there's no way to specify that a `#%%` commented file is actually a set of cells, but sounds like a good enhancement request. VS code has had an interactive window that supports `#%%` for a long time and it seems like we should treat those files differently.

**Comment by debonte** [comment]
> sounds like a good enhancement request

These existing enhancement requests might cover the functionality that you are hoping to see. If so, please up-vote them:

- https://github.com/microsoft/pylance-release/discussions/3851
- https://github.com/microsoft/pylance-release/discussions/4703
