### ISSUE TITLE
Python language server no longer recommends auto imports from local files (still works for site-packages in venv)

### ISSUE THREAD

**Issue by SimonSchick** [microsoft/pylance-release#3380]
Type: <b>Bug</b>

Unsure, it worked 3 days ago, not it doesn't, didn't change any workspace settings what so ever.

Extension version: 2022.14.0
VS Code version: Code 1.71.2 (Universal) (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (6.37GB free)|
|Process Argv|--crash-reporter-id 0731fb54-df68-48c8-9bc7-cb94d92db4d8|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by judej** [comment]
Could you please try turning off indexing in the settings file and see if the recommendations reappear?
`"python.analysis.indexing": false`

**Comment by SimonSchick** [comment]
This doesn't not appear to solve the issue.

**Comment by aksestok** [comment]
I had the same issue as you, and have found a workaround. It seems to be related to `pyright` looking for its configuration in `./pyproject.toml` if it exists. Can you check the output logs of "Python Language Server"? For me it looks something like this if `pyright` finds the pyproject.toml file, but not the `tool.pyright` section:
```
...
[Info  - 8:14:29 AM] (9676) No configuration file found.
[Info  - 8:14:29 AM] (9676) pyproject.toml file found at {{workspace path}}.
[Info  - 8:14:29 AM] (9676) Setting pythonPath for service "python": "{{venv path}}"
[Info  - 8:14:29 AM] (9676) Loading pyproject.toml file at {{workspace path}}/pyproject.toml
[Error - 8:14:29 AM] (9676) Pyproject file "{{workspace path}}/pyproject.toml" is missing "[tool.pyright]" section.
```

## Workaround 1

Add an empty section to the `pyproject.toml` in the workspace:
pyproject.toml
```toml
# adding the empty section below fixes the issue

[tool.pyright]

```

## Workaround 2

Delete `pyproject.toml`

**Comment by alejoar** [comment]
I am having the same issue.

Imports suddenly stopped working without changing any settings.

Curiously enough, if I open the module with a function I want to import in a new VSCode tab, then Pylance finds it and auto import works as it should in the original file. Obviously this is not convenient at all specially with big projects. Can't have all the modules opened all the time.

None of the suggestions in this thread fixed the issue.

**Comment by SimonSchick** [comment]
Adding `[tool.pyright]` seems to indeed have fixed the issue combined with `"python.analysis.indexing": true`

**Comment by debonte** [comment]
FYI, the `pyproject.toml` issue is https://github.com/microsoft/pylance-release/issues/3348, which is fixed in our latest prerelease build (2022.9.31).

**Comment by alejoar** [comment]
> FYI, the `pyproject.toml` issue is #3348, which is fixed in our latest prerelease build (2022.9.31).

I still have this issue running on 2022.9.31

Maybe it's a different from op. See my description above.

**Comment by debonte** [comment]
> Curiously enough, if I open the module with a function I want to import in a new VSCode tab, then Pylance finds it and auto import works 

@alejoar, does setting `"python.analysis.indexing": true` fix this for you?

cc: @heejaechang

**Comment by alejoar** [comment]
@debonte no it doesn't. Only works after I have open the file that contains what I intend to import.

**Comment by heejaechang** [comment]
user symbol only shows up auto import if it is used by some files already transitively. all of user symbols will show up in ```add import``` not ```auto import```.

you can get ```add import``` by putting your caret on the ```unknown symbol``` and do ```ctrl+.``` to bring up light blub (code action)

**Comment by alejoar** [comment]
> you can get `add import` by putting your caret on the `unknown symbol` and do `ctrl+.` to bring up light blub (code action)

@heejaechang indeed this works. However this behavior is different from what I used to have before, where I would start typing and the auto imports would get suggested. Then just pressing TAB would trigger the auto import.

Is this some setting I accidentally changed? Do you know how do I get back to the behavior I am describing?

**Comment by heejaechang** [comment]
> Is this some setting I accidentally changed? Do you know how do I get back to the behavior I am describing?

it has been this way for long time. I think before without you realizing, user symbols you wanted somehow used somewhere in open files transitively. that's why it showed up.

by transitively, what I mean is some imports in one of your opened files are imported the file that have the symbol you wanted used. 

ex) file 'a.py' has import lib and file lib.py has import lib2 and lib2.py has import lib3 and so on. then all symbols in a, lib, lib2, lib3 will be shown in auto import.

that being said, we can consider adding new option to show all user symbols in auto import if we have enough vote for people who are fine with having perf hit time to time to include a few thousands item in completion.

**Comment by heejaechang** [comment]
please upvote the issue if you want to option to make all user symbols show up in completion.
