### ISSUE TITLE
The Pylance server crashed 5 times in the last 3 minutes in a .py file.

### ISSUE THREAD

**Issue by GXZlegend** [microsoft/pylance-release#3453]
My Pylance server keeps crashing when working in one of my workspaces. I only make minor modifications to my code and Pylance crashes soon after I start working. This does not happen in other workspaces.

I'm asking how this crashing could happen. If possible, please tell me how I can avoid this crashing.

Thanks!

Here is the output of Python Language Server:

```plain
[Info  - 2:12:11 AM] (1311001) Pylance language server 2022.10.10 (pyright 59bdc42e) starting
[Info  - 2:12:11 AM] (1311001) Server root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist
[Info  - 2:12:11 AM] (1311001) Starting service instance "source_free_domain_adaptation"
[Info  - 2:12:11 AM] (1311001) Notebook support: LSP
[Info  - 2:12:11 AM] (1311001) Interactive window support: LSP
[Info  - 2:12:11 AM] (1311001) No configuration file found.
[Info  - 2:12:11 AM] (1311001) No pyproject.toml file found.
[Info  - 2:12:11 AM] (1311001) Setting pythonPath for service "source_free_domain_adaptation": "/home/guoxingzhuo/anaconda3/bin/python"
[Warn  - 2:12:11 AM] (1311001) stubPath /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/typings is not a valid directory.
[Info  - 2:12:11 AM] (1311001) Assuming Python version 3.9
[Info  - 2:12:11 AM] (1311001) Assuming Python platform Linux
[Info  - 2:12:11 AM] (1311001) Searching for source files
[Info  - 2:12:11 AM] (1311001) Found 2 source files
[Info  - 2:12:11 AM] (1311001) Background analysis(1) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist
[Info  - 2:12:11 AM] (1311001) Background analysis(1) started
[Info  - 2:12:12 AM] (1311001) Indexer background runner(2) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist (index)
[Info  - 2:12:12 AM] (1311001) Indexing(2) started
[Info  - 2:12:14 AM] (1311001) [BG(1)] Long operation: getSemanticTokens full at /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/shot.py (2762ms)
[Info  - 2:12:17 AM] (1311001) [IDX(2)] Long operation: index execution environment /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (4481ms)
[Info  - 2:12:17 AM] (1311001) [IDX(2)] Long operation: index libraries /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (5085ms)
[Info  - 2:12:17 AM] (1311001) Indexer done(2). indexed 676 files
[Info  - 2:12:29 AM] (1311001) Indexer background runner(3) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist (refresh)
[Info  - 2:12:29 AM] (1311001) Indexing(3) started
[Info  - 2:12:30 AM] (1311001) [BG(1)] Long operation: checking: /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/shot.py (2077ms)
[Info  - 2:12:30 AM] (1311001) [BG(1)] Long operation: analyzing: /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/shot.py (2245ms)
[Info  - 2:12:34 AM] (1311001) [IDX(3)] Long operation: index execution environment /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (4532ms)
[Info  - 2:12:34 AM] (1311001) [IDX(3)] Long operation: index libraries /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (5184ms)
[Info  - 2:12:34 AM] (1311001) Indexer done(3). indexed 676 files
[Info  - 2:13:36 AM] (1311001) Indexer background runner(4) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist (refresh)
[Info  - 2:13:36 AM] (1311001) Indexing(4) started
[Info  - 2:13:38 AM] (1311001) [BG(1)] Long operation: checking: /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/shot.py (2157ms)
[Info  - 2:13:38 AM] (1311001) [BG(1)] Long operation: analyzing: /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/shot.py (2384ms)
[Info  - 2:13:41 AM] (1311001) [IDX(4)] Long operation: index execution environment /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (4532ms)
[Info  - 2:13:41 AM] (1311001) [IDX(4)] Long operation: index libraries /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (5158ms)
[Info  - 2:13:41 AM] (1311001) Indexer done(4). indexed 676 files
[Info  - 2:14:12 AM] (1311001) Indexer background runner(5) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist (refresh)
[Info  - 2:14:12 AM] (1311001) Indexing(5) started
[Info  - 2:14:14 AM] (1311001) [BG(1)] Long operation: analyzing: /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/shot.py (2140ms)
[Info  - 2:14:17 AM] (1311001) [IDX(5)] Long operation: index execution environment /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (5029ms)
[Info  - 2:14:17 AM] (1311001) [IDX(5)] Long operation: index libraries /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (5686ms)
[Info  - 2:14:17 AM] (1311001) Indexer done(5). indexed 676 files
[Info  - 2:14:26 AM] (1311001) Indexer background runner(6) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist (refresh)
[Info  - 2:14:26 AM] (1311001) Indexing(6) started
[Info  - 2:14:31 AM] (1311001) [IDX(6)] Long operation: index execution environment /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (4904ms)
[Info  - 2:14:31 AM] (1311001) [IDX(6)] Long operation: index libraries /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (5545ms)
[Info  - 2:14:31 AM] (1311001) Indexer done(6). indexed 676 files
[Info  - 2:15:04 AM] (1311001) Indexer background runner(7) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist (refresh)
[Info  - 2:15:04 AM] (1311001) Indexing(7) started
[Info  - 2:15:06 AM] (1311001) [BG(1)] Long operation: checking: /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/shot.py (2360ms)
[Info  - 2:15:06 AM] (1311001) [BG(1)] Long operation: analyzing: /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/shot.py (2627ms)
[Info  - 2:15:09 AM] (1311001) [IDX(7)] Long operation: index execution environment /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (4801ms)
[Info  - 2:15:09 AM] (1311001) [IDX(7)] Long operation: index libraries /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (5454ms)
[Info  - 2:15:09 AM] (1311001) Indexer done(7). indexed 676 files
Error: request cancelled
    at t.throwIfCancellationRequested (/home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist/pyright-internal/src/common/cancellationUtils.ts:42:15)
    at MessagePort.<anonymous> (/home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist/server.bundle.js:1:393328)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[Info  - 2:15:10 AM] Connection to server got closed. Server will restart.
[Info  - 2:15:10 AM] (1322841) Pylance language server 2022.10.10 (pyright 59bdc42e) starting
[Info  - 2:15:10 AM] (1322841) Server root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist
[Info  - 2:15:10 AM] (1322841) Starting service instance "source_free_domain_adaptation"
[Info  - 2:15:10 AM] (1322841) Notebook support: LSP
[Info  - 2:15:10 AM] (1322841) Interactive window support: LSP
[Info  - 2:15:10 AM] (1322841) No configuration file found.
[Info  - 2:15:10 AM] (1322841) No pyproject.toml file found.
[Info  - 2:15:10 AM] (1322841) Setting pythonPath for service "source_free_domain_adaptation": "/home/guoxingzhuo/anaconda3/bin/python"
[Warn  - 2:15:10 AM] (1322841) stubPath /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/typings is not a valid directory.
[Info  - 2:15:10 AM] (1322841) Assuming Python version 3.9
[Info  - 2:15:10 AM] (1322841) Assuming Python platform Linux
[Info  - 2:15:11 AM] (1322841) Searching for source files
[Info  - 2:15:11 AM] (1322841) Found 2 source files
[Info  - 2:15:11 AM] (1322841) Background analysis(1) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist
[Info  - 2:15:11 AM] (1322841) Background analysis(1) started
[Info  - 2:15:11 AM] (1322841) Indexer background runner(2) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist (index)
[Info  - 2:15:11 AM] (1322841) Indexing(2) started
[Info  - 2:15:13 AM] (1322841) [BG(1)] Long operation: getSemanticTokens full at /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/shot.py (2799ms)
[Info  - 2:15:16 AM] (1322841) [IDX(2)] Long operation: index execution environment /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (4520ms)
[Info  - 2:15:16 AM] (1322841) [IDX(2)] Long operation: index libraries /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (5140ms)
[Info  - 2:15:16 AM] (1322841) Indexer done(2). indexed 676 files
Error: request cancelled
    at t.throwIfCancellationRequested (/home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist/pyright-internal/src/common/cancellationUtils.ts:42:15)
    at MessagePort.<anonymous> (/home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist/server.bundle.js:1:393328)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[Info  - 2:15:16 AM] Connection to server got closed. Server will restart.
[Info  - 2:15:17 AM] (1322876) Pylance language server 2022.10.10 (pyright 59bdc42e) starting
[Info  - 2:15:17 AM] (1322876) Server root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist
[Info  - 2:15:17 AM] (1322876) Starting service instance "source_free_domain_adaptation"
[Info  - 2:15:17 AM] (1322876) Notebook support: LSP
[Info  - 2:15:17 AM] (1322876) Interactive window support: LSP
[Info  - 2:15:17 AM] (1322876) No configuration file found.
[Info  - 2:15:17 AM] (1322876) No pyproject.toml file found.
[Info  - 2:15:17 AM] (1322876) Setting pythonPath for service "source_free_domain_adaptation": "/home/guoxingzhuo/anaconda3/bin/python"
[Warn  - 2:15:17 AM] (1322876) stubPath /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/typings is not a valid directory.
[Info  - 2:15:17 AM] (1322876) Assuming Python version 3.9
[Info  - 2:15:17 AM] (1322876) Assuming Python platform Linux
[Info  - 2:15:17 AM] (1322876) Searching for source files
[Info  - 2:15:17 AM] (1322876) Found 2 source files
[Info  - 2:15:17 AM] (1322876) Background analysis(1) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist
[Info  - 2:15:17 AM] (1322876) Background analysis(1) started
[Info  - 2:15:17 AM] (1322876) Indexer background runner(2) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist (index)
[Info  - 2:15:17 AM] (1322876) Indexing(2) started
[Info  - 2:15:20 AM] (1322876) [BG(1)] Long operation: getSemanticTokens full at /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/shot.py (2673ms)
[Info  - 2:15:23 AM] (1322876) [IDX(2)] Long operation: index execution environment /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (4580ms)
[Info  - 2:15:23 AM] (1322876) [IDX(2)] Long operation: index libraries /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (5178ms)
[Info  - 2:15:23 AM] (1322876) Indexer done(2). indexed 676 files
Error: request cancelled
    at t.throwIfCancellationRequested (/home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist/pyright-internal/src/common/cancellationUtils.ts:42:15)
    at MessagePort.<anonymous> (/home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist/server.bundle.js:1:393328)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[Info  - 2:15:23 AM] Connection to server got closed. Server will restart.
[Info  - 2:15:23 AM] (1322935) Pylance language server 2022.10.10 (pyright 59bdc42e) starting
[Info  - 2:15:23 AM] (1322935) Server root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist
[Info  - 2:15:23 AM] (1322935) Starting service instance "source_free_domain_adaptation"
[Info  - 2:15:23 AM] (1322935) Notebook support: LSP
[Info  - 2:15:23 AM] (1322935) Interactive window support: LSP
[Info  - 2:15:23 AM] (1322935) No configuration file found.
[Info  - 2:15:23 AM] (1322935) No pyproject.toml file found.
[Info  - 2:15:23 AM] (1322935) Setting pythonPath for service "source_free_domain_adaptation": "/home/guoxingzhuo/anaconda3/bin/python"
[Warn  - 2:15:23 AM] (1322935) stubPath /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/typings is not a valid directory.
[Info  - 2:15:23 AM] (1322935) Assuming Python version 3.9
[Info  - 2:15:23 AM] (1322935) Assuming Python platform Linux
[Info  - 2:15:24 AM] (1322935) Searching for source files
[Info  - 2:15:24 AM] (1322935) Found 2 source files
[Info  - 2:15:24 AM] (1322935) Background analysis(1) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist
[Info  - 2:15:24 AM] (1322935) Background analysis(1) started
[Info  - 2:15:24 AM] (1322935) Indexer background runner(2) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist (index)
[Info  - 2:15:24 AM] (1322935) Indexing(2) started
[Info  - 2:15:27 AM] (1322935) [BG(1)] Long operation: getSemanticTokens full at /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/shot.py (2757ms)
[Info  - 2:15:29 AM] (1322935) [IDX(2)] Long operation: index execution environment /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (4595ms)
[Info  - 2:15:29 AM] (1322935) [IDX(2)] Long operation: index libraries /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (5197ms)
[Info  - 2:15:29 AM] (1322935) Indexer done(2). indexed 676 files
Error: request cancelled
    at t.throwIfCancellationRequested (/home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist/pyright-internal/src/common/cancellationUtils.ts:42:15)
    at MessagePort.<anonymous> (/home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist/server.bundle.js:1:393328)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[Info  - 2:15:30 AM] Connection to server got closed. Server will restart.
[Info  - 2:15:30 AM] (1323640) Pylance language server 2022.10.10 (pyright 59bdc42e) starting
[Info  - 2:15:30 AM] (1323640) Server root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist
[Info  - 2:15:30 AM] (1323640) Starting service instance "source_free_domain_adaptation"
[Info  - 2:15:30 AM] (1323640) Notebook support: LSP
[Info  - 2:15:30 AM] (1323640) Interactive window support: LSP
[Info  - 2:15:30 AM] (1323640) No configuration file found.
[Info  - 2:15:30 AM] (1323640) No pyproject.toml file found.
[Info  - 2:15:30 AM] (1323640) Setting pythonPath for service "source_free_domain_adaptation": "/home/guoxingzhuo/anaconda3/bin/python"
[Warn  - 2:15:30 AM] (1323640) stubPath /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/typings is not a valid directory.
[Info  - 2:15:30 AM] (1323640) Assuming Python version 3.9
[Info  - 2:15:30 AM] (1323640) Assuming Python platform Linux
[Info  - 2:15:30 AM] (1323640) Searching for source files
[Info  - 2:15:30 AM] (1323640) Found 2 source files
[Info  - 2:15:30 AM] (1323640) Background analysis(1) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist
[Info  - 2:15:30 AM] (1323640) Background analysis(1) started
[Info  - 2:15:31 AM] (1323640) Indexer background runner(2) root directory: /home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist (index)
[Info  - 2:15:31 AM] (1323640) Indexing(2) started
[Info  - 2:15:33 AM] (1323640) [BG(1)] Long operation: getSemanticTokens full at /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation/shot.py (2989ms)
[Info  - 2:15:36 AM] (1323640) [IDX(2)] Long operation: index execution environment /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (4708ms)
[Info  - 2:15:36 AM] (1323640) [IDX(2)] Long operation: index libraries /workspace/guoxingzhuo/Transfer-Learning-Library/examples/domain_adaptation/source_free_domain_adaptation (5376ms)
[Info  - 2:15:36 AM] (1323640) Indexer done(2). indexed 676 files
Error: request cancelled
    at t.throwIfCancellationRequested (/home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist/pyright-internal/src/common/cancellationUtils.ts:42:15)
    at MessagePort.<anonymous> (/home/guoxingzhuo/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.10/dist/server.bundle.js:1:393328)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[Error - 2:15:36 AM] The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by judej** [comment]
Could you please send us repro steps for this issue?

**Comment by GXZlegend** [comment]
> Could you please send us repro steps for this issue?

I'm sorry but, to the best of my repro, the crashing occurs almost randomly.

One of the clues is that, when I perform folder operations (creating/deleting), there might be an `Error: request cancelled` in the Pylance output. Another observation is that the crashing happens after I run a .py file.

Could these help?

**Comment by GXZlegend** [comment]
> Could you please send us repro steps for this issue?

Could you please send us repro steps for this issue?

I'm sorry but, to the best of my repro, the crashing occurs almost randomly.

One of the clues is that, when I perform folder operations (creating/deleting), there might be an Error: request cancelled in the Pylance output. Another observation is that the crashing happens after I run a .py file.

Could these help?

**Comment by GXZlegend** [comment]
> are you using it locally? or are you using it over remote such as SSH/WSL or something else?

I am using remote-SSH on my server.

**Comment by RoacherM** [comment]
> 
same problom when open jupyter notebook on remote server, the logs is below:
Error: request cancelled
    at t.throwIfCancellationRequested (/home/**/.vscode-server/extensions/ms-python.vscode-pylance-2022.9.40/dist/pyright-internal/src/common/cancellationUtils.ts:42:15)
    at MessagePort.<anonymous> (/home/**/.vscode-server/extensions/ms-python.vscode-pylance-2022.9.40/dist/server.bundle.js:1:470717)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[Info  - 11:18:42 PM] Connection to server got closed. Server will restart.
[Info  - 11:18:42 PM] (3305989) Pylance language server 2022.9.40 (pyright 9fd1b94c) starting
[Info  - 11:18:42 PM] (3305989) Server root directory: /home/**/.vscode-server/extensions/ms-python.vscode-pylance-2022.9.40/dist
[Info  - 11:18:42 PM] (3305989) Starting service instance "workspace"
[Info  - 11:18:42 PM] (3305989) Notebook support: LSP
[Info  - 11:18:42 PM] (3305989) Interactive window support: LSP

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2022.10.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221021-12-October-2022-PreRelease)

**Comment by hamjam** [comment]
The problem still occurs for my  prerelease version 2022.10.21

**Comment by tautomer** [comment]
Switched to pre-release, but the same problem still shows up over SSH.

```[Info  - 4:02:25 PM] (2844389) [BG(1)] Long operation: analyzing: /projects/ethene_with_nacr/long/training.py (3024ms)
Error: request cancelled
    at t.throwIfCancellationRequested (/vast/home/user/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.21/dist/pyright-internal/src/common/cancellationUtils.ts:42:15)
    at MessagePort.<anonymous> (/vast/home/user/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.21/dist/server.bundle.js:1:436772)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[Info  - 4:02:25 PM] Connection to server got closed. Server will restart.
[Info  - 4:02:25 PM] (2854863) Pylance language server 2022.10.21 (pyright 50e12b4b) starting
[Info  - 4:02:25 PM] (2854863) Server root directory: /vast/home/user/.vscode-server/extensions/ms-python.vscode-pylance-2022.10.21/dist
```

**Comment by rchiodo** [comment]
@tautomer my guess is that this is a problem with compatibility between the jupyter extension and the pylance extension.

What's your version of the jupyter extension on the remote machine?

**Comment by Tikquuss** [comment]
I had this problem with VS code version 1.84.0 (2023-11-01), and the error squiggle lines were not showing. 
I tried some [solutions](https://stackoverflow.com/questions/59739526/why-are-pylints-error-squiggle-lines-not-showing-in-python-visual-studio-code), but none of them worked.

Once I read @rchiodo comment, I uninstalled Pylance, and everything started working.

**Comment by pvtien96** [comment]
@Tikquuss I experienced the same issue with version 1.84.0, which disrupted auto-completion and suggestions. I suspect this might be connected to remote SSH. Uninstalling Pylance resolved the problem for me.

**Comment by ricardodeazambuja** [comment]
I was having problems with pylance as well and the problem was solved by changing the value for `python.analysis.stubPath` to an empty string to make it look for stuf in the current directory (I'm using my local conda/mamba and this is set as the interpreter for vscode).
