### ISSUE TITLE
Matplotlib subplots not returning correct types

### ISSUE THREAD

**Issue by danpe027** [microsoft/pylance-release#3482]
## Environment data

-   Language Server version: 2022.10.20
-   OS and version: Ubuntu 22.04 on WSL in Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 
    - Python 3.10.4
    - conda environment with conda 4.10.3
    - Matplotlib version 3.6.1
    - numpy version 1.23.3

## Code Snippet

```python
import matplotlib.pyplot as plt
import numpy as np

num_row = 2
num_col = 1

x = np.linspace(-np.pi, np.pi)
f = []
f.append(np.sin(x))
f.append(np.cos(x))

fig, axes = plt.subplots(nrows=num_row, ncols=num_col)
for i, axis in enumerate(axes.flat):
    axis.plot(f[i])
plt.show()
```

## Expected behavior

The variable `axes` should be of type `NDArray[Axes]` and `axes` should, for example, have the member `flat`

## Actual behavior

The variable is of type `list[Axes]` and there is an error saying

```
Cannot access member "flat" for type "list[Axes"] Member "flat" is unknown
```

This is true for any `num_row>1` or `num_col>1`

**Comment by xozion** [comment]
The same type of error also occurs for single-subplots, where only one Axes object is returned.
## Environment data

-   Language Server version: 2022.11.30 (pyright 04a10583)
-   OS and version: Windows 10 Pro 22H2
-   Python version: Python 3.7.9

## Code Snippet

```python
from matplotlib import pyplot as plt
fig, ax = plt.subplots(1)
ax.get_xaxis().set_ticks([])
```

## Expected behavior

Type of 'ax' gets infered as (single) plt.Axes, because we only create 1 subplot.

## Actual behavior

Type of 'ax' gets infered as list[Axes]. Therefore following member function calls, e.g. get_xaxis() result in type error
> Cannot access member "get_xaxis" for type "list[Axes]"
  Member "get_xaxis" is unknown

**Comment by rchiodo** [comment]
My guess for both of these problems is that the type stubs are either incorrect or not descriptive enough in order to handle these scenarios.

Type stubs for matplotlib come from here:
https://github.com/microsoft/python-type-stubs/tree/main/matplotlib

**Comment by bschnurr** [comment]
maybe there is a way using @overloads and `Literal[1]` to define a signature to return what you expect

**Comment by bschnurr** [comment]
try
```python
fig, axs = plt.subplots(1,1)
```

![image](https://user-images.githubusercontent.com/1946977/203621285-818bf6ec-b923-45c4-a6db-37c14a33e3df.png)

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2023.4.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023421-12-April-2023-PreRelease)

**Comment by kaigu1997** [comment]
The issue still occurs when calling `fig.subplots()`.

Just a small modification of the above code
```
import matplotlib.pyplot as plt
import numpy as np

num_row = 2
num_col = 1

x = np.linspace(-np.pi, np.pi)
f = []
f.append(np.sin(x))
f.append(np.cos(x))

fig = plt.figure()
axes = fig.subplots(nrows=num_row, ncols=num_col)
for i, axis in enumerate(axes.flat):
    axis.plot(f[i])
plt.show()
```
and Pylance give the following error information:
```
Cannot access member "flat" for type "list[Axes]"
  Member "flat" is unknown
```

**Comment by debonte** [comment]
@kaigu1997, please file a new issue on this. The problem is in a different spot. The return types of `plt.subplots` and `fig.subplots` are inconsistent in the stubs.
