### ISSUE TITLE
Expected class type but received "DeclarativeMeta"

### ISSUE THREAD

**Issue by Cdayz** [microsoft/pylance-release#360]
Sorry for my awful english.

## Environment data

-   Language Server version: 2020.9.4 (pyright 9983747f)
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.3, pyenv

## Expected behaviour

No type errors, because in that case i am use DelcarativeBase metaclass for create sqlalchemy model

## Actual behaviour

Pylance threat a class created from a metaclass as not a class
![2020-09-11_14-34](https://user-images.githubusercontent.com/30727708/92921099-1d98f500-f43c-11ea-8e8f-b7f3b63dac8b.png)
![2020-09-11_14-34_1](https://user-images.githubusercontent.com/30727708/92921137-343f4c00-f43c-11ea-9af5-561a6ab5630b.png)

**Comment by erictraut** [comment]
Thank you for reporting this problem. Pylance was not correctly handling the case where a class was created by directly instantiating a metaclass. Most libraries use the "metaclass hook" to statically declare new classes based on a metaclass, but sqlalchemy is doing something more dynamic here. I've added code to Pyright (the type checker used by Pylance) to handle this case, and the fix will be in the next release of Pylance.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.5, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202095-16-september-2020

**Comment by Distortedlogic** [comment]
I am still receiving this error
![06-10-2020-07-22-28](https://user-images.githubusercontent.com/54854447/95195535-af2e2500-07a4-11eb-80e2-1887a65ddbf7.png)

**Comment by erictraut** [comment]
@Distortedlogic, can you please file a new issue and provide more context — preferably a short snippet of self-contained code that repros the problem? Thanks!
