### ISSUE TITLE
Python intellisense is very slow

### ISSUE THREAD

**Issue by ilouzl** [microsoft/pylance-release#3668]
Type: <b>Bug</b>

Text highlighting and auto complete are very slow under specific python envs.

Python Language Server prints log messages of 'Long operation' like this:
`[Info  - 11:15:48 AM] (31493) [BG(1)] Long operation: getSemanticTokens full at /Users/liron/Desktop/detector.py (124762ms)`

Tried to revert to older extension versions - with no improvement. 
This is the pip freeze output:
```
affine==2.3.1
attrs==22.1.0
bleak==0.12.1
certifi==2022.9.24
charset-normalizer==2.1.1
contourpy==1.0.6
cycler==0.11.0
delayed-image==0.2.3
distinctipy==1.2.2
ffmpeg-python==0.2.0
fonttools==4.38.0
future==0.18.2
idna==3.4
imageio==2.22.4
joblib==1.2.0
jsonschema==4.17.1
kiwisolver==1.4.4
kwarray==0.6.5
kwcoco==0.5.1
kwimage==0.9.7
matplotlib==3.6.2
networkx==2.8.8
numpy==1.23.5
opencv-python==4.6.0.66
packaging==21.3
pandas==1.5.2
parse==1.19.0
Pillow==9.3.0
pycocotools==2.0.6
pyobjc-core==9.0
pyobjc-framework-Cocoa==9.0
pyobjc-framework-CoreBluetooth==9.0
pyobjc-framework-libdispatch==9.0
pyparsing==3.0.9
pyrsistent==0.19.2
python-dateutil==2.8.2
pytz==2022.6
PyWavelets==1.4.1
PyYAML==6.0
requests==2.28.1
safer==4.4.1
scikit-image==0.19.3
scikit-learn==1.1.3
scipy==1.9.3
scriptconfig==0.7.1
Shapely==1.8.5.post1
six==1.16.0
sortedcontainers==2.4.0
-e git+ssh://git@bitbucket.org/tap_rd/tap_camera_algorithms_python.git@04d11c66dd7cda85cb87711381c3f6418de4b589#egg=tapalgo
tapsdk @ git+https://github.com/TapWithUs/tap-python-sdk@07d84d89c3c425fbb47ee56149f3d3b5bda3d311
threadpoolctl==3.1.0
tifffile==2022.10.10
tqdm==4.64.1
ubelt==1.2.2
uritools==4.0.0
urllib3==1.26.12
xarray==2022.11.0
```

Python Extension version: 2022.18.2
Pylance Extension version: 2022.11.30
VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.53GB free)|
|Process Argv|--crash-reporter-id 37c91045-05a3-4c4f-89d9-994246d45d08|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue. Could you share the repository you're running this on so we can try to repro the problem?

**Comment by bschnurr** [comment]
Also suggest putting your code inside a folder and then using "open folder"

**Comment by ilouzl** [comment]
@rchiodo 
It's a private repo, so I'm afraid I cant share it.

@brettcannon  
This is how I always work - I open the folder of the repo.

Do you think maybe there's a specific package that might cause this latency?

**Comment by erictraut** [comment]
@ilouzl, based on the log message that you shared, it looks like `detector.py` is taking an extremely long time to analyze. You could try to narrow down the portion of that module that's causing the long analysis time by commenting out portions. I typically use a bisection approach (e.g. start by commenting out the second half of the source file, etc.). If you can narrow it down to a particular section that can be extracted from the file and then sufficiently obfuscated and shared with us, we could take a look at the underlying cause.

**Comment by bschnurr** [comment]
in the past scipy has caused a lot of perf issues if that helps track it down.

**Comment by ilouzl** [comment]
@erictraut , I took your suggestion and bisected the code.
I quickly noticed that when importing numpy things start to get slower (~2sec analysis), but if I also import pandas at the same script, latency becomes very long (~15sec).
The rest of import does't impact latency.

**Comment by erictraut** [comment]
That's a good clue, but we'll need to go a bit deeper. Pyright (the type checker upon which pylance is built) is a "lazy" type checker in that it evaluates the types of symbols only when they are referenced. That goes for imported symbols as well. So a simple import statement will not cause pyright to do much work. We'll need to determine which symbols from within those imports are triggering the long analysis times. It will require more bisecting to determine which pandas symbol(s) you're accessing that result in the long analysis time.

Do you have any pandas type stubs installed locally in your project or within your python environment, or are you using the pandas stubs that are bundled with pylance? You can tell by right-clicking on `pandas` or `pd` and choosing `Go To Declaration`. That should open a `.pyi` (stub) file.

Also, the times that you're reporting here (15s) are long, but they are nowhere near what your log message indicated (124.7s).

**Comment by ilouzl** [comment]
Going further with the bisection, I reduced the script to the minimum required to demonstrate the issue


```
import numpy as np
import pandas as pd

class IMUDataSet(Dataset):
    def __init__(self, data_dir, transforms=None, jitter=None, class_ratio=None):
        self.triggers, self.records, self.data = make_dataset(data_dir)
        self.triggers["label"] = 1
        self.transforms = transforms
        self.jitter = jitter
        self.c_ratio = class_ratio
        if self.c_ratio is not None:
            self.balance_classes()
    
    def balance_classes(self):
        n_false_triggers = len(self)*(1 - self.c_ratio)/self.c_ratio
        n_false_triggers_per_record = int(n_false_triggers / len(self.records)) 
        trigger_per_record = self.triggers.groupby('record_id')
        for rec_id, rec in self.records.iterrows():
            rec_len = len(self.data[rec['filename']])
            candidate_false_trigger_idx = np.arange(rec_len)
            try:
                record_triggers = trigger_per_record.get_group(rec_id).trigger_idx.values
                if self.jitter:
                    record_triggers = np.unique(np.concatenate([record_triggers + j for j in list(range(-self.jitter, self.jitter + 1))]))
                candidate_false_trigger_idx = np.delete(np.arange(len(self.data[rec['filename']])),record_triggers)
            except:
                pass
            candidate_false_trigger_idx = candidate_false_trigger_idx[(candidate_false_trigger_idx > WIN_LEN) & (candidate_false_trigger_idx < rec_len - WIN_LEN)]
            selected_false_trigger_idx = np.random.choice(candidate_false_trigger_idx, n_false_triggers_per_record, replace=False)
            self.triggers = pd.concat([self.triggers, pd.DataFrame(selected_false_trigger_idx, columns=['trigger_idx']).assign(**{"record_id":rec_id, "label":0})])
        
        self.triggers = self.triggers.sort_values(['record_id', 'trigger_idx']).reset_index(drop=True)
```

That script on my machine takes 8.5 sec.
If I comment out the out the very last line or any one of the two imports, the latency disappears.

**Comment by erictraut** [comment]
Great! I'm able to repro the problem locally. I'll investigate further.

**Comment by ilouzl** [comment]
> Also, the times that you're reporting here (15s) are long, but they are nowhere near what your log message indicated (124.7s).

The 124 sec analysis happened when I open another python script that imports the one that I shared above (before the reduction).

**Comment by erictraut** [comment]
Here's a simplified sample that exhibits the problem:

```python
from pandas import concat, DataFrame
from numpy import unique, delete, arange
from numpy.random import choice

class ClassA:
    def method1(self):
        t1 = self.g1
        for _ in []:
            c1 = arange(0)
            try:
                r1 = t1.g
                if 1 < 1:
                    r1 = unique([r1])
                c1 = delete(arange(1), r1)
            except:
                pass
            s1 = choice(c1, 1)
            self.g1 = concat([self.g1, DataFrame(s1)])
```

**Comment by bschnurr** [comment]
@ilouzl  for now just add some annotations to your 'self.foo' member variables.

**Comment by erictraut** [comment]
This will be addressed in the next release.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.1.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023111-4-January-2023-PreRelease)

**Comment by ilouzl** [comment]
Thanks, you are awesome!

**Comment by haowang5128** [comment]
This issue is back with  pylance version v2023.1.40 (or any other versions after v2023.1.20) :(

**Comment by erictraut** [comment]
Yes, I needed to back out the previous change because it introduced a regression. There is an open issue in the pyright issue tracker: https://github.com/microsoft/pyright/issues/4231.

**Comment by ilouzl** [comment]
It seems lile the issue is now fixed with [2023.2.20](https://github.com/microsoft/pylance-release/tree/2023.2.20)
