### ISSUE TITLE
Docstring not working in Python

### ISSUE THREAD

**Issue by dlefcoe** [microsoft/pylance-release#4377]
Type: <b>Bug</b>

# Behaviour
The issue is reported here but was closed as it is deemed to be python related.

Docstring not working in Python #181602
https://github.com/microsoft/vscode/issues/181602

## Expected vs. Actual
docstring does not have line breaks when parenthesis is used. Particularly notied in the "args" part of a docstring where there are multiple lines with multiple args.

The issue is also here:
https://stackoverflow.com/questions/76172407/docstring-not-working-in-python-on-vs-code

XXX

## Steps to reproduce:

1.  write and standard docstring **that contains parenthesis** and then hover over the function to observe the formatting of the docstring.
2. compare this to the expected formatting given by print(my_function.__doc__).

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.4
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• enabled: false

```

</p>
</details>

Extension version: 2023.8.0
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (0.70GB free)|
|Process Argv|--crash-reporter-id 2c246bab-cf0c-4e3f-b959-8571c0ced585|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixshowwlkth:30730052
pythongtdpath:30739704

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue.

This should be a dupe of #4317 which was fixed last in last week's prerelease. The fix for that should ship in this week's stable version.

The docstring format in the stack overflow description is slightly different though. It has the types after the colon:

```python
def function(a: str, b:bool, c:int):
    ''' the function doc string. 
    Here is a bit more.
    
    args:
        a: (str) a random string goes here
        b: (bool) lets describe something binary
        c: (int) we have a whole number

    return:
        gives something back


    '''
    
    a = a + ' world'
    b = 5 * b
    c = 10 + c


    return c
```

We support the types before the colon like so (which is the normal google doc format):

```
def function(a: str, b:bool, c:int):
    ''' the function doc string. 
    Here is a bit more.
    
    args:
        a (str): a random string goes here
        b (bool): lets describe something binary
        c (int): we have a whole number

    return:
        gives something back


    '''
    
    a = a + ' world'
    b = 5 * b
    c = 10 + c


    return c
```

**Comment by dlefcoe** [comment]
This is not fixed and does not work with the google doc format of brackets before the colon.
Please see the image.
I am using vs code version 1.78.2

![image](https://github.com/microsoft/pylance-release/assets/17166744/e8743fc4-4143-4343-a12d-8b3dc8e507fa)

Please re-open.

**Comment by dlefcoe** [comment]
And here is the reproduced example of the same failure with the example code provided...

![image](https://github.com/microsoft/pylance-release/assets/17166744/e634daa2-4a7a-4a0d-90f7-125864848d49)

**Comment by rchiodo** [comment]
What's your version of the Pylance extension? This was fixed in 2023.5.21. Which is our latest prerelease.

**Comment by dlefcoe** [comment]
My pylance version is:  v2023.5.20
I will try to get the newer version and confirm.

**Comment by dlefcoe** [comment]
I do not see a new version available.
The latest version is v2023.5.20.

When are users able to see the newer version please ?

**Comment by rchiodo** [comment]
It's a prelease version. It should be installed by clicking this button here:

![image](https://github.com/microsoft/pylance-release/assets/19672699/c825440d-9db6-4a92-a0e0-8bf62ca60ad9)

**Comment by dlefcoe** [comment]
confirmed this works.  I should also say thank you as the docstring is a rather useful tool. So thank you (the team) kindly for fixing it.

**Comment by dlefcoe** [comment]
I should ask one thing which is this.  Surely the docstring should "exactly" replicate the docstring that one sees when doing `print(function.__doc__)`. Or is that not the case ?

ie.  the position of the brackets before or after the colon should be irrelevant if they are irrelevant for the above.

**Comment by rchiodo** [comment]
> I should ask one thing which is this. Surely the docstring should "exactly" replicate the docstring that one sees when doing print(function.__doc__). Or is that not the case ?

The docstring has to be converted to markdown. Hover text in VS code uses Markdown.  For example, we have to remove the spaces at the front. Line feeds are removed when possible so that the Markdown renderer can fit it into the hover window. (It doesn't always have the same number of columns as your editor)

**Comment by rchiodo** [comment]
Seems like we can probably assume for user code at least that it would have the same number of columns? For 3rd party libraries we can't guess how wide the user's original screen was compared to what VS code is currently showing, but might it be safe to assume that for the user's current code? 

Or maybe we have some setting that forces a cutoff for length of hover strings?

**Comment by dlefcoe** [comment]
Interesting.  I thought it might have been markdown related (because hover text is markdown).  I suppose it would be logical (for python) that a fixed width of 80 (basically PEP8) might be used initially for a cutoff length.

Assuming that you agree that this is logical and consistent.

**Comment by rchiodo** [comment]
I added this issue to potentially handle your suggestion:
https://github.com/microsoft/pylance-release/issues/4379
