### ISSUE TITLE
Pylance reports "reportUnusedImport" for symbols imported in __init__.py

### ISSUE THREAD

**Issue by Carsten-Leue** [microsoft/pylance-release#446]
## Environment data

-   Language Server version: Pylance language server 2020.9.7 (pyright a0620921)
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.6

## Expected behaviour

In my `__init__.py` file of a package I have this:
```
from typing import Tuple
from ._internal.async_di_context_impl import create_async_di_container
from ._internal.async_provider_impl import create_async_provider_definition

#: python nonsense
__all__: Tuple[str, ...] = (
    'create_async_di_container',
    'create_async_provider_definition'
)
```

I expect this not to show errors or warnings despite the symbols being unused. They are imported because they are re-exported by the package via the `__all__` variable.

## Actual behaviour

The import lines report a `reportUnusedImport` error.

![image](https://user-images.githubusercontent.com/55989662/94855387-bcf34b80-042e-11eb-9701-8ff6735be459.png)

![image](https://user-images.githubusercontent.com/55989662/94855486-e2805500-042e-11eb-9ae4-1d534eaab359.png)

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.10.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020100-7-october-2020

**Comment by tylerlaprade** [comment]
@jakebailey/@erictraut, I don't see any notes about this is the linked changelog. I also still experience this bug (although I just have imports, no `__all__`.)
