### ISSUE TITLE
Pylance crashing on Jupyter Notebook Cell Deletion

### ISSUE THREAD

**Issue by justinmahendra** [microsoft/pylance-release#4685]
## Environment data

-   Language Server version: v2023.8.10
-   OS and version: Windows 10 22H2 OS Build 22621.1992
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.4

## Repro Steps
1. Add 2 new empty cells in Jupyter Notebook or Deleting any other cells in between cells. Deleting one would not instantly crash, but deleting another one will
2. Proceed to delete the first created cell, then delete the second one (top to bottom). Deleting from bottom to top in order does not crash the server
3. Crashed

## Expected behavior

1. Not crashing. Issue has been posted before in another report #4077, but this crash in reopen, not crashing the linting server

## Logs

```
Error: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths:
    at _0x598038 (c:\Users\leejieun\.vscode\extensions\ms-python.vscode-pylance-2023.8.11\dist\server.bundle.js:1:897913)
    at c:\Users\leejieun\.vscode\extensions\ms-python.vscode-pylance-2023.8.11\dist\server.bundle.js:1:905158
    at _0x547bdc.<computed> (c:\Users\leejieun\.vscode\extensions\ms-python.vscode-pylance-2023.8.11\dist\server.bundle.js:1:905190)
    at _0x3822ba._onDidChangeNotebookDocumentAsync (c:\Users\leejieun\.vscode\extensions\ms-python.vscode-pylance-2023.8.11\dist\server.bundle.js:1:884105)
```

**Comment by justinmahendra** [comment]
Downgrading to v2023.7.40 seems to have solved the issue. Bug maybe introduced in new version?

**Comment by rchiodo** [comment]
Can somebody post a gif of it happening? I cannot seem to reproduce the problem:

![deletecells](https://github.com/microsoft/pylance-release/assets/19672699/61e8e63d-3a96-40be-a56e-0c741389653c)

**Comment by justinmahendra** [comment]
![bug_recording](https://github.com/microsoft/pylance-release/assets/60601243/d56406ce-441e-4adb-9302-3e44ba8dfd43)
Here's whats happening in my computer.

**Comment by rchiodo** [comment]
Did you reorder any cells or put anything in the notebook before adding the 3? extra cells at the bottom? No matter how many cells or where I put them, I can't get it to crash. But maybe reordering first is necessary.

**Comment by justinmahendra** [comment]
Freshly opened vscode using reload window, then added the cells. Just happen to me on this particular version. I can try using venv to follow your gif there. Might followup in 12 hours

**Comment by justinmahendra** [comment]
I think i tried waiting a few seconds before deleting another cell. Still broke the server though. But deleting from bottom to top in order seems fine.

**Comment by Xavi422** [comment]
> Did you reorder any cells or put anything in the notebook before adding the 3? extra cells at the bottom? No matter how many cells or where I put them, I can't get it to crash. But maybe reordering first is necessary.

I'm getting a similar issue when deleting cells in Jupyter notebook. See my post here for a video:

https://github.com/microsoft/vscode/issues/189645#issuecomment-1665838880

I get the same error "Error: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths"

**Comment by Xavi422** [comment]
Note: Downgrading to v2023.7.40 doesn't solve the issue for me.

Instead I had to downgrade Pylance to version 2023.6.10 **and** downgrade Jupyter to version 2023.6.1101941928

**Comment by rchiodo** [comment]
We really need a way to repro the problem. Nobody in house can seem to reproduce the issue. Does it happen no matter the notebook?

**Comment by rchiodo** [comment]
Yeah I still can't repro. Doesn't matter where I create a cell.

**Comment by Xavi422** [comment]
> Yeah I still can't repro. Doesn't matter where I create a cell.

Can you try this?

I used D+D to delete the middle cell and Z to undo the delete

https://github.com/microsoft/pylance-release/assets/94503686/b27f3d95-2cd6-4707-af86-d9688e1f7fd6

**Comment by rchiodo** [comment]
Nope that works fine. Deleting the cell, moving it around, doesn't matter. 

The code that's failing is detecting that we understand all of the cells in the notebook (they get turned into files that reference each other). When the error occurs, one of the cells is set to undefined for some reason.

**Comment by rchiodo** [comment]
Can you try an experimental setting? 

```
 "python.analysis.enableSyncServer": true
```

This changes how we handle LSP messages. That setting forces us to handle one message at a time. The bug here might be we're getting a delete for a notebook cell while we get an edit for a cell and the delete might be deleting a cell we were editing.

Sync server mode should make those two messages happen synchronously.

**Comment by rchiodo** [comment]
Oh, should have said that new mode requires restarting VS code.

**Comment by thierry-bm** [comment]
Not helping on my side. The crash message looks slightly different though : 
```
2023-08-08 15:17:38.324 [info] [Error - 15:17:38] Notification handler 'notebookDocument/didChange' failed with message: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths c:\xxx\zzz.ipynb:pylance-notebook-cell:X53sZmlsZQ==.py
```

**Comment by zachmeador** [comment]
That did make _some_ progress. Autocomplete keeps working now, but objects are underlined as if they don't exist (`reportUndefinedVariable`). And then I'm getting the same log message as tierry-bm.

```
2023-08-08 15:57:35.015 [info] [Error - 3:57:35 PM] Notification handler 'notebookDocument/didChange' failed with message: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths c:\zzz\debug.ipynb:pylance-notebook-cell:W0sZmlsZQ==.py
```

![image](https://github.com/microsoft/pylance-release/assets/12589360/fb0d8755-ad99-4a63-bd0f-4110d44efef6)

![image](https://github.com/microsoft/pylance-release/assets/12589360/7dffcce2-0579-42d1-930d-764cb0e82c1e)

**Comment by rchiodo** [comment]
That probably means the 'crash' for the async server is not crashing the sync server. But the data is still messed up. Meaning it still repros.

**Comment by rchiodo** [comment]
Just to double check, everyone hitting this is using either the latest VS code insiders or VS code stable?

I tried with stable: 1.81
I tried with insiders: 1.82

Thought maybe VS code changed notebook sync messages.

**Comment by zachmeador** [comment]
I’m using stable, but tomorrow I can also try with insiders if that would be useful.

**Comment by rchiodo** [comment]
> I’m using stable, but tomorrow I can also try with insiders if that would be useful.

No, I don't think that matters. I really doubt VS code changed these messages at all. There's some race condition we have in Pylance.

**Comment by JoHof** [comment]
Using stable 1.81, ms-python.vscode-pylance-2023.8.20 on linux machine

notbooks keep crashing with mentioned error message. remote an local. Can reproduce by deleting two cells consecutively.

**Comment by starball5** [comment]
Related on Stack Overflow: [Pylance in VS Code crashes when adding or deleting cells in a Jupyter notebook](https://stackoverflow.com/q/76874235/11107541)

**Comment by lbferreira** [comment]
I'm also with the same problem. I got it after deleting random cells.
Windows 11
VSCode 1.81.1 (stable)
Pylance: v2023.8.21 (pre-release version) (I also had the same problem with previous versions)

![Screenshot 2023-08-10 181408](https://github.com/microsoft/pylance-release/assets/23250372/3bee4af9-1236-4f65-b319-3d5c95dd1938)

**Comment by AndreasGiersch** [comment]
Same problem occuring with

- macOS Ventura 13.0
- VSCode 1.81.0 (universal)
- Python ext: v2023.14.0
- Pylance ext: v2023.8.20

after pylance has fully loaded and e.g. deleting two consecutive code cells. Returns with message "Error: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths" in an instant.

Also tried the experimental setting '"python.analysis.enableSyncServer": true' mentioned above, which resulted in the message "Notification handler 'notebookDocument/didChange' failed with message: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths". However, this time the message did not appear instantaneously, but with a few seconds delay.

Reverting pylance to v2023.7.40 worked for me!

**Comment by lbferreira** [comment]
I tried reverting pylance to v2023.7.40 and so far it's working.

**Comment by matrs** [comment]
Since the august update,  Intellisense breaks for me too, not sure after which particular action, but i'm sure it happens without the need to delete cells (I've experience this for 3 days). Reverting `pylance` to `v2023.7.40` works for me.

**Comment by julian-irwin-tfs** [comment]
Reverting to v2023.7.40 seems to make crashes / intellisense dropout less frequent, but it still happens. Like most of the others here, I'm having a hard time figuring out exactly what triggers the crash / dropout.

**Comment by Newtoniano** [comment]
Actually even just creating and deleting a cell without doing any other action is enough to break pylance for me in some notebook files. I've had these issues for the longest time, although recently it happens more frequently, and I feel like they happen more often when I have multiple python projects open, but it might just be a coincidence.
![image](https://github.com/microsoft/pylance-release/assets/81423796/0061d1ac-d1c0-456a-8952-d5812e53263d)

**Comment by debonte** [comment]
I have confirmed that at least some of these scenarios are fixed by the fix for #4733 which will be included in this week's Pylance prerelease build.

**Comment by debonte** [comment]
A lot of people chimed in on this issue with different ways to hit this assert. I'm hopeful that they are all fixed by the fix for #4733 which was just released in our latest prerelease build, [2023.8.41](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023841-23-August-2023-PreRelease)

Could you please all upgrade to 2023.8.41 and see if your issues are resolved?

**Comment by Xavi422** [comment]
> 

Still isn't working for me; receiving the same "Error: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths" from Pylance output.

This occurs when deleting a cell and then undoing the delete.

**Comment by raaaaaymond** [comment]
Can confirm, still doesn't work for me after upgrading to 2023.8.41. Same error as before (same error as @Xavi422.

**Comment by JoHof** [comment]
Same here, doesn't seem to fix it

**Comment by epistemetrica** [comment]
Updating Pylance to 2023.8.41 actually seems to have fixed the issue for me. I've tried all the things that previously made it crash, and so far I haven't been able to get the problem to repeat. 

Thanks to everyone working on this! I'm very new to coding an I **_need_** the colors :).

**Comment by vlad-bolovaneanu-ase** [comment]
Using 2023.8.41 I get the same error as @Xavi422.

**Comment by matrs** [comment]
Still the same problem with `2023.8.41`

**Comment by debonte** [comment]
Found another repro for this assert, which I'm now investigating.

## Setup
1. Create empty directory
2. Open dir in VS Code
3. Add new empty file `test.py`
4. `Create: New Jupyter Notebook`
5. Add cells. The content is probably irrelevant, aside from having 3+ cells, but here's what I used:
  a. `thing = "thing"`
  b. `thing`
  c. `print(thing)`
  d. <empty>
  e. <empty>
6. Save notebook in the directory as `test.ipynb` 
7. Close both files
8. Close VS Code

## Repro
1. Open dir in VS Code again.
1. Open `test.py`
1. Wait for Pylance to initialize. This may not be necessary.
3. Open `test.ipynb`
4. Delete second-to-last cell
5. Delete last cell

```text
2023-08-25 17:05:08.658 [info] Error: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths c:\temp\temp\4685repro\test.ipynb:pylance-notebook-cell:W1sZmlsZQ==.py
    at _0x35bbe7 (c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1025282)
    at c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1032550
    at _0x114e49.<computed> (c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1032582)
    at _0x4600bc._onDidChangeNotebookDocumentAsync (c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1010710)
```

**Comment by debonte** [comment]
The scenario above will be fixed in our next prerelease build.

**Comment by AWeheid** [comment]
I'm still facing this issue even with prerelease `v2023.8.41 `: 
![image](https://github.com/microsoft/pylance-release/assets/12305610/906dd80c-cc7b-4213-a6b4-3d31823449bc)

Output logs : 
`2023-08-28 21:39:45.397 [info] Error: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths c:\Users\046724\PQinPrompt\test_prompt.ipynb:pylance-notebook-cell:X13sZmlsZQ==.py
    at _0x35bbe7 (c:\Users\046724\.vscode\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1025282)
    at c:\Users\046724\.vscode\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1032550
    at _0x114e49.<computed> (c:\Users\046724\.vscode\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1032582)
    at _0x4600bc._onDidChangeNotebookDocumentAsync (c:\Users\046724\.vscode\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1010710)`

**Comment by debonte** [comment]
> I'm still facing this issue even with prerelease v2023.8.41

Right. We fixed a related bug (#4733) in 2023.8.41. The scenario in [my comment above](https://github.com/microsoft/pylance-release/issues/4685#issuecomment-1694060355) seems closer to what users are reporting in this issue and will be fixed in our next prerelease build. Likely on Wednesday.

**Comment by octave-ati** [comment]
Just posting to confirm that I'm having the exact same issue.

**Comment by JavierRojas14** [comment]
I can confirm that I have the same issue. I downgraded to 2023.7.30 and 2023.7.40, and also switched to pre-release version (2023.8.41) and still the same issue.

**Comment by thehappycheese** [comment]
The whole python linting/autocomplete experience is broken so regularly that it has become embarrassing for me to recommend VS Code to new users. It is always "it should be working today, lets see"

**Comment by octave-ati** [comment]
So since we are Wednesday does the pre release build that will be released today fix this issue?

**Comment by aiden4977** [comment]
Problem seems was fixed after installing Pyright v1.1.325, which claims that have fixed it. 

https://github.com/microsoft/pyright/pull/5854

**Comment by rchiodo** [comment]
There was an additional fix that isn't in Pyright. it's only in pylance at the moment.

**Comment by rchiodo** [comment]
When we ship the next Pylance prerelease, the bug should be fixed. That would be 2023.8.51

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2023.8.51, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023851-30-August-2023-PreRelease)

**Comment by jzazo** [comment]
I am on `v2023.8.51` of pylance and this does not seem to be fixed. I still get white text pretty often on imports. Need to refresh window.

**Comment by debonte** [comment]
> I am on `v2023.8.51` of pylance and this does not seem to be fixed. I still get white text pretty often on imports. Need to refresh window.

@jzazo, after that happens, if you add/delete/reorder a cell, does Pylance crash with an error like the one below? If not, it's a different issue.

```text
2023-08-25 20:20:22.473 [info] Error: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths c:\temp\temp\4685repro_2\test.ipynb:pylance-notebook-cell:W0sZmlsZQ==.py
    at _0x35bbe7 (c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1025282)
    at c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1032550
    at _0x114e49.<computed> (c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1032582)
    at _0x4600bc._onDidChangeNotebookDocumentAsync (c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1010710)
```

**Comment by raaaaaymond** [comment]
Can confirm that upgrading to Pylance 2023.8.51 worked for me. For now. Thank you all for working on this.

**Comment by jzazo** [comment]
I am not using jupyter or interpreted python, I am on a normal python module, and pylance stops working. Yeah, it may happen when I reorder code, is that possible?

**Comment by debonte** [comment]
> I am not using jupyter or interpreted python, I am on a normal python module, and pylance stops working. Yeah, it may happen when I reorder code, is that possible?

@jzazo, the identifying behavior of this issue is the crash. The fact that semantic highlighting stops working just before the crash is a symptom of the underlying problem, but there are many reasons that semantic highlighting could stop working. It's impossible for this crash to occur without opening a notebook. The code where the "Chained file path x doesn't match cellFilePaths" check is performed is only executed when VS Code tells Pylance that a notebook has been opened or modified. 

So what you're seeing is a different issue. Can you please open a new issue?

The only existing issue I found that looked similar is https://github.com/microsoft/pylance-release/issues/4513, but I don't think there's enough detail there yet for us to know if it's the same as your issue. So open a new one and we can always resolve it as a duplicate after investigation if appropriate.

**Comment by jzazo** [comment]
Thanks, I will keep monitoring and report back if I observe it crashes.

**Comment by debonte** [comment]
> Thanks, I will keep monitoring and report back if I observe it crashes.

@jzazo, sorry if I wasn't clear. When the semantic highlighting (colored text) changes to white, which of the following options is true for you? Note that having a notebook "open" does not necessarily mean that it is the active tab that you are typing in. Simply having it open as another tab may be sufficient to cause this issue.

### No notebooks are open 
If you don't have any notebooks open when you see the semantic highlighting (colored text) change to white, then what you are seeing is unrelated to this issue. File a new issue please.

### 1+ notebook is open and adding/deleting/reordering cell _does not cause_ this crash
If you *do* have a notebook open (as an open tab, but not necessarily the active tab) when you see the semantic highlighting (colored text) change to white (in any file), then when that color change occurs, please switch to the open notebook and try adding, deleting, or reordering a cell there. If that doesn't cause the crash I mentioned above, then what you are seeing is unrelated to this issue. File a new issue please.

### 1+ notebook is open and adding/deleting/reordering cell _causes_ this crash
If you see the coloration disappear with a notebook open, and adding/deleting/reordering a cell causes the crash I mentioned above, and you are using 2023.8.51, then what you're seeing *is* related to this issue and we'll need more details on your project and what actions you are taking before the problem occurs.

**Comment by jzazo** [comment]
Thanks @debonte. Yeah, I don't have any notebooks open, so it is an unrelated issue. I will keep monitoring, it doesn't happen as frequently as before.

**Comment by FlorinAndrei** [comment]
I have upgraded today to the `2023.8.51` pre-release version. I have worked all day on a large notebook (dozens of MB file size, due to lots of graphics). Remote session into a Linux machine via the SSH extension.

Syntax highlighting and autocompletion worked flawlessly all day (if a bit slow due to the huge notebook size). No crashes (that I know of).

With recent previous versions, I used to experience a loss of syntax highlighting and autocompletion after a while, that required closing/reopening the notebook. I have never seen any crashes with previous versions (may have occurred, I just never saw them).

I believe the `2023.8.51` pre-release fixes the problems I had.

Thanks @debonte

**Comment by KokollariIlir** [comment]
I am on `v2023.11.11` and this issue is still persisting

```
2023-11-06 10:53:41.635 [info] Error: Debug Failure. Cell path not found for cell vscode-notebook-cell:/c%3A/Users/ilirk/projects/adhoc/movement.ipynb#W6sZmlsZQ%3D%3D
    at _0x5e8922.getNotebookCellPath (c:\Users\ilirk\.vscode\extensions\ms-python.vscode-pylance-2023.11.11\dist\server.bundle.js:1:261668)
    at _0x8f195a.decodeTextDocumentUri (c:\Users\ilirk\.vscode\extensions\ms-python.vscode-pylance-2023.11.11\dist\server.bundle.js:1:230980)
    at _0x45a7e7.onDidCloseTextDocument (c:\Users\ilirk\.vscode\extensions\ms-python.vscode-pylance-2023.11.11\dist\server.bundle.js:1:901599)
    at c:\Users\ilirk\.vscode\extensions\ms-python.vscode-pylance-2023.11.11\dist\pyright.bundle.js:1:1144202
    at c:\Users\ilirk\.vscode\extensions\ms-python.vscode-pylance-2023.11.11\dist\vendor.bundle.js:2:1234062
    at oe (c:\Users\ilirk\.vscode\extensions\ms-python.vscode-pylance-2023.11.11\dist\vendor.bundle.js:2:1234284)
    at c:\Users\ilirk\.vscode\extensions\ms-python.vscode-pylance-2023.11.11\dist\vendor.bundle.js:2:1230224
    at Immediate.<anonymous> (c:\Users\ilirk\.vscode\extensions\ms-python.vscode-pylance-2023.11.11\dist\vendor.bundle.js:2:1230244)
    at processImmediate (node:internal/timers:476:21)

2023-11-06 10:53:41.819 [info] [Error - 10:53:41 AM] Server process exited with code 1.
2023-11-06 10:53:41.826 [info] [Info  - 10:53:41 AM] Connection to server got closed. Server will restart.
2023-11-06 10:53:41.827 [info] true
2023-11-06 10:53:42.959 [info] [Info  - 10:53:42 AM] (11624) Pylance language server 2023.11.11 (pyright 64c9c3ff) starting
2023-11-06 10:53:42.959 [info] [Info  - 10:53:42 AM] (11624) Server root directory: C:\Users\ilirk\.vscode\extensions\ms-python.vscode-pylance-2023.11.11\dist
2023-11-06 10:53:42.960 [info] [Error - 10:53:42 AM] Server initialization failed.
2023-11-06 10:53:42.960 [info]   Message: Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.

----- [29023443aa0953887e4bf9867965fbbfac2b37d3fe3788884a690a80741a1b19]
```

**Comment by NikitiusIvanov** [comment]
The same problem in my jupyter notebook. I used plotly lib to visualization, and after i deleted cell with plot pylance server was crashed

my version: 1.85.0-insider (user setup)
Commit: 9aacac648821b5c9c1a7192ac9d44c50af6fe241
Date: 2023-11-06T05:34:22.485Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by rchiodo** [comment]
The deleting of the cell is actually tracked in a separate issue. This one: https://github.com/microsoft/pylance-release/issues/5071. The fix for that should be in the next prerelease version when we ship it. Otherwise I'd recommend switching to stable.

**Comment by D1mi3** [comment]
> The same problem in my jupyter notebook. I used plotly lib to visualization, and after i deleted cell with plot pylance server was crashed
> 
> my version: 1.85.0-insider (user setup) Commit: 9aacac648821b5c9c1a7192ac9d44c50af6fe241 Date: 2023-11-06T05:34:22.485Z Electron: 25.9.2 ElectronBuildId: 24603566 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Windows_NT x64 10.0.19045

Same problem here, tried several past versions with the server crashing on open, none seems to work.

**Comment by LicoriceLin** [comment]
This issue happens again for my Pylance in version 2023.8.50

**Comment by rchiodo** [comment]
> This issue happens again for my Pylance in version 2023.8.50

@LicoriceLin, If that's your version, you should upgrade. This bug has been fixed since 2023.11.12

**Comment by LicoriceLin** [comment]
> > This issue happens again for my Pylance in version 2023.8.50
> 
> @LicoriceLin, If that's your version, you should upgrade. This bug has been fixed since 2023.11.12

Oh thanks! 
I just forgot to turn on auto-update in my new dev-environment.

**Comment by LicoriceLin** [comment]
> > This issue happens again for my Pylance in version 2023.8.50
> 
> @LicoriceLin, If that's your version, you should upgrade. This bug has been fixed since 2023.11.12

Oh I think it's a new issue as update doesn't fix it. And my error log goes like " Received change text document command for closed file":
![image](https://github.com/microsoft/pylance-release/assets/93641868/d00fafc2-afd8-4215-b444-7687a44e00a5)

**Comment by LicoriceLin** [comment]
> > > This issue happens again for my Pylance in version 2023.8.50
> > 
> > 
> > @LicoriceLin, If that's your version, you should upgrade. This bug has been fixed since 2023.11.12
> 
> Oh I think it's a new issue as update doesn't fix it. And my error log goes like " Received change text document command for closed file": ![image](https://private-user-images.githubusercontent.com/93641868/309391739-d00fafc2-afd8-4215-b444-7687a44e00a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMjgwMzksIm5iZiI6MTcwOTMyNzczOSwicGF0aCI6Ii85MzY0MTg2OC8zMDkzOTE3MzktZDAwZmFmYzItYWZkOC00MjE1LWI0NDQtNzY4N2E0NGUwMGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDIxMTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYWNkZTFkYTcyMDE5YzgyYWEyNDlkODI3MjljZWQ2YTdmZGY2MzkyYmQxMmY5MGRjMzg4MzRiMWU3NjJhNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vu-yxlUk8k-Y1RkLgnrdGHLkWuWHbQZmX1qDrsNUNNE)

In my situation any change to jupyter codes, even if it's in the existent blocks, will make pylance crash

**Comment by rchiodo** [comment]
That sounds like this problem then:
https://github.com/microsoft/pylance-release/issues/5543

Which looks to be an issue with VS code:
https://github.com/microsoft/vscode/issues/206487

If you downgrade VS code to 1.86.2, the problem should go away.

**Comment by 2blo** [comment]
having this problem right now on ![Image](https://github.com/user-attachments/assets/43ceca04-895a-4ba0-9eac-0f6147825f45)

**Comment by rchiodo** [comment]
@2blo please open a new issue with the contents of the output log. It should give us a callstack of where the problem occurred.
