### ISSUE TITLE
Newbie Help: pcinput issue

### ISSUE THREAD

**Issue by hamzarehan68** [microsoft/pylance-release#4898]
I tried importing "pcinput" and to use "getInteger" from it , but it is not working. Everyitme I try to type "from pcinput import ..." there is a line underneath it and when I hover it it says "(Import pcinput could not be resolvedPylance[reportMissingImports])".
I have done the necessary steps like placing the pcinput.py file in the same folder as I am using the file in but to no avail. I tried doing import sys thing but to no avail. Can anyone help? Attached are pictures for reference.

![2](https://github.com/microsoft/pylance-release/assets/146377688/a2ba2f6a-cef1-4bd8-bc94-9069aa64d17e)
![pcinput](https://github.com/microsoft/pylance-release/assets/146377688/30fca7e9-cf77-4514-ba25-e7dd8a28d18a)
![1](https://github.com/microsoft/pylance-release/assets/146377688/6a54c2b4-8567-48af-8686-2309f1d75a62)

**Comment by rchiodo** [comment]
This should actually be fixed now. It was a bug introduced in version 2023.9.10. It's fixed in 2023.9.31

**Comment by hamzarehan68** [comment]
I have the latest version of Python, and it is still not working. I downloaded this in 1st week of September. I tried updating it but still does not work... I am using VSC is there a different way to update Python there?  

![4](https://github.com/microsoft/pylance-release/assets/146377688/61e329fe-91c7-48c4-a75d-5cac43e64297)

**Comment by hamzarehan68** [comment]
Done thanks!

**Comment by hamzarehan68** [comment]
It actually was a problem, that my folder was not open in the workspace to the left. There was no problem with the version as I had the latest one.

![7](https://github.com/microsoft/pylance-release/assets/146377688/ef048fc1-891d-4e6a-844d-ea5fe71aaef9)
