### ISSUE TITLE
Pylance crashed immediately after open VSCode

### ISSUE THREAD

**Issue by XJTLUmedia** [microsoft/pylance-release#5009]
## Environment data

-   Language Server version: v2023.10.41
-   OS and version: Windows_NT x64 10.0
-   VSCode Version: 1.84.0-insider
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.5

## Code Snippet

```
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.plotting import lag_plot
import statsmodels.api as sm
from statsmodels.compat import lzip
sns.set_style("darkgrid")
plt.rc("figure", figsize=(16, 6))
plt.rc("savefig", dpi=90)
plt.rc("font", family="sans-serif")
plt.rc("font", size=14)
```

Note: this is just a sample notebook, however, in any python/ipython files opened with this VSCode, the results are the same 

## Repro Steps

1. When opening VSCode, the pylance will crash

## Expected behavior

Pylance should not crash

## Actual behavior

Pylance crash

## Logs

```
2023-10-26 09:39:31.505 [info] TypeError: _0x3a4bf3[(_0xb0a014(...) + _0xb0a014(...))] is not a function
    at _0x186756.dirExistsCached (c:\Users\ASUS\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.41\dist\server.bundle.js:1:779292)
    at _0x186756._resolveAbsoluteImport (c:\Users\ASUS\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.41\dist\pyright.bundle.js:1:303694)
    at _0x186756.resolveAbsoluteImport (c:\Users\ASUS\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.41\dist\pyright.bundle.js:1:296859)
    at _0x186756._resolveBestAbsoluteImport (c:\Users\ASUS\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.41\dist\pyright.bundle.js:1:305905)
    at _0x186756._resolveImportStrict (c:\Users\ASUS\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.41\dist\pyright.bundle.js:1:299332)
    at _0x186756.resolveImportInternal (c:\Users\ASUS\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.41\dist\pyright.bundle.js:1:294521)
    at _0x186756.resolveImport (c:\Users\ASUS\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.41\dist\pyright.bundle.js:1:290200)
    at _0x186756.resolveImport (c:\Users\ASUS\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.41\dist\server.bundle.js:1:775260)
    at _0x5a1281.<computed> (c:\Users\ASUS\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.41\dist\server.bundle.js:1:149880)
    at _0x1b11ed._enableJinjaTelemetry (c:\Users\ASUS\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.41\dist\server.bundle.js:1:954757)
    at _0x1b11ed.updateSettingsForWorkspace (c:\Users\ASUS\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.41\dist\server.bundle.js:1:896870)
    at async Promise.all (index 0)

2023-10-26 09:39:31.511 [info] [Error - 9:39:31 AM] Server process exited with code 1.
2023-10-26 09:39:31.512 [info] [Error - 9:39:31 AM] The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

```

**Comment by danieleldjarn** [comment]
Getting the same error

**Comment by d0gkiller87** [comment]
Ran into the same problem on Pylance v2023.10.50 and it seems to be due to some sort of corrupted cache?
I renamed my workspace directory to a different name and it's no longer crashing.
It would be helpful to know how to reset the cache in case something like this happens.

**Comment by rchiodo** [comment]
My cache would be here:
C:\Users\rchiodo\.vscode\extensions\ms-python.vscode-pylance-2023.10.41\dist\.cache (the dist/.cache folder wherever the extension is installed)

Worth a try to see if somehow that's breaking things, but the callstack on the original poster isn't indicating a read from the cache. So we're not sure what's happening.

**Comment by d0gkiller87** [comment]
Ran into the same error on Python 3.8.10, Pylance v2023.10.50.

> Worth a try to see if somehow that's breaking things, but the callstack on the original poster isn't indicating a read from the cache. So we're not sure what's happening.
I removed my falsely concluded comment about how renaming workspace fixes it. Turned out it was due to that VSCode selected another Python interpreter on my system (3.11.4) by default, which Pylance runs fine with.

**Comment by rchiodo** [comment]
Hmm, the failure indicates the return value of statSync (which is a call into the node fs library eventually) is not returning the correct type of object. This might happen if the site-packages folder has a zip/egg. Which might explain how it works in one environment and not another.

The weird part is we haven't changed that code in a long time, so not sure how it would have worked before. 6 months ago was the last update.

**Comment by nosas** [comment]
Similar issue, although mine "restarts" instead of stopping. Pylance was working fine all day up until 2 hours ago:

```
2023-10-27 00:06:17.465 [info] TypeError: _0x2f33cc[(_0x1efd68(...) + _0x1efd68(...))] is not a function
    at _0xa6e677.dirExistsCached (/home/sason/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:902382)
    at _0xa6e677._resolveAbsoluteImport (/home/sason/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:303694)
    at _0xa6e677.resolveAbsoluteImport (/home/sason/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:296859)
    at _0xa6e677._resolveBestAbsoluteImport (/home/sason/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:305693)
    at _0xa6e677._resolveImportStrict (/home/sason/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:299332)
    at _0xa6e677.resolveImportInternal (/home/sason/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:294521)
    at _0xa6e677.resolveImport (/home/sason/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:290200)
    at _0xa6e677.resolveImport (/home/sason/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:898287)
    at _0x170d92.<computed> (/home/sason/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:272928)
    at _0x5e13d0._enableJinjaTelemetry (/home/sason/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:1078110)
    at _0x5e13d0.updateSettingsForWorkspace (/home/sason/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:1019982)
    at async Promise.all (index 0)

2023-10-27 00:06:17.503 [info] [Info  - 12:06:17 AM] Connection to server got closed. Server will restart.
2023-10-27 00:06:17.503 [info] true
2023-10-27 00:06:17.942 [info] [Info  - 12:06:17 AM] (10539) Pylance language server 2023.10.50 (pyright cfe56bfb) starting
2023-10-27 00:06:17.942 [info] [Info  - 12:06:17 AM] (10539) Server root directory: /home/sason/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist
```

**Comment by darynwhite** [comment]
This is happening for me as well, and I ensured it isn't anything else by removing all extensions and reinstalling. Here is a complete log of what happened after my last window reload:

```log
2023-10-26 17:28:01.401 [info] [Error - 5:28:01 PM] Server process exited with code 1.
2023-10-26 17:28:01.402 [info] [Error - 5:28:01 PM] The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

##### Complete output: `Python Language Server`
[Python Language Server.log](https://github.com/microsoft/pylance-release/files/13183865/Python.Language.Server.log)


</details>

**Comment by COOLIRON2311** [comment]
Same error for me.
Can be fixed by rolling back the extension to `v2023.10.40`.

### Environment data
Language Server version: v2023.10.50
OS and version: Windows 11 23H2
VSCode Version: 1.83.1

**Comment by XJTLUmedia** [comment]
> Hmm, the failure indicates the return value of statSync (which is a call into the node fs library eventually) is not returning the correct type of object. This might happen if the site-packages folder has a zip/egg. Which might explain how it works in one environment and not another.
> 
> The weird part is we haven't changed that code in a long time, so not sure how it would have worked before. 6 months ago was the last update.

I checked my site-package folder, I do have egg in that folder.

**Comment by WitherZuo** [comment]
me too, even if a simple python file...I use miniconda (Python 3.11.5, base environment).  

For me, temporarily fixed by rolling back the extension to v2023.10.40 too.

![QQ截图20231027101519](https://github.com/microsoft/pylance-release/assets/25317916/f4376a0a-0a78-4548-a32c-a369609df605)

```
分析文件“C:\Users\withe\Downloads\waifu2x\process.py”时发生内部错误:TypeError: _0x2f33cc[(_0x1efd68(...) + _0x1efd68(...))] is not a function
    at _0xa6e677.dirExistsCached (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:902382)
    at _0xa6e677._resolveAbsoluteImport (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:303694)
    at _0xa6e677.resolveAbsoluteImport (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:296859)
    at _0xa6e677._resolveBestAbsoluteImport (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:305905)
    at _0xa6e677._resolveImportStrict (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:299332)
    at _0xa6e677.resolveImportInternal (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:294521)
    at _0xa6e677.resolveImport (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:290200)
    at _0xa6e677.resolveImport (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:898287)
    at i (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:510945)
    at _0x4c3a07._resolveImports (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:511197)
    at c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:499381
    at a.timeOperation (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:1130032)
    at c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:499348
    at t.LogTracker.log (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:1092230)
    at _0x4c3a07.parse (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:498098)
    at N._parseFile (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:434006)
    at N._bindFile (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:434964)
    at c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:436150
    at t.LogTracker.log (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:1092230)
    at N._checkTypes (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:435861)
    at c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:420596
    at runWithCancellationToken (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:843404)
    at a.timeOperation (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:1130032)
    at N._runEvaluatorWithCancellationToken (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:426484)
    at N.analyze (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:420355)
    at t.analyzeProgram (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:923)
    at _0x79f29.handleResumeAnalysis (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:1021122)
    at _0x79f29.handleAnalyze (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:1021046)
    at _0x79f29.handleAnalyze (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:139271)
    at _0x79f29.onMessage (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:1018726)
    at _0x79f29.onMessage (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:138679)
    at _0x79f29._onMessageWrapper (c:\Users\withe\Downloads\vscode\data\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:1023516)
```  

```  
版本: 1.83.1
提交: f1b07bd25dfad64b0167beb15359ae573aecd2cc
日期: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.25982
```

**Comment by debonte** [comment]
Thanks all. We're able to repro this and are working on a fix.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.10.53, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231053-27-October-2023-PreRelease)

**Comment by darynwhite** [comment]
This didn't seem to fix it for my system. Any steps I should take after installing the `2023.10.53` version?

<img width="472" alt="Screenshot 2023-10-27 at 14 07 30" src="https://github.com/microsoft/pylance-release/assets/40304663/1038685a-b205-477c-8ab4-5ac52d2deb2f">

**Comment by debonte** [comment]
@darynwhite, based on your log above it looks like you're hitting a different error. Is this still what you're seeing? If so, can you open a new issue? And provide some details on your setup so we can try to repro this ourselves? Do you hit this with notebooks or normal python files? Are you using a remote environment of some sort -- WSL, SSH, dev concontainer, etc?

```text
2023-10-26 17:28:01.397 [info] Error: [UriError]: Scheme contains illegal characters.
    at l (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/vendor.bundle.js:2:1390846)
    at t (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/vendor.bundle.js:2:1391782)
    at new t (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/vendor.bundle.js:2:1393374)
    at Function.t.parse (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/vendor.bundle.js:2:1392677)
    at v (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:1099841)
    at w (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:1101719)
    at A (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:1101778)
    at /Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:1481888
    at Array.filter (<anonymous>)
    at o.readdirEntriesSync (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:1481840)
    at _0x311974.readdirEntriesSync (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/server.bundle.js:1:216358)
    at c (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:456960)
    at I.ensureDefaultExtraPaths (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:1064461)
    at k._getConfigOptions (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:472865)
    at k.setOptions (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:466884)
    at Function.runWithOptions (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:1165679)
    at _0x5ca583.updateOptionsAndRestartService (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:1143165)
    at _0x5ca583.updateSettingsForWorkspace (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:1142932)
    at _0x5ca583.updateSettingsForWorkspace (/Users/white/.vscode/extensions/ms-python.vscode-pylance-2023.10.52/dist/server.bundle.js:1:877024)
    at async Promise.all (index 0)
```

**Comment by darynwhite** [comment]
That is what I'm seeing, I'll open new issue based on what I'm seeing.

**Comment by ajromanelli** [comment]
I had the same issue, reverting to the .40 released fixed it

**Comment by wakusoftware** [comment]
same issue for me

**Comment by kaern** [comment]
I had the same issue: 
2023-11-02 08:22:44.224 [info] [Error - 8:22:44 AM] Server process exited with code 1.
2023-11-02 08:22:44.224 [info] TypeError: _0x2f33cc[(_0x1efd68(...) + _0x1efd68(...))] is not a function
even with .40 it seems to work, but language server indicate some error: 
2023-11-02 08:26:20.470 [info] ERROR: The process "27548" not found.
reverting to .30 and no errors ..

**Comment by HenraL** [comment]
I have the same issue with the latest version of pylance:
2023-11-02 12:04:19.744 [info] [Error - 12:04:19 PM] Server process exited with code 1.
2023-11-02 12:04:19.744 [info] TypeError: _0x2f33cc[(_0x1efd68(...) + _0x1efd68(...))] is not a function
    at _0xa6e677.dirExistsCached (c:\Users\Henry_PC\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:902382)
    at _0xa6e677._resolveAbsoluteImport (c:\Users\Henry_PC\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:303694)
    at _0xa6e677.resolveAbsoluteImport (c:\Users\Henry_PC\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:296859)
    at _0xa6e677._resolveBestAbsoluteImport (c:\Users\Henry_PC\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:305905)
    at _0xa6e677._resolveImportStrict (c:\Users\Henry_PC\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:299332)
    at _0xa6e677.resolveImportInternal (c:\Users\Henry_PC\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:294521)
    at _0xa6e677.resolveImport (c:\Users\Henry_PC\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:290200)
    at _0xa6e677.resolveImport (c:\Users\Henry_PC\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:898287)
    at _0x170d92.<computed> (c:\Users\Henry_PC\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:272928)
    at _0x5e13d0._enableJinjaTelemetry (c:\Users\Henry_PC\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:1078110)
    at _0x5e13d0.updateSettingsForWorkspace (c:\Users\Henry_PC\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:1019982)
    at async Promise.all (index 0)

2023-11-02 12:04:19.748 [info] [Error - 12:04:19 PM] The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

**Comment by debonte** [comment]
Just restating that this issue is fixed in our latest prerelease build -- 2023.10.53.

cc: @ajromanelli, @wakusoftware, @kaern, @HenraL

**Comment by HenraL** [comment]
How long does ir take for vscode to see the new version? Because currently, the latest version for them is v2023.10.50.

**Comment by debonte** [comment]
> Edit: sorry, didn't see that we needed to switch to pre-release

Here's a screenshot of that UI if others are having trouble finding it:

![image](https://github.com/microsoft/pylance-release/assets/12820898/ddfc48a9-87da-48e3-8853-5bb9ce132d5f)

**Comment by RisingLiberty** [comment]
After using the pre-release version the language server errors out as soon as there's a change made to the file,
is this a known issue?
![image](https://github.com/microsoft/pylance-release/assets/26844119/9bd51bb0-fc4c-4581-bfaa-704a7003a507)

The line marked with a red arrow is a new line I've added

**Comment by rchiodo** [comment]
@RisingLiberty what's the error message that Pylance is giving?

**Comment by RisingLiberty** [comment]
It doesn't print anything to the console actually, the only thing I see at the end of a restart is the following
2023-11-02 17:06:35.630 [info] ERROR: The process "27076" not found.

there's also an error about a redundant open text document command for the file I'm editing, but I assume that's just warning?

after I've changed the file, notthing else gets emitted to the output console in vscode

**Comment by rchiodo** [comment]
hmm, Does hover over say 'print' work?

**Comment by RisingLiberty** [comment]
yep, print works
![image](https://github.com/microsoft/pylance-release/assets/26844119/7d588937-b98b-4247-be03-4022fc95bc67)

not sure if it helps but the code above the changed lines still highlights as expected, it's only the new code and the lines below that gets messed up.

In there I've found a few references like this
2023-11-02 17:25:23.734 [info] [Info  - 5:25:23 PM] (31408)   Attempting to resolve using root path '<my\user\path>\.vscode\extensions\ms-python.vscode-pylance-2023.10.53\dist\typeshed-fallback\stdlib'
2023-11-02 17:25:23.734 [info] [Info  - 5:25:23 PM] (31408)   Typeshed path not found
2023-11-02 17:25:23.735 [info] [Info  - 5:25:23 PM] (31408)   Looking for typeshed third-party path
2023-11-02 17:25:23.735 [info] [Info  - 5:25:23 PM] (31408)   Looking for typeshed stubs path
2023-11-02 17:25:23.735 [info] [Info  - 5:25:23 PM] (31408)   Typeshed path not found

**Comment by wakusoftware** [comment]
It updated to prerelease and it worked. Thanks

**Comment by RisingLiberty** [comment]
Alright, no problem, thanks for the help, great stuff :)

**Comment by kaern** [comment]
Everything seems to work fine, but I am also getting some process error (this was not the case with .30): 

2023-11-02 21:57:51.663 [info] [Info  - 9:57:51 PM] (22156) Pylance language server 2023.10.53 (pyright d7012d0d) starting
2023-11-02 21:57:51.665 [info] [Info  - 9:57:51 PM] (22156) Server root directory: C:\Users\xxx\.vscode\extensions\ms-python.vscode-pylance-2023.10.53\dist
2023-11-02 21:57:51.666 [info] [Info  - 9:57:51 PM] (22156) Starting service instance "xxx"
2023-11-02 21:57:51.755 [info] [Info  - 9:57:51 PM] (22156) Setting pythonPath for service "xxx": "\.venv\Scripts\python.exe"
2023-11-02 21:57:51.755 [info] [Info  - 9:57:51 PM] (22156) Setting environmentName for service "xxx": "3.10.11 (.venv venv)"
2023-11-02 21:57:51.796 [info] [Info  - 9:57:51 PM] (22156) Loading pyproject.toml file at \pyproject.toml
2023-11-02 21:57:51.797 [info] [Info  - 9:57:51 PM] (22156) Pyproject file "\pyproject.toml" has no "[tool.pyright]" section.
2023-11-02 21:57:52.011 [info] [Info  - 9:57:52 PM] (22156) Assuming Python version 3.10
2023-11-02 21:57:52.783 [info] [Info  - 9:57:52 PM] (22156) Found 385 source files
2023-11-02 21:57:53.497 [info] ERROR: The process "17036" not found.

2023-11-02 21:57:56.650 [info] [Info  - 9:57:56 PM] (22156) [BG(1)] Long operation: getSemanticTokens full at xxx.py (2834ms)

**Comment by rchiodo** [comment]
That error doesn't matter. It's because we're killing a child process a lot sooner than we used to in 2023.10.30. We should just skip logging the error if it's not found.
