### ISSUE TITLE
New version problem related to jupyter or pylance.

### ISSUE THREAD

**Issue by chinabiue** [microsoft/pylance-release#5066]
After new vscode version 1.83.1 update. I got some problem with vscode:

1. CPU stay high when just open VSCODE with a py file just one code 'import sys'
![1](https://github.com/microsoft/pylance-release/assets/2224440/c0e8156c-6002-45eb-988e-dca34a72547c)

2.  Jupyter cell the Pylance didn't work. You can see in the cell, there is no auto completion works and the import module is showed as white, not green.
![3](https://github.com/microsoft/pylance-release/assets/2224440/43315f9f-3d52-4624-9329-eae4c4321ba4)

3. I am try so hard to solve this problem. I reinstall the whole vscode(delete all setting), and just install below extensions.
![2](https://github.com/microsoft/pylance-release/assets/2224440/6d668665-f8d3-4592-b12f-6005bed784bc)

This make the notebook can notebook canot coding, due to the high CPU usage. Before the update everything was fine.
I also try to create new conda env just for the fresh installation of vscode, still the same.

I post the OUTPUT , if anyone got the problem like this?

I saw something wrong with pylance want to find some PID but failed, and the last line of jupyter OUTPUT even with a typo error:
`21:00:37.039 [warn] Got a non-existent Jupyer Data Dir file:///c%3A/Users/<username>/AppData/Roaming/Python/share/jupyter`

Python language server OUTPUT
```
2023-11-01 21:00:08.148 [info] [Info  - 9:00:08 PM] (552) Pylance language server 2023.10.50 (pyright cfe56bfb) starting
2023-11-01 21:00:08.150 [info] [Info  - 9:00:08 PM] (552) Server root directory: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist
2023-11-01 21:00:08.210 [info] [Info  - 9:00:08 PM] (552) Starting service instance "<default>"
2023-11-01 21:00:08.214 [info] (Client) Jupyter provided interpreter path override: c:\Users\Administrator\miniconda3\envs\jupi\python.exe
2023-11-01 21:00:08.314 [info] (552) No pyproject.toml file found.
2023-11-01 21:00:08.318 [info] [Info  - 9:00:08 PM] (552) Setting pythonPath for service "<default>": "C:\Users\Administrator\miniconda3\python.exe"
2023-11-01 21:00:08.318 [info] [Info  - 9:00:08 PM] (552) Setting environmentName for service "<default>": "3.11.4 (base conda)"
2023-11-01 21:00:08.580 [info] [Info  - 9:00:08 PM] (552) Assuming Python version 3.11
2023-11-01 21:00:08.582 [info] (552) Assuming Python platform Windows
2023-11-01 21:00:08.896 [info] [Info  - 9:00:08 PM] (552) Search paths for <default>
2023-11-01 21:00:08.897 [info] [Info  - 9:00:08 PM] (552)   C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib
2023-11-01 21:00:08.897 [info] [Info  - 9:00:08 PM] (552)   typings
2023-11-01 21:00:08.898 [info] [Info  - 9:00:08 PM] (552)   C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stubs\...
2023-11-01 21:00:08.898 [info] [Info  - 9:00:08 PM] (552)   C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\bundled\stubs
2023-11-01 21:00:08.899 [info] [Info  - 9:00:08 PM] (552)   C:\Users\Administrator\miniconda3\DLLs
2023-11-01 21:00:08.903 [info] [Info  - 9:00:08 PM] (552)   C:\Users\Administrator\miniconda3\Lib
2023-11-01 21:00:08.905 [info] [Info  - 9:00:08 PM] (552)   C:\Users\Administrator\miniconda3
2023-11-01 21:00:08.906 [info] [Info  - 9:00:08 PM] (552)   C:\Users\Administrator\miniconda3\Lib\site-packages
2023-11-01 21:00:08.907 [info] [Info  - 9:00:08 PM] (552) Adding fs watcher for library directories:
 C:\Users\Administrator\miniconda3\DLLs
C:\Users\Administrator\miniconda3\Lib
C:\Users\Administrator\miniconda3
C:\Users\Administrator\miniconda3\Lib\site-packages
2023-11-01 21:00:08.907 [info] (552) Searching for source files
2023-11-01 21:00:08.910 [info] [Info  - 9:00:08 PM] (552) No source files found.
2023-11-01 21:00:08.911 [info] (552) pytest configurations: {"message":"script","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2023-11-01 21:00:08.912 [info] (552) pytest configurations: {"message":"script","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2023-11-01 21:00:09.151 [info] (552) [IDX(FG)] index libraries  (index) ...
2023-11-01 21:00:09.152 [info] (552) [IDX(FG)]   read stdlib indices (103ms)
2023-11-01 21:00:09.170 [info] (552) [IDX(FG)] index libraries  (index) [succeed] (118ms)
2023-11-01 21:00:09.184 [info] (552) Server settings returned for workspace: : {
  "autoSearchPaths": true,
  "disableLanguageServices": false,
  "openFilesOnly": true,
  "useLibraryCodeForTypes": true,
  "watchForSourceChanges": true,
  "watchForLibraryChanges": true,
  "watchForConfigChanges": true,
  "typeCheckingMode": "off",
  "diagnosticSeverityOverrides": {
    "reportShadowedImports": "warning"
  },
  "logLevel": "log",
  "autoImportCompletions": false,
  "includeUserSymbolsInAutoImport": true,
  "indexing": false,
  "completeFunctionParens": false,
  "enableExtractCodeAction": true,
  "indexOptions": {
    "packageDepths": [
      [
        "sklearn",
        2,
        false
      ],
      [
        "matplotlib",
        2,
        false
      ],
      [
        "scipy",
        2,
        false
      ],
      [
        "django",
        2,
        false
      ],
      [
        "flask",
        2,
        false
      ],
      [
        "fastapi",
        2,
        false
      ]
    ],
    "localStoragePath": "",
    "userFileIndexingLimit": 2000
  },
  "variableInlayTypeHints": false,
  "callArgumentNameInlayHints": "off",
  "functionReturnInlayTypeHints": false,
  "pytestParametersInlayTypeHints": false,
  "importFormat": "absolute",
  "fileSpecs": [],
  "excludeFileSpecs": [],
  "ignoreFileSpecs": [],
  "formatOnType": true,
  "taskListTokens": [],
  "addImportExactMatchOnly": false,
  "enablePytestSupport": true,
  "enablePytestExtra": false,
  "gotoDefinitionInStringLiteral": true,
  "remapDiagnostics": false,
  "intelliCodeEnabled": true,
  "pythonPath": "C:\\Users\\Administrator\\miniconda3\\python.exe",
  "pythonEnvironmentName": "3.11.4 (base conda)",
  "fixAll": [],
  "extraCommitChars": true,
  "notebookRunStartupCommands": "",
  "editorIndentConfig": {
    "defaultTabSequence": "    ",
    "tabSize": 4
  }
}
2023-11-01 21:00:09.192 [info] (552) No pyproject.toml file found.
2023-11-01 21:00:09.193 [info] [Info  - 9:00:09 PM] (552) Setting pythonPath for service "<default>": "C:\Users\Administrator\miniconda3\python.exe"
2023-11-01 21:00:09.193 [info] [Info  - 9:00:09 PM] (552) Setting environmentName for service "<default>": "3.11.4 (base conda)"
2023-11-01 21:00:09.511 [info] [Info  - 9:00:09 PM] (552) Assuming Python version 3.11
2023-11-01 21:00:09.512 [info] (552) Assuming Python platform Windows
2023-11-01 21:00:09.775 [info] [Info  - 9:00:09 PM] (552) Search paths for <default>
2023-11-01 21:00:09.776 [info] [Info  - 9:00:09 PM] (552)   C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib
2023-11-01 21:00:09.777 [info] [Info  - 9:00:09 PM] (552)   typings
2023-11-01 21:00:09.777 [info] [Info  - 9:00:09 PM] (552)   C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stubs\...
2023-11-01 21:00:09.778 [info] [Info  - 9:00:09 PM] (552)   C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\bundled\stubs
2023-11-01 21:00:09.778 [info] [Info  - 9:00:09 PM] (552)   C:\Users\Administrator\miniconda3\DLLs
2023-11-01 21:00:09.780 [info] [Info  - 9:00:09 PM] (552)   C:\Users\Administrator\miniconda3\Lib
2023-11-01 21:00:09.782 [info] [Info  - 9:00:09 PM] (552)   C:\Users\Administrator\miniconda3
2023-11-01 21:00:09.782 [info] [Info  - 9:00:09 PM] (552)   C:\Users\Administrator\miniconda3\Lib\site-packages
2023-11-01 21:00:09.783 [info] [Info  - 9:00:09 PM] (552) Adding fs watcher for library directories:
 C:\Users\Administrator\miniconda3\DLLs
C:\Users\Administrator\miniconda3\Lib
C:\Users\Administrator\miniconda3
C:\Users\Administrator\miniconda3\Lib\site-packages
2023-11-01 21:00:09.783 [info] (552) Searching for source files
2023-11-01 21:00:09.784 [info] [Info  - 9:00:09 PM] (552) No source files found.
2023-11-01 21:00:09.784 [info] [Info  - 9:00:09 PM] (552) Starting service instance "<default>"
2023-11-01 21:00:09.787 [info] (552) WorkspaceFactory 0 add <default>:c:\Users\Administrator\miniconda3\envs\jupi\python.exe
2023-11-01 21:00:09.942 [info] (552) [IDX(FG)] index libraries  (index) ...
2023-11-01 21:00:09.943 [info] (552) [IDX(FG)]   read stdlib indices (2ms)
2023-11-01 21:00:09.947 [info] (552) [IDX(FG)] index libraries  (index) [succeed] (7ms)
2023-11-01 21:00:09.951 [info] (552) pytest configurations: {"message":"script","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2023-11-01 21:00:09.989 [info] (552) Server settings returned for workspace: : {
  "autoSearchPaths": true,
  "disableLanguageServices": false,
  "openFilesOnly": true,
  "useLibraryCodeForTypes": true,
  "watchForSourceChanges": true,
  "watchForLibraryChanges": true,
  "watchForConfigChanges": true,
  "typeCheckingMode": "off",
  "diagnosticSeverityOverrides": {
    "reportShadowedImports": "warning"
  },
  "logLevel": "log",
  "autoImportCompletions": false,
  "includeUserSymbolsInAutoImport": true,
  "indexing": false,
  "completeFunctionParens": false,
  "enableExtractCodeAction": true,
  "indexOptions": {
    "packageDepths": [
      [
        "sklearn",
        2,
        false
      ],
      [
        "matplotlib",
        2,
        false
      ],
      [
        "scipy",
        2,
        false
      ],
      [
        "django",
        2,
        false
      ],
      [
        "flask",
        2,
        false
      ],
      [
        "fastapi",
        2,
        false
      ]
    ],
    "localStoragePath": "",
    "userFileIndexingLimit": 2000
  },
  "variableInlayTypeHints": false,
  "callArgumentNameInlayHints": "off",
  "functionReturnInlayTypeHints": false,
  "pytestParametersInlayTypeHints": false,
  "importFormat": "absolute",
  "fileSpecs": [],
  "excludeFileSpecs": [],
  "ignoreFileSpecs": [],
  "formatOnType": true,
  "taskListTokens": [],
  "addImportExactMatchOnly": false,
  "enablePytestSupport": true,
  "enablePytestExtra": false,
  "gotoDefinitionInStringLiteral": true,
  "remapDiagnostics": false,
  "intelliCodeEnabled": true,
  "pythonPath": "C:\\Users\\Administrator\\miniconda3\\python.exe",
  "pythonEnvironmentName": "3.11.4 (base conda)",
  "fixAll": [],
  "extraCommitChars": true,
  "notebookRunStartupCommands": "",
  "editorIndentConfig": {
    "defaultTabSequence": "    ",
    "tabSize": 4
  }
}
2023-11-01 21:00:10.747 [info] ERROR: The process "8660" not found.

2023-11-01 21:00:10.755 [info] (552) No pyproject.toml file found.
2023-11-01 21:00:10.755 [info] [Info  - 9:00:10 PM] (552) Setting pythonPath for service "<default>": "c:\Users\Administrator\miniconda3\envs\jupi\python.exe"
2023-11-01 21:00:10.755 [info] [Info  - 9:00:10 PM] (552) Setting environmentName for service "<default>": "3.11.4 (base conda)"
2023-11-01 21:00:11.004 [info] [Info  - 9:00:11 PM] (552) Assuming Python version 3.10
2023-11-01 21:00:11.004 [info] (552) Assuming Python platform Windows
2023-11-01 21:00:11.400 [info] [Info  - 9:00:11 PM] (552) Search paths for <default>
2023-11-01 21:00:11.401 [info] [Info  - 9:00:11 PM] (552)   C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib
2023-11-01 21:00:11.404 [info] [Info  - 9:00:11 PM] (552)   typings
2023-11-01 21:00:11.405 [info] [Info  - 9:00:11 PM] (552)   C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stubs\...
2023-11-01 21:00:11.407 [info] [Info  - 9:00:11 PM] (552)   C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\bundled\stubs
2023-11-01 21:00:11.408 [info] [Info  - 9:00:11 PM] (552)   C:\Users\Administrator\miniconda3\envs\jupi\DLLs
2023-11-01 21:00:11.409 [info] [Info  - 9:00:11 PM] (552)   C:\Users\Administrator\miniconda3\envs\jupi\Lib
2023-11-01 21:00:11.410 [info] [Info  - 9:00:11 PM] (552)   C:\Users\Administrator\miniconda3\envs\jupi
2023-11-01 21:00:11.410 [info] [Info  - 9:00:11 PM] (552)   C:\Users\Administrator\miniconda3\envs\jupi\Lib\site-packages
2023-11-01 21:00:11.411 [info] [Info  - 9:00:11 PM] (552)   C:\Users\Administrator\miniconda3\envs\jupi\Lib\site-packages\win32
2023-11-01 21:00:11.411 [info] [Info  - 9:00:11 PM] (552)   C:\Users\Administrator\miniconda3\envs\jupi\Lib\site-packages\win32\lib
2023-11-01 21:00:11.411 [info] [Info  - 9:00:11 PM] (552)   C:\Users\Administrator\miniconda3\envs\jupi\Lib\site-packages\pythonwin
2023-11-01 21:00:11.414 [info] [Info  - 9:00:11 PM] (552) Adding fs watcher for library directories:
 C:\Users\Administrator\miniconda3\envs\jupi\DLLs
C:\Users\Administrator\miniconda3\envs\jupi\Lib
C:\Users\Administrator\miniconda3\envs\jupi
C:\Users\Administrator\miniconda3\envs\jupi\Lib\site-packages
C:\Users\Administrator\miniconda3\envs\jupi\Lib\site-packages\win32
C:\Users\Administrator\miniconda3\envs\jupi\Lib\site-packages\win32\lib
C:\Users\Administrator\miniconda3\envs\jupi\Lib\site-packages\pythonwin
2023-11-01 21:00:11.418 [info] (552) Searching for source files
2023-11-01 21:00:11.418 [info] [Info  - 9:00:11 PM] (552) No source files found.
2023-11-01 21:00:11.419 [info] (552) pytest configurations: {"message":"request cancelled","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2023-11-01 21:00:11.618 [info] (552) [FG] parsing: D:\git\up2date\0python\fluent\tempelate.py (190ms)
2023-11-01 21:00:11.931 [info] (552) [FG] parsing: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 5ms] (310ms)
2023-11-01 21:00:12.102 [info] (552) [FG] binding: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\builtins.pyi (166ms)
2023-11-01 21:00:12.104 [info] (552) [FG] binding: D:\git\up2date\0python\fluent\tempelate.py (0ms)
2023-11-01 21:00:12.172 [info] (552) [IDX(FG)] index libraries  (index) ...
2023-11-01 21:00:12.173 [info] (552) [IDX(FG)]   read stdlib indices (2ms)
2023-11-01 21:00:12.177 [info] (552) [IDX(FG)] index libraries  (index) [succeed] (7ms)
2023-11-01 21:00:12.186 [info] (552) pytest configurations: {"message":"request cancelled","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2023-11-01 21:00:12.188 [info] ERROR: The process "4884" not found.

2023-11-01 21:00:12.189 [info] (552) pytest configurations: {"message":"script","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2023-11-01 21:00:12.266 [info] (552) pytest configurations: {"message":"request cancelled","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2023-11-01 21:00:12.506 [info] (552) [BG(1)] analyzing: D:\git\up2date\0python\fluent\tempelate.py ...
2023-11-01 21:00:12.507 [info] (552) [BG(1)]   parsing: D:\git\up2date\0python\fluent\tempelate.py (271ms)
2023-11-01 21:00:12.845 [info] (552) [BG(1)]   parsing: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 9ms] (325ms)
2023-11-01 21:00:13.008 [info] ERROR: The process "5884" not found.

2023-11-01 21:00:13.009 [info] (552) pytest configurations: {"message":"request cancelled","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2023-11-01 21:00:13.012 [info] (552) [BG(1)]   binding: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\builtins.pyi (160ms)
2023-11-01 21:00:13.014 [info] (552) [BG(1)]   binding: D:\git\up2date\0python\fluent\tempelate.py (1ms)
2023-11-01 21:00:13.236 [info] (552) [BG(1)]   checking: D:\git\up2date\0python\fluent\tempelate.py ...
2023-11-01 21:00:13.237 [info] (552) [BG(1)]     parsing: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\typing.pyi [fs read 3ms] (152ms)
2023-11-01 21:00:13.310 [info] (552) [BG(1)]     binding: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\typing.pyi (49ms)
2023-11-01 21:00:13.310 [info] (552) [BG(1)]     parsing: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\typing_extensions.pyi [fs read 0ms] (17ms)
2023-11-01 21:00:13.402 [info] (552) [BG(1)]     binding: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\typing_extensions.pyi (41ms)
2023-11-01 21:00:13.612 [info] Error: ENOENT: no such file or directory, stat 'untitled:/__builtins__'
    at statSync (node:fs:1617:3)
    at Object.t.statSync (node:electron/js2c/asar_bundle:2:4557)
    at c.statSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:978467)
    at makeCallSync.subPath (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:1023397)
    at I.makeCallSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:1032658)
    at I.statSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:1023365)
    at A.statSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:987618)
    at C.statSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:987618)
    at S.statSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:1112371)
    at o.statSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:1479863)
    at _0x4db351.statSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:338358)
    at c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:912670
    at c.handleMessage (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:12500)
    at c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:17939
    at Worker.<anonymous> (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:867160)
    at Worker.emit (node:events:525:35)
    at MessagePort.<anonymous> (node:internal/worker:234:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'untitled:/__builtins__'
}

2023-11-01 21:00:13.613 [info] (552) [BG(1)]     parsing: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi [fs read 0ms] (106ms)
2023-11-01 21:00:13.614 [info] (552) [BG(1)]     binding: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi (4ms)
2023-11-01 21:00:13.614 [info] (552) [BG(1)]     parsing: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\types.pyi [fs read 1ms] (34ms)
2023-11-01 21:00:13.615 [info] (552) [BG(1)]     binding: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\types.pyi (35ms)
2023-11-01 21:00:13.617 [info] Error: ENOENT: no such file or directory, scandir 'untitled:/_'
    at Object.readdirSync (node:fs:1454:3)
    at Object.t.readdirSync (node:electron/js2c/asar_bundle:2:10884)
    at c.readdirSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:983642)
    at makeCallSync.subPath (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:1030866)
    at I.makeCallSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:1032658)
    at I.readdirSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:1030834)
    at A.readdirSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:990800)
    at C.readdirSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:990800)
    at S.readdirEntriesSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:1111976)
    at o.readdirEntriesSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:1479427)
    at _0x4db351.readdirEntriesSync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:337896)
    at c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:912296
    at c.handleMessage (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:12500)
    at c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\vendor.bundle.js:2:17939
    at Worker.<anonymous> (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:867160)
    at Worker.emit (node:events:525:35)
    at MessagePort.<anonymous> (node:internal/worker:234:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'untitled:/_'
}

2023-11-01 21:00:13.672 [info] (552) [BG(1)]     parsing: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\abc.pyi [fs read 0ms] (3ms)
2023-11-01 21:00:13.673 [info] (552) [BG(1)]     binding: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\abc.pyi (1ms)
2023-11-01 21:00:13.755 [info] (552) [BG(1)]     parsing: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\sys.pyi [fs read 0ms] (55ms)
2023-11-01 21:00:13.756 [info] (552) [BG(1)]     binding: C:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\typeshed-fallback\stdlib\sys.pyi (5ms)
2023-11-01 21:00:14.056 [info] (552) [BG(1)]   checking: D:\git\up2date\0python\fluent\tempelate.py (1055ms)
2023-11-01 21:00:14.066 [info] (552) [BG(1)] analyzing: D:\git\up2date\0python\fluent\tempelate.py (1830ms)
2023-11-01 21:00:14.066 [info] (552) [BG(1)] getSemanticTokens full at D:\git\up2date\0python\fluent\tempelate.py (7ms)
2023-11-01 21:00:14.067 [info] (552) [BG(1)] getSemanticTokens range 0:0 - 1:11 at D:\git\up2date\0python\fluent\tempelate.py (1ms)
2023-11-01 21:00:14.098 [info] (552) pytest configurations: {"message":"script","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2023-11-01 21:00:14.106 [info] ERROR: The process "1676" not found.

2023-11-01 21:00:15.083 [info] Error: Debug Failure. False expression: Duplicate path in cellFilePaths
    at _0x47bd3d (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:1082040)
    at c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:1089377
    at _0x4ec48a.<computed> (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:1089409)
    at _0x5e13d0._onDidChangeNotebookDocumentAsync (c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:1070159)
```

Jupyter OUPUT
```
Visual Studio Code (1.83.1, undefined, desktop)
Jupyter Extension Version: 2023.9.1102792234.
Python Extension Version: 2023.18.0.
Platform: win32 (x64).
No workspace folder opened.
20:59:59.457 [info] User belongs to experiment group 'NewJupyterSession'
21:00:00.404 [info] Start refreshing Kernel Picker (1698843600404)
21:00:00.435 [info] Using Pylance
21:00:00.549 [info] End refreshing Kernel Picker (1698843600404)
21:00:00.647 [info] Start refreshing Kernel Picker (1698843600647)
21:00:00.721 [info] Start refreshing Interpreter Kernel Picker
21:00:08.784 [info] End refreshing Kernel Picker (1698843600647)
21:00:11.083 [info] Process Execution: ~\miniconda3\envs\jupi\python.exe -m pip list
21:00:12.663 [info] Process Execution: ~\miniconda3\python.exe -m pip list
21:00:33.750 [info] Handle Execution of Cells 3 for Interactive-1.interactive
21:00:33.755 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0a402d4bba85a5486d21a0aa8751821be17a978a5de584b5df079ca806e7eb63b.~\miniconda3\envs\jupi\python.exe.~\miniconda3\envs\jupi\python.exe.-m#ipykernel_launcher  (Python Path: ~\miniconda3\envs\jupi\python.exe, Conda, jupi, 3.10.9) for 'Interactive-1.interactive' (disableUI=false)
21:00:33.778 [info] Process Execution: ~\miniconda3\envs\jupi\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
21:00:33.908 [info] Process Execution: ~\miniconda3\envs\jupi\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2023.9.1102792234-win32-x64\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 7724
    > cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2023.9.1102792234-win32-x64\pythonFiles\vscode_datascience_helpers
21:00:34.466 [info] Process Execution: ~\miniconda3\envs\jupi\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"b4868f99-fba0-4dea-a53e-97de72aa3665" --shell=9002 --transport="tcp" --iopub=9004 --f=~\AppData\Roaming\jupyter\runtime\kernel-v2-7724tAAelHnTdxuK.json
    > cwd: d:\Program Files\Microsoft VS Code
21:00:34.906 [info] ipykernel version & path 6.15.2, ~\miniconda3\envs\jupi\lib\site-packages\ipykernel\__init__.py for ~\miniconda3\envs\jupi\python.exe
21:00:36.401 [warn] StdErr from Kernel Process ~\miniconda3\envs\jupi\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
21:00:36.402 [warn] StdErr from Kernel Process ~\miniconda3\envs\jupi\lib\site-packages\traitlets\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'b4868f99-fba0-4dea-a53e-97de72aa3665' instead of 'b"b4868f99-fba0-4dea-a53e-97de72aa3665"'.
  warn(
21:00:36.852 [info] Process Execution: ~\miniconda3\envs\jupi\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2023.9.1102792234-win32-x64\pythonFiles\printJupyterDataDir.py
21:00:36.877 [info] Kernel acknowledged execution of cell 3 @ 1698843636876
21:00:36.889 [info] End cell 3 execution @ 1698843636889, started @ 1698843636876, elapsed time = 0.013s
21:00:37.039 [warn] Got a non-existent Jupyer Data Dir file:///c%3A/Users/<username>/AppData/Roaming/Python/share/jupyter
```

**Comment by CoderChen01** [comment]
Go to Definition in Notebook Editor Not Working

Uploading bandicam 2023-11-02 21-51-47-235.mp4…

**Comment by rchiodo** [comment]
@CoderChen01 your issue is a dupe of #5037 that was fixed in 2023.10.53. You can fix your problem by upgrading to the prerelease version.

**Comment by CoderChen01** [comment]
> @CoderChen01 your issue is a dupe of #5037 that was fixed in 2023.10.53. You can fix your problem by upgrading to the prerelease version.

Thank you for your answer, but I switched to 2023.10.53 and the problem still exists. Here is my screen recording.

https://github.com/microsoft/pylance-release/assets/61137732/b25f7334-7d8a-4d4d-8999-5c19467a56e2

**Comment by rchiodo** [comment]
Can you open a new issue then? We'd need the log from the 'Python Language Server' output tab.

**Comment by chinabiue** [comment]
> Go to Definition in Notebook Editor Not Working
> 
> Pylance v2023.10.50 cannot work, but its previous version can work.
> 
> [screen capture](https://drive.google.com/file/d/1pt1SxARfRTUzEUE_-VdqJvVjb_n1jqBv/view?usp=sharing)
> 
> similar as this: [microsoft/vscode-jupyter#9047](https://github.com/microsoft/vscode-jupyter/issues/9047)

Today Pylance release a new version, after install the new version, everything works as before.
I don't know why, during these time I have been trying so hard to solve this issue, I even reisntalled the windows OS of PC. 
But after the update of Pylance, everything back to before.

**Comment by CoderChen01** [comment]
> > Go to Definition in Notebook Editor Not Working
> > Pylance v2023.10.50 cannot work, but its previous version can work.
> > [screen capture](https://drive.google.com/file/d/1pt1SxARfRTUzEUE_-VdqJvVjb_n1jqBv/view?usp=sharing)
> > similar as this: [microsoft/vscode-jupyter#9047](https://github.com/microsoft/vscode-jupyter/issues/9047)
> 
> Today Pylance release a new version, after install the new version, everything works as before. I don't know why, during these time I have been trying so hard to solve this issue, I even reisntalled the windows OS of PC. But after the update of Pylance, everything back to before.

This seems to be the reason: https://github.com/microsoft/pylance-release/issues/5076#issuecomment-1791725244
