### ISSUE TITLE
Type is not callable error using SQLAlchemy's declarative_base

### ISSUE THREAD

**Issue by nirn** [microsoft/pylance-release#507]
## Environment data

-   Language Server version: 2020.10.1
-   OS and version: Windows 10, 2004
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.3

## Expected behaviour

No errors.

## Actual behaviour

Two errors appear:
```
"User" has type "Type[User]" and is not callable
  Type "Type[User]" is not callable Pylance (reportGeneralTypeIssues)
Expected no arguments to "User" constructor Pylance (reportGeneralTypeIssues)
```

## Code Snippet / Additional information

```python
from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class User(Base):
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(255), unique=True, index=True)


user = User(id=1, username='test')
```

![image](https://user-images.githubusercontent.com/16687729/96589476-8605ac80-12ed-11eb-92b4-03dfc7a23ae3.png)

SQLAlchemy's declarative_base should use [this _declarative_constructor](https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/api.html#sqlalchemy.ext.declarative.api._declarative_constructor) by default, which allows initialization from kwargs.
There are no errors for the same snippet using standalone Pyright (1.1.80) without Pylance.

**Comment by erictraut** [comment]
Thanks for the bug report. SqlAlchemy is using a custom metaclass that provides non-standard behaviors for a constructor. I've changed the logic in pylance to avoid emitting this particular error when a class is instantiated from a custom metaclass, so you won't see this false positive in the future.

This fix will be in the next release of pylance.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.10.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020102-21-october-2020

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.10.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020103-28-october-2020

**Comment by aaronkavlie-wf** [comment]
I still get the "Expected no arguments" bug on SQLAlchemy model class initialization.

(running Pylance 2020.11.1)

**Comment by erictraut** [comment]
I just re-verified that the code sample above does not result in any errors. If your code differs from the above, please post a simple example that exhibits the problem.

**Comment by aaronkavlie-wf** [comment]
> I just re-verified that the code sample above does not result in any errors. If your code differs from the above, please post a simple example that exhibits the problem.

Sorry about the trouble Eric, the errors are gone now. I think my workspace just wasn't pointed at my virtualenv's Python interpreter.
