### ISSUE TITLE
Highlighting fails after switching between monorepo projects (when switching python interpreters)

### ISSUE THREAD

**Issue by alita-moore** [microsoft/pylance-release#5995]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Basically, I expect the highlighting on the Jupyter notebook to update when I switch from one project to another. However, when I switch from one project to another it fails to update the highlighting until I either reload the window or I restart the extension host. Note that normal python files highlight just fine.

To reproduce this see the following [codesandbox](https://codesandbox.io/p/devbox/recursing-sea-2wt86c?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx61x6na00072e6f4n01x9p4%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx61x6na00022e6fnkrn5qoa%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx61x6na00042e6fnqqseugb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx61x6na00062e6f5bzyws62%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx61x6na00022e6fnkrn5qoa%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx61x6n900012e6faha7ym17%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clx61x6na00022e6fnkrn5qoa%2522%252C%2522activeTabId%2522%253A%2522clx61x6n900012e6faha7ym17%2522%257D%252C%2522clx61x6na00062e6f5bzyws62%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx61x6na00052e6f82wh4dlc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5000%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clx61x6na00062e6f5bzyws62%2522%252C%2522activeTabId%2522%253A%2522clx61x6na00052e6f82wh4dlc%2522%257D%252C%2522clx61x6na00042e6fnqqseugb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx61x6na00032e6fq5tq4gph%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522clx61x6na00042e6fnqqseugb%2522%252C%2522activeTabId%2522%253A%2522clx61x6na00032e6fq5tq4gph%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

After you've loaded into the codesandbox, open it in vscode. Make sure that you have the following extensions:
1. pylance
2. jupyter
3. python envy (teticio.python-envy)

open "third_project/another_one.ipynb" and select the appropriate .venv which is located at "third_project/.venv". Notice that things are highlighting.
<img width="1300" alt="Screenshot 2024-06-08 at 11 55 42 PM" src="https://github.com/microsoft/vscode-jupyter/assets/26529820/6a9c8b30-6461-40bb-b0a6-8ecc5c25b544">

open other_project/__init__.py

You can also get here by navigating to the definition of the "other_project" module. Notice that python envy changes the interpreter.
<img width="1322" alt="Screenshot 2024-06-08 at 11 58 07 PM" src="https://github.com/microsoft/vscode-jupyter/assets/26529820/66051c1b-cb78-4dc1-9cf7-57f5209f8406">

Now navigate back to the "third_project/another_one.ipynb". If you're "lucky" you'll see that when you scroll down and then back up (to force re-draw the highlihgts) that sometimes it freezes. When it freezes like this it's frozen indefinitely.
<img width="1297" alt="Screenshot 2024-06-09 at 12 01 44 AM" src="https://github.com/microsoft/vscode-jupyter/assets/26529820/d9e31869-cf8e-40e0-8aa1-20735f1f57ff">

NOTE:
1. It may be somewhat difficult to reproduce the results, and you may have to go back and forth between notebooks / files quickly in order to overload the system and then force the behavior. However, note that in larger codebases it happens nearly every time you switch between notebooks / project interpreters.
2. I am using poetry to import from other modules in the monorepo using their relative path importing system

### VS Code Version

1.90.0

### Jupyter Extension Version

v2024.5.0

### Jupyter logs

```shell
Visual Studio Code (1.90.0, ssh-remote, desktop)
Jupyter Extension Version: 2024.5.0.
Python Extension Version: 2024.8.0.
Pylance Extension Version: 2024.6.1.
Platform: linux (x64).
Workspace folder /project/workspace, Home = /root
14:55:37.492 [info] Starting Kernel (Python Path: /project/workspace/third_project/.venv/bin/python, Poetry, 3.8.19) for '/project/workspace/third_project/another_one.ipynb' (disableUI=true)
14:55:38.300 [info] Process Execution: /project/workspace/third_project/.venv/bin/python -m pip list
14:55:38.367 [info] Process Execution: /project/workspace/third_project/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
14:55:38.382 [info] Process Execution: /project/workspace/third_project/.venv/bin/python -m ipykernel_launcher --f=/~/.local/share/jupyter/runtime/kernel-v2-18791fQR1MB8Io0Zd.json
    > cwd: //project/workspace/third_project
14:55:40.250 [info] Kernel successfully started
14:55:40.270 [info] Process Execution: /project/workspace/third_project/.venv/bin/python /~/.vscode-server/extensions/ms-toolsai.jupyter-2024.5.0-linux-x64/pythonFiles/printJupyterDataDir.py
14:58:47.202 [info] Starting Kernel (Python Path: /project/workspace/.venv/bin/python, Poetry, 3.8.19) for '/project/workspace/notebook.ipynb' (disableUI=true)
14:58:48.116 [info] Process Execution: /project/workspace/.venv/bin/python -m pip list
14:58:48.189 [info] Process Execution: /project/workspace/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
14:58:48.206 [info] Process Execution: /project/workspace/.venv/bin/python -m ipykernel_launcher --f=/~/.local/share/jupyter/runtime/kernel-v2-18791DaYZEb5bjEdQ.json
    > cwd: //project/workspace
14:58:50.302 [info] Kernel successfully started
14:58:50.317 [info] Process Execution: /project/workspace/.venv/bin/python /~/.vscode-server/extensions/ms-toolsai.jupyter-2024.5.0-linux-x64/pythonFiles/printJupyterDataDir.py
14:58:57.241 [info] Starting Kernel (Python Path: /project/workspace/other_project/.venv/bin/python, Poetry, 3.8.19) for '/project/workspace/other_project/other.ipynb' (disableUI=true)
14:58:57.949 [info] Process Execution: /project/workspace/other_project/.venv/bin/python -m pip list
14:58:58.162 [info] Process Execution: /project/workspace/other_project/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
14:58:58.192 [info] Process Execution: /project/workspace/other_project/.venv/bin/python -m ipykernel_launcher --f=/~/.local/share/jupyter/runtime/kernel-v2-18791UmM5kZOsfZ8o.json
    > cwd: //project/workspace/other_project
14:59:00.672 [info] Kernel successfully started
14:59:00.691 [info] Process Execution: /project/workspace/other_project/.venv/bin/python /~/.vscode-server/extensions/ms-toolsai.jupyter-2024.5.0-linux-x64/pythonFiles/printJupyterDataDir.py
```

### Coding Language and Runtime Version

python v3.8

### Language Extension Version (if applicable)

Pylance v2024.6.1

### Running Jupyter locally or remotely?

Remote

**Comment by debonte** [comment]
Since Pylance owns semantic highlighting for Python, I've brought the main issue over to our repo and will resolve #5986 as a dupe.

**Comment by debonte** [comment]
Here's the link to your log file which was the only piece of info that I think was specific to the other issue:

>Here are the logs of a time when I _think_ I reproduced it.
[logs.txt](https://github.com/user-attachments/files/15789229/logs.txt)
>
>I'd be happy to collect more if you want.

**Comment by alita-moore** [comment]
I noticed that I accidentally posted this in pylance rather than in the jupyter extension repo. Should I post there as well or do you think this is a pylance issue?

**Comment by alita-moore** [comment]
I've noticed that this seems to primarily happen when the setting python.analysis.nodeExecutable is set to \usr\bin\node (or something other than empty). I started noticing this after I changed this setting due to memory overload warnings.

**Comment by alita-moore** [comment]
One work-around I have found is to disable then enable the jupyter extension without reloading vscode. In other words, disable without committing that change. I think this problem is related to this post as well: https://stackoverflow.com/questions/78643088/pylance-in-vscode-jupiter-notebooks-cannot-resolve-modules

**Comment by alita-moore** [comment]
If I change python.languageServer to none then back to pylance it also fixes the problem

**Comment by alita-moore** [comment]
force-stopping the pylance processes also causes it to get unstuck. Is there a way to restart pylance every time the interpreter changes?

**Comment by debonte** [comment]
> Is there a way to restart pylance every time the interpreter changes? 

No. It shouldn't be necessary to restart the process. Pylance will be notified of the config change.

> And or can you add a command to restart all processes?

That exists already actually -- "Python: Restart Language Server"

**Comment by debonte** [comment]
I haven't been able to repro this. Every time I think it has repro'd, I wait a little bit and it recovers. I'm curious if the same would happen for you if you waited longer. I'm not saying that that's a good experience -- but if it does recover eventually that would be good to know. It would also be interesting to see what's happening in the "Python Language Server" log (in the Output pane) when you believe that this has repro'd. Is it actively doing anything? Is it still catching up on recent interpreter changes triggered by Python Envy?

Changing the interepreter "every" time you change tabs can be expensive as it causes us to clear our type cache (we need to start from scratch on analysis), reindex your files, etc. So I'm not surprised that you see more issues in a real monorepo with more files.

Have you tried opening your repo as a multiroot workspace rather than simply opening the root folder? You'd use "Add Folder to Workspace" to add each folder that has its own venv. That's a one time thing. You'd then save the layout as a `.code-workspace` file that you can open (instead of the root folder) in the future. At that point you should disable Python Envy as Pylance wouldn't need its help to identify each file's corresponding venv. And switching between tabs in different projects wouldn't require an expensive configuration change.

Of course, that's assuming that you're not relying on Python Envy for other things.

@heejaechang might have other ideas.

**Comment by alita-moore** [comment]
I'll look into the `.code-workspace` I haven't heard of that before but am definitely open to a smoother experience! The language server output does spend some time catching up but eventually it stops outputting and it never recovers. I think it's possible that if given enough time it could recover, but I also find that unlikely because I have gone hours without it recovering. I have also noticed the behavior you mentioned, though. Especially in the sample monorepo I provided, it's possible that's not big enough to trigger the actual behavior. In that case it likely makes the most sense for me to just share logs from my project with you (not publicly).

By the way, I've noticed that when it freezes some pylance errors stop functioning correctly. Like it won't error on undefined variables until the processes are manually reset even in python files in different workspace roots and when highlighting is working for those files.

> That exists already actually -- "Python: Restart Language Server"

I don't see this command, but will try to find it as that would be helpful for me to quickly refresh / get highlighting to work.

What other information / logs can I collect to you and where I can securely share it?

**Comment by alita-moore** [comment]
I've looked into the workspaces that you mentioned. I'll keep messing around with it to try and make it work for my use-case, but I'll point out that python-envy is more intuitive and requires less setup.

**Comment by debonte** [comment]
> > That exists already actually -- "Python: Restart Language Server"
> 
> I don't see this command, but will try to find it as that would be helpful for me to quickly refresh / get highlighting to work.

That's strange. You're looking in the Command Palette? Ctrl+Shift+P?

![image](https://github.com/microsoft/pylance-release/assets/12820898/f9386653-c554-45d0-8d66-62ea72e846ab)

> I'll look into the `.code-workspace` I haven't heard of that before

Here is the docs page on that: https://code.visualstudio.com/docs/editor/multi-root-workspaces

> it likely makes the most sense for me to just share logs from my project with you (not publicly).

You can email me at `erikd at microsoft dot com`. You could send me a zip file, or a link to a download location of your choosing. Please set `"python.trace.server": "verbose"` which will cause the LSP traffic between VS Code and Pylance to be logged. I'm curious to see the last semanticTokens request and response.

> I'll point out that python-envy is more intuitive and requires less setup.

That's fair. We're aware that our monorepo support is a bit rough at the moment.

**Comment by alita-moore** [comment]
Ah, one problem I'm seeing with the workspaces solution is that you can't refactor across workspace roots. When using pylance refactors propogate

**Comment by debonte** [comment]
> Ah, one problem I'm seeing with the workspaces solution is that you can't refactor across project roots. When using python envy refactors propogate

Yeah, it would have that limitation.

So I guess that means that you have cross-root/cross-project imports? Out of curiosity, how do you currently handle those imports -- are the paths absolute or relative? Are you happy with whatever approach you're using at the moment?

@erictraut, do you have any suggestions on how to handle a monorepo where the projects each have their own venv? Do we have a good way to handle that while still allowing refactoring (ex. rename) across projects? Would execution environments help here?

**Comment by alita-moore** [comment]
I sent the logs @debonte I didn't include much of the logs for security reasons, but I captured the final parts where it eventually stopped outputting after claiming that `SemanticTokens full` for the notebooks in question. 

Yep, I have cross-root/cross-project imports using poetry development paths. This affords me a similar workflow to typescript monorepos which is very nice. Basically, it lets me check the usage of some variable / function whatever across the entire monorepo and refactor it as well as if it were a single project. Currently I setup my project in the same way as the original codesandbox that I linked, I setup each project in the same structure as a typescript monorepo (with pnpm as well for added control) and make sure that poetry saves the dependencies in the local .venv. Then when I navigate between projects python envy changes the interpreter which allows me to navigate naturally through the project.

I'm very happy with this workflow, the biggest issue being pylance being a bit delayed when switching and it using up a lot of CPU. But to me it's worth it because of the ease of refactoring and seeing where things are being used acros projects.

**Comment by alita-moore** [comment]
To be clear btw poetry dev paths treats the other projects as packages. I'm the same way that you can import a pnpm package in Typescript

**Comment by erictraut** [comment]
> do you have any suggestions on how to handle a monorepo where the projects each have their own venv

These are the options I can think of:
1. Build a single venv that is the superset of all of the venvs used across the monorepo, and use that for editing, refactoring, and type checking. This is the technique I've used previously for a monorepo. It requires that the libraries installed in the various venvs are not too divergent (e.g. conflicting versions of the same library).
2. Use workspaces. This gives you per-venv isolation and analysis, but it also means that refactoring doesn't work across workspaces.

**Comment by debonte** [comment]
> 2024-06-21 05:55:33.235 [info] [Trace - 5:55:33 AM] Received response 'textDocument/semanticTokens/full - (600)' in 2ms.
2024-06-21 05:55:33.235 [info] Result: {
    "data": []
}

Given the empty semantic tokens response, my best guess is that we're somehow no longer aware that the cells in that notebook exist. How we got into that state, I'm not sure. I'll try to repro this some more.

**Comment by alita-moore** [comment]
@erictraut that's not an ideal solution because it causes conflicts when there are some projects that require heavy dependencies or have conflicts with others. Have you found this to be an issue as well? Using python envy allows me to have project configs for each project that are separate from each other in the same way you'd have a monorepo in typescript. Have you given that a try?

**Comment by erictraut** [comment]
> Have you found this to be an issue as well?

We tried to keep versions of third-party libraries roughly in sync across the monorepo, so this wasn't an issue. In cases where the library version wasn't exactly in sync, we were typically able to use the later version and assume that the earlier version was backward compatible. In a few rare cases, we needed to create custom stubs.

> that's not an ideal solution

I don't think an ideal solution is possible in this case. You're going to need to make some compromises. If your monorepo is using different venvs, then any modules that are used in two or more venvs are potentially going to be interpreted differently because of symbols they import from the different venvs. Even if pylance were to understand different venvs without using workspaces (something that's very unlikely because it would require a substantial redesign and rewrite of pylance and pyright), it would still be dangerous to perform refactoring actions across venv boundaries. Refactoring is based on static type information, and the venv affects the static analysis. That means a refactor action that is correct for one venv may not be for another. Most of the time this probably wouldn't matter, and the refactor would be safe, but the edge cases would be ugly.

**Comment by alita-moore** [comment]
@erictraut just out of curiosity, how do you deal with submodules and dependencies that have dependency conflicts that cross major version updates?

I see, would it also require a lot of work to make switching between the venv more efficient / fast?

**Comment by erictraut** [comment]
> would it also require a lot of work to make switching between the venv more efficient / fast?

Are you finding this to be slow currently? Pyright alone (without the additional functionality in pylance) should enable very fast switching between venvs. Pylance may add overhead if it needs to reindex based on the new venv, but indexing is done in the background.

**Comment by debonte** [comment]
> Are you finding this to be slow currently?

Semantic highlighting is slow, and that's also on the background thread. But the real issue is that sometimes, after a venv change, semantic highlighting stops working entirely. I suspect that that's happening because somehow the active notebook's cells are not in the expected workspace. But I haven't been able to repro this, so I'm not positive.

When this repros in the sample repo, the user is repeatedly and rapidly switching venvs by switching tabs with the Python Envy extension installed. Apparently when this repros in a real monorepo it doesn't require so much tab switching. Maybe one is enough?

**Comment by alita-moore** [comment]
@debonte yes one is enough and I think your hypothesis makes sense. One thing I noticed is that the notebook begins to highlight if you switch to a different venv / out of that notebook. I can show you what I mean in a video if that'd help. It stops highlighting after you switch back to the notebook.

**Comment by alita-moore** [comment]
@erictraut other than the issue with it freezing it's pretty responsive. My biggest complaint is that it causes the cpu usage to spike when switching venv and sometimes if I switch quickly it takes a while to catch up. Is it possible to cache the indexing for the venv so that it requires less indexing between switches? Also, if I'm not mistaken pylance seems to index fully for each venv change even if I switch before it finishes (e.g. say I switch from venv A to venv B and then back to A before B finishes indexing, it seems that pylance will finish indexing B despite this switch), but I may be mistaken there.

**Comment by debonte** [comment]
> One thing I noticed is that the notebook begins to highlight if you switch to a different venv / out of that notebook. I can show you what I mean in a video if that'd help

Yeah, a video of that would be interesting. 

Here's an experiment that I'd be curious about: 
1. Open two notebooks in the same project (same venv).
2. Repro the issue in one of those two notebooks.
3. If you switch between those two notebook tabs now, does one of them have functional semantic highlighting while the other one does not?
4. If so, if you close the notebook that is not showing semantic highlighting (which hopefully makes the sibling notebook in the same venv the active tab, because we want to avoid switching venvs), and then reopen that notebook, does semantic highlighting work in that notebook now?

**Comment by alita-moore** [comment]
@debonte I was having trouble reproducing the issue, but I might have found something. It seems that if I import tqdm it becomes a lot easier to reproduce the issue. I have updated the linked codesandbox with tqdm to make trying it easier for you. For reference here's a video of me reproducing it: https://www.loom.com/share/7c2ad9054cf042a0990c6f20118820a1

**Comment by debonte** [comment]
> It seems that if I import tqdm it becomes a lot easier to reproduce the issue.

Good clue! I'm out of town this week, so i won't be able to look at this until next week.

**Comment by alita-moore** [comment]
I've noticed that in the pre-release version it seems that this problem is now sometimes affecting non-jupyter notebook. And or the pylance server freezes. Then if you attempt to restart it using the "restart language server" it never come back and the only way to get highlighting to work again is to reload vscode. To give you some context on how prevalent this is, I'm having to reload vscode about 20-30 times per day probably. Take it with a grain of salt that this is specific to the pre-release version, it's possible I'm mistaken.

**Comment by alita-moore** [comment]
to offer more details on the above, it seems that if I try to find the usage of a variable while switching a virtualenv the hihglighting fails / freezes in a similar way to the jupyter notebook, except that in this case 

> Restart Lang

@debonte it seems that this isn't available in jupyter notebook for some reason, i.e. in my vscode if a jupyter notebook is focused it doesn't show up, but it does if I have a python file selected.

**Comment by alita-moore** [comment]
Also this may be a separate issue, but it seems that when switching environments and trying to check for a funciton's references while indexing it sometimes kills the language server. The log outputs are as follows.
```
2024-07-03 06:10:11.188 [info] Auto-Indent enabled
2024-07-03 06:10:18.051 [info] 
<--- Last few GCs --->

[15379:0x6f696b0]  5120603 ms: Mark-Compact 7837.9 (8227.3) -> 7826.9 (8230.7) MB, 1900.86 / 0.00 ms  (average mu = 0.362, current mu = 0.459) allocation failure; scavenge might not succeed
[15379:0x6f696b0]  5123788 ms: Mark-Compact 7842.8 (8230.7) -> 7830.7 (8232.2) MB, 3136.87 / 0.00 ms  (average mu = 0.179, current mu = 0.015) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----


2024-07-03 06:10:18.074 [info]  1: 0xb80c78 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [/usr/bin/node]

2024-07-03 06:10:18.075 [info]  2: 0xeee1b0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/usr/bin/node]

2024-07-03 06:10:18.075 [info]  3: 0xeee497 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/usr/bin/node]

2024-07-03 06:10:18.076 [info]  4: 0x1100035  [/usr/bin/node]

2024-07-03 06:10:18.076 [info]  5: 0x11005c4 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/bin/node]

2024-07-03 06:10:18.077 [info]  6: 0x11174b4 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*) [/usr/bin/node]

2024-07-03 06:10:18.077 [info]  7: 0x1117ccc v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]

2024-07-03 06:10:18.078 [info]  8: 0x10edfd1 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]

2024-07-03 06:10:18.078 [info]  9: 0x10ef165 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]

2024-07-03 06:10:18.079 [info] 10: 0x10cc7b6 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/bin/node]

2024-07-03 06:10:18.079 [info] 11: 0x15285e6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
12: 0x70cfc3ed9ef6 

2024-07-03 06:11:47.548 [info] [Error - 6:11:47 AM] Stopping server timed out
```

Sorry, this might be a different issue

**Comment by debonte** [comment]
Thanks for your continued help on this. I'm now able to reproduce the issue on codesandbox and have confirmed that the problem is that we, for some reason, removed the target notebook from our internal view of the project. I'll continue investigating and let you know when I figure it out. 

Please open a separate issue for the crash.

**Comment by alita-moore** [comment]
will do, thank you!

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2024.7.103, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20247103-29-July-2024-PreRelease)

**Comment by alita-moore** [comment]
@heejaechang it seems that it did kind of fix the problem but it still happens if you switch enough and in addition it now affects standard python files as well as notebooks :(

**Comment by alita-moore** [comment]
unfortunately @heejaechang on the latest pre-release version it appears that the problem is back. I will update if the problem resolves itself.
