### ISSUE TITLE
Goto definition goes to stub files instead of actual definitions

### ISSUE THREAD

**Issue by jahan01** [microsoft/pylance-release#65]
## Expected behaviour

Goto definition goes to actual code even if types are defined in a stub file

## Actual behaviour

Goto definition goes to stub files instead of actual code

## Code Snippet / Additional information

```python
from http import HTTPStatus

print(HTTPStatus.GATEWAY_TIMEOUT)
```

Try goto definition (F12) on either `HTTPStatus` in line 1 or `GATEWAY_TIMEOUT` in line 3

**Comment by tekumara** [comment]
Duplicate https://github.com/microsoft/pyright/issues/795

**Comment by huguesv** [comment]
Goto definition on `HTTPStatus` results include both the .py and .pyi, which is currently the expected result. As discussed in the linked topic on pyright, we have no control on which of the multiple results appears first.

Goto definition on `GATEWAY_TIMEOUT` results only include the .pyi, which is a bug, it should be able to find it in sources as well but it doesn't right now.

**Comment by jahan01** [comment]
As a suggestion, if you couldn't control the order of displayed results, it would be nice to have an option turn off displaying `*.pyi` files in all the results as whole or only display results from `*.pyi` files when there are no `*.py` files.

**Comment by savannahostrowski** [comment]
@jahan01 Thanks for the suggestion. We're looking into solutions and will update here soon.

**Comment by gousaiyang** [comment]
Could we have [two separate commands like `Go To Declaration`/`Go To Definition` for C/C++ in Visual Studio](https://docs.microsoft.com/en-us/cpp/ide/navigate-code-cpp?view=vs-2019#go-to-definitiondeclaration)?

- `Go To Declaration` goes to `.h` files for C/C++, for Python we can go to the `.pyi` files
- `Go To Definition` goes to `.cpp` files for C++, for Python we can go to the `.py` files
- If one of the `.pyi` file and `.py` file is missing, the other command could still go to the existing file

**Comment by chaleaoch** [comment]
hello, is this a bug in below gif?
![websocket_firefox](https://user-images.githubusercontent.com/11831441/92248458-4e889f80-eefb-11ea-9220-4298d2774568.gif)

**Comment by jakebailey** [comment]
At the moment, that is expected behavior.

**Comment by vinicius-cleves** [comment]
I am trying to annotate tqdm. So I did the following:
1. Created a file typings/tqdm/__init__.pyi with: 
`
from typing import Any, Generic, Iterable, Iterator, TypeVar
T = TypeVar('T')
class tqdm(Generic[T]):
	def __init__(self, iterable: Iterable[T], *args: Any, **kwargs: Any): ...
	def __iter__(self) -> Iterator[T]: ...
`

2. Added `"python.analysis.stubPath": "${workspaceFolder}/typings"` to .vscode/settings.json

Now when I click on tqdm -> "Go to Definition" on another piece of code (like `from tqdm import tqdm') it jumps straight to the stub file.  Also if I try to see the references on "Go to References" the source code is not listed (it was before adding the stub file). Selecting Peek -> "Peek Definition" only display the stub file as well.

**Comment by nnemkin** [comment]
This is a major bug. Navigation into stdlib and 3rd party libraries is basically broken. `.pyi` files are an implementation detail of a typechecker, please don't put them above the real code.

**Comment by ClericPy** [comment]
Anybody thought there is an ambiguous meaning between `goto definition` and `goto stubs`? My temp solution is to remove .pyi files but is not very smart.

**Comment by ewerybody** [comment]
Well alright. Thanks @jakebailey . I was looking thoroughly but didn't use the word "stub" just `.pyi` ... 😄
So, what about WIP? How is this supposed to work in the future? Is there a plan? is there a blog post about this? anything?

For me this is simply broken atm and it was fine in the past.
There could be another shortcut like <kbd>Shift+Ctrl+Click</kbd> to Goto the stub. Actual definition should always be first!, no?

I mean I wanna be fair here: You're doing awesome work already and when doing progress things need to break here and there but I'd at least wanna know how to backup.

**Comment by ssbarnea** [comment]
That default preference for pyi drives me insane as it is killing the entire code browsing experience for any library that happens to keep type hints outside the source files. I do not want to browse the stubs when the source files exist and we clearly need and option to tell it to respect that preference.

**Comment by pszynk** [comment]
This is a sound solution, your rarely are interested in definition or type stubs at the same time.
There should be an separate option to go to either of them.

> Could we have [two separate commands like `Go To Declaration`/`Go To Definition` for C/C++ in Visual Studio](https://docs.microsoft.com/en-us/cpp/ide/navigate-code-cpp?view=vs-2019#go-to-definitiondeclaration)?
> 
> * `Go To Declaration` goes to `.h` files for C/C++, for Python we can go to the `.pyi` files
> * `Go To Definition` goes to `.cpp` files for C++, for Python we can go to the `.py` files
> * If one of the `.pyi` file and `.py` file is missing, the other command could still go to the existing file

**Comment by ssbarnea** [comment]
My C/++ years precede the existence of vscode so I do not know what is current behavior on Cmd+click as I would wish to be Go To Definition by default.

There is a slight issue with having two options because what if you do not have a definition and you only have access to the declaration? in that case I suppose it should send you to the only one available

Apparently the UI is bit confused about what is a definition and declaration as I right click on the method and choose "Go To Definition" and instead it opens the in-line preview of the declaration:

This was happened accesing "Go To Definition":
![](https://sbarnea.com/ss/Screen-Shot-2020-11-23-09-12-45.24.png)

**Comment by b99andla** [comment]
Also having trouble with this. Previously i at least got both the stub and implementation, but now I only get the stub when using F12...

**Comment by RileyMShea** [comment]
I am also experiencing this issue.  My current solution involves renaming my `/typings` folder whenver I need `goto` impl.  I've had it occasionally recognize both the pyi stub and the library .py implementation, but I have no way of consistently reproducing that behavior.  Seems a bit odd that a stub would completely obfuscate the implementation.

**Comment by aleuyX** [comment]
Started happening to me today. No workaround for this at least?

**Comment by savannahostrowski** [comment]
We are currently investigating solutions to address this.

**Comment by 93Akkord** [comment]
I believe a solution here would be the approach Pycharm takes.  Providing a clickable widget in the gutter if a corresponding .py or .pyi is available.  See screenshots below.

![image](https://user-images.githubusercontent.com/8103207/104493412-006b6300-55a3-11eb-8c95-5ff26f22c0db.png)

![image](https://user-images.githubusercontent.com/8103207/104493424-04978080-55a3-11eb-802b-7e62c85c0831.png)

**Comment by maestro4** [comment]
@savannahostrowski any new news on this?

**Comment by savannahostrowski** [comment]
We've spec'd out and planned an enhancement to go to def/go to declaration to improve this behaviour. Stay tuned!

**Comment by jakebailey** [comment]
This is not strictly related, no. We'd appreciate a new issue for that, but I would expect it to either be an issue with the source mapper, or that `os.path` contains compiled code that isn't shown.

**Comment by maestro4** [comment]
For the meantime I've downgraded pylance extension to v2020.11.1 . It now shows the documentation properly and a click will follow to the source. Unfortunately, I don't exactly know which version broke the behaviour, therefore I just tried an older version. Hope I don't have to use the older version for long, as some people are already working to resolve this issue.

**Comment by ewerybody** [comment]
> This is not strictly related, no. We'd appreciate a new issue for that, but I would expect it to either be an issue with the source mapper, or that `os.path` contains compiled code that isn't shown.

Seems there are already some related issues: #844, #170 ? Or would you rather have another one dedicated to build-in libs?

**Comment by jakebailey** [comment]
#844 is about the bundled matplotlib stubs, and #170 is a problem with Jupyter, neither are related to `isfile` missing its documentation. The builtins already have docs, but other stdlib code may not if they are compiled, but I would have expected this one to work.

**Comment by jakebailey** [comment]
The next release includes a change to go-to-definition's behavior and adds go-to-declaration. Go-to-definition prefers source files, while go-to-declaration prefers stubs.

Here's an example jumping to `Flask`:

![gotothing2](https://user-images.githubusercontent.com/5341706/107449303-2fb8b580-6af8-11eb-936f-15898ace9a59.gif)

If either of these calls would otherwise return no results (e.g. go-to-def when only a stub is available), then the old behavior is used so that you don't mysteriously jump nowhere.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.2.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202121-10-february-2021

**Comment by salvapinyol** [comment]
For me is not fixed. 

Example:

from operator import attrgetter

If I try Go to Definition or Go to Declaration for attrgetter, both goes to stub file.

**Comment by jmfederico** [comment]
Not fixed for me either.

For me it fails with the following:

```python
from django.urls import include, path
```

It correctly takes me to the source of `include`, but for `path` it takes me to stub.

**Comment by ewerybody** [comment]
Whow! I thought it was working! But obviously not always
```python
import pipes
pipes.quote()
```
Ctrl+Clicking `pipes` goes to the **stub** while `quotes` takes me to the **source**! :|

**Comment by jakebailey** [comment]
Please report these as individual bugs. We won't be reopening this issue for every case, as the primary functionality is in place.

**Comment by kissgyorgy** [comment]
This still jumps me to the stubs almost every time on v2021.2.3

**Comment by jakebailey** [comment]
Please file a new issue for those cases, but you may want to wait for the next release, which includes a good number of improvements to the way we map stubs to their source files.

**Comment by andrewmed** [comment]
> This issue has been fixed in version 2021.2.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202121-10-february-2021

This issue should not have been closed before some testing, not after getting this feedback
For me, as well, code navigation is broken with pylance. Looking for replacement...

**Comment by heejaechang** [comment]
@andrewmed if you open new issue with repro step specific to your issue, we can take a look. "go to definition" can go to stub instead of actual definition due to million different reasons. this issue is for some specific reasons which we added logic to handle. if it didn't work for you, yours is probably due to different reasons we don't know about yet. but without repro steps, we can't even take a look.

**Comment by zakigo** [comment]
this major issue exsit now . Not solved yet. so inconvenient.

pylance _v2022.1.1

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by debonte** [comment]
@zakigo, as heejaechang mentioned above, we need repro steps to understand what you are seeing. Please file a **new** issue with repro steps for what you are seeing.

**Comment by olivarius1** [comment]
I have encountered the same issue. In the past, I could at least see .pyi files and the source code. However, now, no matter which one I use between 'Go to Definition,' 'Go to Declaration,' and 'Go to Type Definition,' I can only see .pyi files (located in .vscode-server/extensions/ms-python.vscode-pylance-2023.10.20/dist/typeshed-fallback/stdlib). My Pylance version is 2023.10.20.

**Comment by debonte** [comment]
@olivarius1, please file a new issue. The issue that you are commenting on was fixed 2.5 years ago and is likely unrelated to what you are seeing.

**Comment by cangyin** [comment]
For python 3.8.10, with pylance v2023.1.10
```python
#!/usr/bin/python3

import sys

from unicodedata import category
```

`Ctrl+Click` on `unicodedata` jumps to the damp stub file, that's frustrating and drives me crazy.

**Comment by erictraut** [comment]
Where would you expect it to take you in this case? There is no `unicodedata.py` file. This module is [implemented in C](https://github.com/python/cpython/blob/main/Modules/unicodedata.c) and compiled as part of the Python interpreter. That means there is no source code on your system that can be displayed. Pylance is falling back to the type stubs in this case because they at least provide you with the interface definitions for this module.
