### ISSUE TITLE
Support for PyScript & Brython.

### ISSUE THREAD

**Issue by ItsCubeTime** [microsoft/pylance-release#6760]
### Brython & PyScript are projects that enable Python in modern browsers, the latter of which has gained a lot of attraction from the Python community recently.

They both work by enabling the use of Python directly in html files without  the need of cross compilation.

To give you a taste, here are some examples:

### Brython example:
![image](https://user-images.githubusercontent.com/20190653/177617558-be698483-ec21-401e-bb53-29f69ac3fb02.png)

*Brython is a Python interpreter written in JavaScript, with similar execution speed to that of CPython itself. It enables complete access to the "DOM", enabling it to interact with existing HTML elements as well as create new ones, it offers full access to JS declared objects (allowing you to use JS libraries and frameworks directly with Python) and supports the vast majority of the CPython STD (where only modules that simply cant run in a browser is unavailable, like the OS module which requires direct access to the computers file system or running OS dependent pre-compiled code that must run outside of the browser).*

*Brython has neglible load times thanks to extremely small package sizes as well as runtime performance comparable to that of CPython on desktop, making the technology useable for simpler websites. In addition to this it supports the full language syntax of Python itself.*

### PyScript
![image](https://user-images.githubusercontent.com/20190653/177618675-28e4b796-ca99-4aea-a964-8408196264cd.png)

*Just like Brython, PyScript is also enabled by an interpreter, which in this case runs with the help of WebAssembly, just like Brython, PyScript supports the entire language syntax of Python leveraging the more advanced features of the language.*

*Unlike Brython ,PyScript comes with a package manager for installing libraries from Pypy.org, known as "micropip", making it really convenient to use 3rd party libraries also on the client side. However PyScript also has significantly longer load times than that of Brython, making the technology more suitable for applications where longer load times are acceptable to be able to make use of potentially larger 3rd party packages on the client in a more convenient fashion.*

### Help wanted!

Both Brython and PyScript have lots of potential, (the latter of which also has a fast growing community at this time) and are in need of a stable & reliable language extension that enable code highlighting & autocompletion, especially for when writing Python code directly in the HTML files. With this feature request Im hoping to see support for **Python in .html files** (similar to that of JS in html files) **in a way thats compatable with both projects** as well as **auto completion for project specific language features & libraries** that both projects implement to allow for interoperability with common browser features (something that can probably be solved to  a large extent with the help of "fake modules" or pyi files). Due to both projects closely replicating the behaviour of the CPython interpreter I can see it being viable to use existing language servers like PyLance to take care of most of he heavy lifting by simply enabling it to read relevant sections of the html files.

They are both fantastic efforts overall.  Im here on hopes that the maintainers of this repo would find the projects interesting enough to add some form of support for them.

I can definetely see a possibility for community collaboration to make this a reality considering that both of these projects are to a large extent driven by open source contributors. I myself would gladly help contributing with CPython compatible pyi files for instance if we were to go down such a route.

#### Thanks for reading, have a nice day 💖

**Comment by rchiodo** [comment]
I believe this would need an extension to `virtualize` the contents of the html files and then send the python parts to whatever python language server is registered (which is usually Pylance).

Something akin as to what is described here:

https://code.visualstudio.com/api/language-extensions/embedded-languages#request-forwarding

I don't believe that would require any work on the Pylance/Python extensions, just another extension that did the forwarding.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2026.3.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20263100-24-August-2026-PreRelease)

**Comment by ItsCubeTime** [comment]
Could you provide some examples @heejaechang ? I can't to get the examples in the original post to work. See: https://youtu.be/2X75IVQ-ZW4 (mirror of attached video)

https://github.com/user-attachments/assets/ae4a8ca9-e73f-436e-8a29-f4d8be81c0ca

**Comment by rchiodo** [comment]
There's a new setting for it that is needed in order for it to work:


python.analysis.supportHtmlEmbeddedPython (Experimental)

Enable/disable language support (IntelliSense, diagnostics) for Python embedded in HTML files, such as PyScript <py-script>/<script type="py"> blocks.
Accepted values:
- true
- false (default)

**Comment by ItsCubeTime** [comment]
Thanks @rchiodo I do get some very basic syntax coloring now, but no hints/auto completions/go to definition/error-linting. Is all that in development still basically (and I just need to be a bit more patient ;) )? I also noticed the "Python" output channel doesnt get created until there is a `.py` file in the open folder or workspace

**Comment by rchiodo** [comment]
So it works for me, but maybe saying we support Brython isn't really accurate. 

<img width="986" height="729" alt="Image" src="https://github.com/user-attachments/assets/9603c8ac-461b-45c4-b1b7-85c7f43f30e5" />

Likely you need to have a python file open first so that the Pylance extension loads.

The problem is that the default import packages for Brython aren't known by Pylance. So like `browser` isn't a package it knows about.

I think what we've done is just treat that section of the html file like a python snippet. Full Brython support seems like it would need stubs or those packages installed in the current environment.

**Comment by rchiodo** [comment]
Reopening because 'full' Byrthon or PyScript support would require extra work around the default system packages in PyScript or Byrthon.

**Comment by ItsCubeTime** [comment]
Got it to work now! Seems a little rough around the edge seeing its crashing when doing certain things and not quite coloring everything, but it looks like a start :)
https://youtu.be/vniUADOmN9U (Im using VS codes default theme in this video, so the missing colors are not a result of a theme)

Regarding pyi files, it may be possible to write some kind of generator script using recursive use of `__dir__()`. I would gladly have a look at this, although I may first see if any of the project maintainers want a say in how this should be done. Otherwise I wouldnt mind biting the bullet and write pyi files directly off their documentation and sharing here. Perhaps best would be if we had a repository where we keep the the pyi files so people like me can request PRs (and that those then somehow gets pulled into the pylance extension during your build process)? That same repository could then also contain any potential generator script

**Comment by rchiodo** [comment]
We generally put type stubs here if the owning package doesn't want them:

https://github.com/microsoft/python-type-stubs

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2026.3.102, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20263102-4-September-2026-PreRelease)

**Comment by rchiodo** [comment]
Reopening. The Brython stubs aren't actually there AFAIK.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2026.3.103, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20263103-14-September-2026-PreRelease)

**Comment by rchiodo** [comment]
Let me caveat the 'fix' by saying we added type stubs for Brython. Errors still don't show up and is tracked by https://github.com/microsoft/pylance-release/issues/8199

**Comment by ItsCubeTime** [comment]
Oh really? Thats cool :) I had a go at writing a stubs generator in Brython itself some days ago, but I were having issues that many attributes identified as a `builtin_method` instead of the "correct" type

I will share it here in case its to any use, but I got stuck trying to figure that one out
[gen0.html](https://github.com/user-attachments/files/32203971/gen0.html)
Its based on the snippet given here: https://github.com/brython-dev/brython/issues/1938#issuecomment-1081202365

**Comment by ItsCubeTime** [comment]
@rchiodo May I ask how you added type stubs? Are they hand written or using some kind of generator - and is the source code for them available somewhere?

**Comment by rchiodo** [comment]
After you install pylance they can be found here:

C:\Users\rchiodo\.vscode-insiders\extensions\ms-python.vscode-pylance-2026.3.103\dist\bundled\html-embedded-stubs\brython\browser\__init__.pyi

We generate these during the build using a python script. Sorry the source code for the generator is not shared at the moment.
