### ISSUE TITLE
An internal error occurred while type checking file filename.py: RangeError: Maximum call stack size exceeded (Request textDocument/semanticTokens/full failed)

### ISSUE THREAD

**Issue by ehossack** [microsoft/pylance-release#701]
## Environment data

Local System: macOS 10.15.6
No remote
Pylance as part of vscode python language tools (v2020.11.371526539): 
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (3 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```
Python 3.9.0 as part of poetry (1.1.4) in a virtualenv installed via pyenv.
No adjustments to pylance.

## Expected behaviour

Can typecheck my file (unable to show it here, not open source)

## Actual behaviour

Can't typecheck file

## Logs

```
[Error - 6:04:27 PM] An internal error occurred while type checking file "/Users/ehossack/code/<project>/<path/to/folder>/<file>.py": RangeError: Maximum call stack size exceeded
    at Object.b [as lookUpClassMember] (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:454089)
    at Be (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:296050)
    at ue (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:275120)
    at /Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:297159
    at Be (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:297619)
    at pe (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:275028)
    at /Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:322073
    at /Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:451636
    at Array.forEach (<anonymous>)
    at Object.c [as mapSubtypes] (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:451513)
[Error - 6:04:27 PM] Error performing analysis: RangeError: Maximum call stack size exceeded
    at Object.b [as lookUpClassMember] (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:454089)
    at Be (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:296050)
    at ue (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:275120)
    at /Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:297159
    at Be (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:297619)
    at pe (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:275028)
    at /Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:322073
    at /Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:451636
    at Array.forEach (<anonymous>)
    at Object.c [as mapSubtypes] (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:451513)
[Error - 6:04:27 PM] Request textDocument/semanticTokens/full failed.
  Message: Request textDocument/semanticTokens/full failed unexpectedly without providing any details.
  Code: -32603 
```

See also https://github.com/microsoft/pylance-release/issues/475#issuecomment-739621071

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.12.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020121-9-december-2020

**Comment by sergei3000** [comment]
@jakebailey 
I'm still having this issue with version 2020.12.1.
In both files I'm working on now along with having the error message I'm having code coloring and code suggestions disappearing right after the part in code where I define a `pyspark`'s UDF (user defined function) using a decorator. Meaning something of this kind:
```
@F.udf(returnType=T.StringType())
def some_func(arg: int) -> str:
    if arg > 6:
        return "my_str"
```
Where `F` comes from `from pyspark.sql import functions as F`.

Here's the error message:
```
An internal error occurred while type checking file "/home/local/X5/serzakharov/projects/x5id/sz_x5_id/0025_loyalty_funnel/rfm.py": RangeError: Maximum call stack size exceeded
    at Object.isSameGenericClass (/home/local/X5/serzakharov/.vscode-server/extensions/ms-python.vscode-pylance-2020.12.1/dist/pyright-internal/src/analyzer/types.ts:567:21)
    at verifyTypeArgumentsAssignable (/home/local/X5/serzakharov/.vscode-server/extensions/ms-python.vscode-pylance-2020.12.1/dist/pyright-internal/src/analyzer/typeEvaluator.ts:15213:26)
    at canAssignClassWithTypeArgs (/home/local/X5/serzakharov/.vscode-server/extensions/ms-python.vscode-pylance-2020.12.1/dist/pyright-internal/src/analyzer/typeEvaluator.ts:15140:18)
    at canAssignClass (/home/local/X5/serzakharov/.vscode-server/extensions/ms-python.vscode-pylance-2020.12.1/dist/pyright-internal/src/analyzer/typeEvaluator.ts:14998:24)
    at canAssignType (/home/local/X5/serzakharov/.vscode-server/extensions/ms-python.vscode-pylance-2020.12.1/dist/pyright-internal/src/analyzer/typeEvaluator.ts:15961:22)
    at assignTypeToTypeVar (/home/local/X5/serzakharov/.vscode-server/extensions/ms-python.vscode-pylance-2020.12.1/dist/pyright-internal/src/analyzer/typeEvaluator.ts:15521:18)
    at canAssignType (/home/local/X5/serzakharov/.vscode-server/extensions/ms-python.vscode-pylance-2020.12.1/dist/pyright-internal/src/analyzer/typeEvaluator.ts:15634:24)
    at partiallySpecializeFunctionForBoundClassOrObject (/home/local/X5/serzakharov/.vscode-server/extensions/ms-python.vscode-pylance-2020.12.1/dist/pyright-internal/src/analyzer/typeEvaluator.ts:17268:25)
    at bindFunctionToClassOrObject (/home/local/X5/serzakharov/.vscode-server/extensions/ms-python.vscode-pylance-2020.12.1/dist/pyright-internal/src/analyzer/typeEvaluator.ts:17139:24)
    at /home/local/X5/serzakharov/.vscode-server/extensions/ms-python.vscode-pylance-2020.12.1/dist/pyright-internal/src/analyzer/typeEvaluator.ts:4176:28Pylance
```

**Comment by sergei3000** [comment]
I submitted a new issue for this - see #720
