### ISSUE TITLE
Support auto-import on snake_cased varaiables.

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pylance-release#703]
We have some flask apps that creates instances in a file and import it from other files. Please see the example:

In base.py
```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy as FlaskSQLAlchemy

app = Flask()
db = FlaskSQLALchemy(app)
```

In api.py
```python
from base import db

db.session.query(XXX)
```

Pylance's auto-import now suggests Classes, functions, UPPER_SNAKE_CASED variables, but no lower_snake_cased variables (like `db`). This would be a big problem for our code style (and this is a commonly used code style for flask users), and we'd have to manually write tons for imports by hand!

We tried to put those variables we'd like to import from other files into the `__all__` list, but Pylance seems to ignoring it.

I assume this is an as-designed behaviour because I can image others might say this is the correct behaviour, but it makes us very hard to adapt using our current code base.

So I wish Pylance can have one of these improvements:
1. Providing a config option to enable/disable auto-imports on snake_cased variable (may not include private variables starting with "_").
2. Simply respect the `__all__` variable (or some other magic variable that indicates which variable we would like to export).
3. Privide an "Manual Search&Import" command, who uses an more aggressive stratege to search possible imports accross the project (like PyCharm).

Thanks!

**Comment by giyyapan** [comment]
Recently I'm trying very hard to make all of my colleague move from PyCharm to VSCode, but the auto-import related behaviours in VSCode are pushing them back to PyCharm.

According to my own experience, PyCharm is actually not doing a very good job about auto-import, but it have a well-implemented "manual import" actions, which uses a much aggresive stratege and searches all the possible match through the whole project and you can always find what you want even these action may take longer to complete. Even it might takes 3~5s to resolve import candidates in our project, it's still much faster than manually write those imports by hand.

I think auto-import is a feature that very hard to tweak, so maybe adding an "manual import" action that use a slow but "searches everything" stratege like PyCharm is a good way to go, because it can make sure everyone get what they want to import eventually.

**Comment by judej** [comment]
@giyyapan, thanks for the report. 

Could you please try using the Insiders Build (#623) which has the indexer enabled that should solve this problem.

Please let me know if this fixes the problem

thanks

**Comment by giyyapan** [comment]
@judej, thanks for your reply.

I've tried the insiders version but snake_cased variables are still can't be auto imported.

Not sure if I did anything wrong, my Pylance version looks like this:
![image](https://user-images.githubusercontent.com/3479453/101758128-f1f8da00-3b12-11eb-9bac-3ece3c23f8c5.png)

And I also tried the `python.analysis.indexing` setting, no luck.

But the workspace symbol search is functioning though, not sure If that proves the indexer is working.
![image](https://user-images.githubusercontent.com/3479453/101758517-616ec980-3b13-11eb-858d-4c452c53ebe8.png)

**Comment by heejaechang** [comment]
@giyyapan we explicitly filtering out lower case variables from the auto-import, that is why you are not seeing it. we are doing it since it bloats the completion list too much if we include all lower variables defined blindly.

I like this idea
>>> Simply respect the __all__ variable (or some other magic variable that indicates which variable we would like to export).

but not sure whether we want to show it in auto-import or "add import (code action/light bulb)" only. 

unlike code action, auto-import can interfere with typing, so if we can, we don't want to add more entries in the completion.
