### ISSUE TITLE
`python.analysis.extraPaths` not working for directories containing symlinks

### ISSUE THREAD

**Issue by TSonono** [microsoft/pylance-release#7564]
## Environment data

-   Pylance version: 2025.8.1
-   OS and version: SLES 15-SP4 (Linux)
-   Python version: 3.10.16 (also tried with 3.12.0)

## Code Snippet

N/A

## Repro Steps

1. In a VS Code workspace's `settings.json`, file, add a directory to `python.analysis.extraPaths` that contains symlinked python files.
2. Import one of the symlinked files from within a Python file that is being edited in the VS Code workspace.

## Expected behavior

The symlinked python files should be found by Pylance and I should be able to use go-to definition on the import as well as code that uses those imports.

## Actual behavior

Pylance does not find the python files and report errors on the imports `Import "xyz" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pylance-release/blob/main/docs/diagnostics/reportMissingImports.md)`

## Logs

```
2025-09-17 16:34:32.513 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/1000/linux64/doc/html/dml-1.2-reference-manual" -> "file:///disk2/tsonono/repos/simics-base/linux64/doc/html/dml-1.2-reference-manual"
2025-09-17 16:34:32.514 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/1000/linux64/doc/html/dml-1.4-reference-manual" -> "file:///disk2/tsonono/repos/simics-base/linux64/doc/html/dml-1.4-reference-manual"
2025-09-17 16:34:33.232 [error] Stopping server timed out
2025-09-17 16:34:34.238 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/ARC-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2084"
2025-09-17 16:34:34.252 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/ARC-CPU-Restricted" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7284"
2025-09-17 16:34:34.252 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/ARM-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2077"
2025-09-17 16:34:34.253 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/ARM-Juno" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2078"
2025-09-17 16:34:34.253 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/ARM-Versatile-Express" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2103"
2025-09-17 16:34:34.253 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/ARM-devices" -> "file:///disk2/tsonono/repos/simics-base/pkgs/4055"
2025-09-17 16:34:34.253 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/ARMv8A-FVP" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2070"
2025-09-17 16:34:34.253 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Addon-Devices-Restricted" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2017"
2025-09-17 16:34:34.253 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/CADENCE-RISC-V-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2056"
2025-09-17 16:34:34.253 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/CPU-Tools" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7201"
2025-09-17 16:34:34.253 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/CPU-interfaces" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7301"
2025-09-17 16:34:34.253 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Cloud-Agent" -> "file:///disk2/tsonono/repos/simics-base/pkgs/6009"
2025-09-17 16:34:34.253 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Crypto-Engine" -> "file:///disk2/tsonono/repos/simics-base/pkgs/1030"
2025-09-17 16:34:34.253 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Crypto-Engine-Restricted" -> "file:///disk2/tsonono/repos/simics-base/pkgs/4031"
2025-09-17 16:34:34.254 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Doc-and-Packaging" -> "file:///disk2/tsonono/repos/simics-base/pkgs/6007"
2025-09-17 16:34:34.254 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Documentation-System" -> "file:///disk2/tsonono/repos/simics-base/pkgs/6008"
2025-09-17 16:34:34.254 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/External-Memory" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7202"
2025-09-17 16:34:34.254 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/GDB" -> "file:///disk2/tsonono/repos/simics-base/pkgs/1031"
2025-09-17 16:34:34.254 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/H8-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2041"
2025-09-17 16:34:34.254 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/I8051-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2085"
2025-09-17 16:34:34.254 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/I8051-CPU-Restricted" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7266"
2025-09-17 16:34:34.254 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/IA-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7294"
2025-09-17 16:34:34.254 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/IA-CPU-Experimental" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7299"
2025-09-17 16:34:34.254 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Installer-Test" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7277"
2025-09-17 16:34:34.254 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Intel-Confidential-Modeling-Library" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2015"
2025-09-17 16:34:34.254 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Intel-LIT" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7220"
2025-09-17 16:34:34.255 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Intel-SystemC" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7213"
2025-09-17 16:34:34.255 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/M68K-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2082"
2025-09-17 16:34:34.255 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/MIPS-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2097"
2025-09-17 16:34:34.255 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Model-Builder" -> "file:///disk2/tsonono/repos/simics-base/pkgs/1010"
2025-09-17 16:34:34.255 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/NIOS-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2100"
2025-09-17 16:34:34.255 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Nios-V-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2051"
2025-09-17 16:34:34.255 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/OSS-Sources" -> "file:///disk2/tsonono/repos/simics-base/pkgs/1020"
2025-09-17 16:34:34.255 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Python" -> "file:///disk2/tsonono/repos/simics-base/pkgs/1033"
2025-09-17 16:34:34.255 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/QSP-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/8112"
2025-09-17 16:34:34.255 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/QSP-CPU-SAN" -> "file:///disk2/tsonono/repos/simics-base/pkgs/3114"
2025-09-17 16:34:34.255 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/QSP-Clear-Linux" -> "file:///disk2/tsonono/repos/simics-base/pkgs/4094"
2025-09-17 16:34:34.255 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/QSP-Images" -> "file:///disk2/tsonono/repos/simics-base/pkgs/3096"
2025-09-17 16:34:34.256 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/QSP-UEFI-BIOS" -> "file:///disk2/tsonono/repos/simics-base/pkgs/4095"
2025-09-17 16:34:34.256 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/QSP-x86" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2096"
2025-09-17 16:34:34.256 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/RISC-V-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2050"
2025-09-17 16:34:34.256 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/RISC-V-Experimental-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2059"
2025-09-17 16:34:34.256 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/RISC-V-Simple" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2053"
2025-09-17 16:34:34.256 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/RISCV-HorseCreek" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2011"
2025-09-17 16:34:34.256 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Remote-Transaction-Library" -> "file:///disk2/tsonono/repos/simics-base/pkgs/3005"
2025-09-17 16:34:34.256 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/SDB" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7020"
2025-09-17 16:34:34.256 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/SHAVE-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7204"
2025-09-17 16:34:34.256 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/SIFIVE-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2052"
2025-09-17 16:34:34.256 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/SPARC-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7290"
2025-09-17 16:34:34.256 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Simics-Base" -> "file:///disk2/tsonono/repos/simics-base/pkgs/1000"
2025-09-17 16:34:34.257 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Simics-Express" -> "file:///disk2/tsonono/repos/simics-base/pkgs/1003"
2025-09-17 16:34:34.257 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Simics-Test" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7207"
2025-09-17 16:34:34.257 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Synopsys-DW" -> "file:///disk2/tsonono/repos/simics-base/pkgs/4065"
2025-09-17 16:34:34.257 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Synopsys-DW-Model-Library-binary" -> "file:///disk2/tsonono/repos/simics-base/pkgs/4066"
2025-09-17 16:34:34.257 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/SystemC-Library" -> "file:///disk2/tsonono/repos/simics-base/pkgs/1013"
2025-09-17 16:34:34.257 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/TS-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7297"
2025-09-17 16:34:34.257 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/TS-IA-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7293"
2025-09-17 16:34:34.257 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/TS-IA-CPU-External" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7295"
2025-09-17 16:34:34.257 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/TS-IA-X86S" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7280"
2025-09-17 16:34:34.257 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Test-Extra-Package-Lib-Path-1" -> "file:///disk2/tsonono/repos/simics-base/pkgs/6026"
2025-09-17 16:34:34.257 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Test-Extra-Package-Lib-Path-2" -> "file:///disk2/tsonono/repos/simics-base/pkgs/6027"
2025-09-17 16:34:34.257 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Test-Extras" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7209"
2025-09-17 16:34:34.258 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Test-Legacy-Iterator" -> "file:///disk2/tsonono/repos/simics-base/pkgs/6028"
2025-09-17 16:34:34.258 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Test-Symbol-Versioning" -> "file:///disk2/tsonono/repos/simics-base/pkgs/6029"
2025-09-17 16:34:34.258 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Training" -> "file:///disk2/tsonono/repos/simics-base/pkgs/6010"
2025-09-17 16:34:34.258 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/UEFI-FW-tracker" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7285"
2025-09-17 16:34:34.258 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Usim" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7298"
2025-09-17 16:34:34.258 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/WebUI-Server" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7272"
2025-09-17 16:34:34.258 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Websome" -> "file:///disk2/tsonono/repos/simics-base/pkgs/1002"
2025-09-17 16:34:34.258 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/X86-Performance-Models" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7210"
2025-09-17 16:34:34.258 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/X86-SAN-CPU" -> "file:///disk2/tsonono/repos/simics-base/pkgs/3112"
2025-09-17 16:34:34.258 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/Xtensa-CPU-Restricted" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7292"
2025-09-17 16:34:34.349 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/simics%28%20%29base/linux64/doc/html/dml-1.2-reference-manual" -> "file:///disk2/tsonono/repos/simics-base/linux64/doc/html/dml-1.2-reference-manual"
2025-09-17 16:34:34.349 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/simics%28%20%29base/linux64/doc/html/dml-1.4-reference-manual" -> "file:///disk2/tsonono/repos/simics-base/linux64/doc/html/dml-1.4-reference-manual"
2025-09-17 16:34:34.662 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/uCode" -> "file:///disk2/tsonono/repos/simics-base/pkgs/7298"
2025-09-17 16:34:34.665 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/x86-440BX" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2018"
2025-09-17 16:34:34.666 [warning] (20252) Skipping recursive symlink "file:///disk2/tsonono/repos/simics-base/pkgs/x86-X58-ICH10" -> "file:///disk2/tsonono/repos/simics-base/pkgs/2075"
2025-09-17 16:34:35.225 [info] (20252) Auto-excluding /disk2/tsonono/repos/simics-base/venv
2025-09-17 16:34:35.228 [info] (20252) Found 25058 source files
2025-09-17 16:34:35.228 [info] (20252) BG: Priority queue background worker(2) root directory: file:///disk2/tsonono/.vscode-server/extensions/ms-python.vscode-pylance-2025.8.1/dist
2025-09-17 16:34:35.229 [info] (20252) BG: Priority queue background worker(2) started
2025-09-17 16:34:35.229 [info] (20252) BG: Indexer background runner(3) root directory: file:///disk2/tsonono/.vscode-server/extensions/ms-python.vscode-pylance-2025.8.1/dist (index)
2025-09-17 16:34:35.229 [info] (20252) BG: Indexing(3) started
2025-09-17 16:34:35.229 [info] (20252) BG: scanned(3) 746 files over 1 exec env
2025-09-17 16:34:35.352 [info] Server process exited successfully
```

As of version 2025.8.1 of Pylance (this does not happen when downgrading to 2025.7.1), directories added with `python.analysis.extraPaths` that contain symlinked python files has seemingly stopped working. I don't see anything in the changelog indicating that this use case should not work anymore.

**Comment by rchiodo** [comment]
Thanks for the issue, but we're having trouble reproducing the issue. Can you describe how your files are symlinked? Do you have links on a per file basis or whole folders?

**Comment by rchiodo** [comment]
With per file symlinks, I can reproduce, but the same problem exists with 2025.7.1. With directory symlinks I don't see an issue.

**Comment by rchiodo** [comment]
I'm using this to test:

<img width="508" height="319" alt="Image" src="https://github.com/user-attachments/assets/b01e3cd1-bc99-4fad-86d0-be75dd82ac4c" />

Where outer_module/foo.py is a file symlink to extra_module/foo.py.

And my extraPath setting is:

```json
{
    "python.analysis.extraPaths": [
        "./extra"
    ]
}
```

That doesn't work no matter how far back I go with Pylance.

**Comment by TSonono** [comment]
@rchiodo 

<img width="2558" height="1437" alt="Image" src="https://github.com/user-attachments/assets/ec1252a0-3e6c-4d48-8a37-9c16e6b20021" />

The scenario above is observed when my settings.json looks like this:

```json
{
    "python.analysis.extraPaths": [
        "extra_modules_with_sym_links"
    ]
}
```

If I change it to

```json
{
    "python.analysis.extraPaths": [
        "extra_modules"
    ]
}
```

, everything works fine.

The symlinks was created from the working directory of the VS Code workspace with `ln -s $PWD/extra_modules/foo.py extra_modules_with_sym_links/foo.py`. `extra_modules_with_sym_links` and `extra_modules` are normal directories.

Downgrading Pylance to 2025.7.1 makes both scenarios work fine in my case, as in I don't get the `reportMissingReport` issue, and intellisense shows the the `plus()` function from the `foo.py` file.

The foo.py file:

```py
def plus(a, b):
    return a + b
```

Interestingly, in this smaller example, I don't get any warning logs version 2025.8.1 version of Pylance, but I still get the same behavior as in my initial post where things are not working. Here's the log output in the smaller example (with trace logs enabled):

[pylance.log](https://github.com/user-attachments/files/22401755/pylance.log)

**Comment by rchiodo** [comment]
I suspect this is related:
https://github.com/microsoft/pyright/issues/10906

At least it would explain the regression.

**Comment by rchiodo** [comment]
For me your example doesn't work no matter what version of Pylance I'm running. I get the same results as my other example. But I'm testing on Windows.

**Comment by rchiodo** [comment]
On WSL I can reproduce it working in 2025.7.1. Meaning we should be able to figure out how to fix it then. I guess this has never worked on Windows though.

**Comment by rchiodo** [comment]
This issue has been fixed in version 2025.8.2, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202582-18-September-2025-Release)

**Comment by TSonono** [comment]
Thanks for the fix!

**Comment by aeliasso** [comment]
I'm on the same team as @TSonono. The fixed version 2025.8.2 works well for our use-case. However, I still get the "Skipping recursive symlink" warnings for the same directories as in the initial report. These are not recursive symlinks, just one level symlinks. Is that a sign that symlink handling elsewhere in Pyright also needs to be updated?

**Comment by rchiodo** [comment]
No, I believe that logic is correct. It means the directory that is being searched has already been found elsewhere. The word "recursive" might be incorrect, but something else has already searched the pointed to directory.

The code in question is here. It happens during source enumeration:

https://github.com/microsoft/pyright/blob/1a46b0f006fc9841195f755841dba940164c7e7e/packages/pyright-internal/src/analyzer/sourceEnumerator.ts#L130

**Comment by aeliasso** [comment]
I see, then it's not a problem. Thanks for clarifying!
