### ISSUE TITLE
Pylance crashes 5 times in a row and didn't restart again

### ISSUE THREAD

**Issue by amirsoroush** [microsoft/pylance-release#7785]
## Environment data

-   Pylance version: 2025.10.4
-   OS and version: MacOS 26.1
-   Python version: 3.12.11

## Actual behavior

Pylance sometimes crashes with no reason (I realized it when the semantic color of my Python code turns white and then comes back to normal). This behavior started since a few weeks ago. This time it crashes 5 times in a row and it says:

```none
Pylance has crashed 5 times in the last 3 minutes. Pylance will not be restarted. Please check [this link](https://aka.ms/AApf7ox) for more details.
```

I should mention that there is no error in the Python code at all, and also this happens when I open slightly large files (approx 700 lines).

I will provide the logs from output panel below. (I'll include all duplicate errors)

## Logs

```
2025-12-12 23:00:03.273 [error] Unhandled Rejection in Pylance: A [Error]: request cancelled
2025-12-12 23:00:03.273 [error]     at t.throwIfCancellationRequested (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/pyright.bundle.js:1:2396887)
2025-12-12 23:00:03.273 [error]     at _0x33b4cd._throwIfOutOfDate (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:587355)
2025-12-12 23:00:03.273 [error]     at _0x33b4cd.getSourceMapper (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:574316)
2025-12-12 23:00:03.273 [error]     at new _0x4e1586 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1888279)
2025-12-12 23:00:03.273 [error]     at new _0x1a90a0 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1088942)
2025-12-12 23:00:03.273 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2391281
2025-12-12 23:00:03.273 [error]     at _0x47daa6 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1633668)
2025-12-12 23:00:03.273 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2391170
2025-12-12 23:00:03.273 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:365928
2025-12-12 23:00:03.273 [error]     at _0x33b4cd.runEditModeAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:572863)
2025-12-12 23:00:03.273 [error]     at _0xac4ccf.runEditModeAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1412151)
2025-12-12 23:00:03.274 [error]     at _0x1a7312._runCoreAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:365483)
2025-12-12 23:00:03.274 [error]     at _0x35ea16.handleHover (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2390810)
2025-12-12 23:00:03.274 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/vendor.bundle.js:2:2210000 {
2025-12-12 23:00:03.274 [error]   code: -32800,
2025-12-12 23:00:03.274 [error]   data: undefined,
2025-12-12 23:00:03.274 [error]   isTypeCacheInvalid: false
2025-12-12 23:00:03.274 [error] }
2025-12-12 23:00:03.314 [error] Server process exited with code 10.
2025-12-12 23:00:03.316 [info] Connection to server got closed. Server will restart.
2025-12-12 23:00:03.671 [info] (11166): Server root directory: file:///Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist
2025-12-12 23:00:03.672 [info] (11166): Pylance language server 2025.10.4 (pyright version 1.1.407, commit 906e40aa) starting
2025-12-12 23:00:03.674 [info] (11166): Starting service instance "backend" for workspace "/Users/soroush/github-clones/backend"
2025-12-12 23:00:03.685 [info] Client: Failed to provide MCP server definitions: Error: Unhandled method python/mcpPort
2025-12-12 23:00:03.704 [info] (11166): FG(backend): Loading pyproject.toml file at /Users/soroush/github-clones/backend/pyproject.toml
2025-12-12 23:00:03.706 [info] (11166): FG(backend): Setting pythonPath for service "backend": "/Users/soroush/github-clones/backend/.venv/bin/python3"
2025-12-12 23:00:03.706 [info] (11166): FG(backend): No include entries specified; assuming /Users/soroush/github-clones/backend
2025-12-12 23:00:03.707 [info] (11166): FG(backend): Auto-excluding **/node_modules
2025-12-12 23:00:03.707 [info] (11166): FG(backend): Auto-excluding **/__pycache__
2025-12-12 23:00:03.707 [info] (11166): FG(backend): Auto-excluding **/.*
2025-12-12 23:00:03.749 [info] (11166): FG(backend): Assuming Python version 3.12.11.final.0
2025-12-12 23:00:03.787 [info] (11166): Settings have not changed. Skipping update.
2025-12-12 23:00:04.099 [info] (11166): PQ(backend): Priority queue background worker(2) root directory: file:///Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist
2025-12-12 23:00:04.100 [info] (11166): PQ(backend): Priority queue background worker(2) started
2025-12-12 23:00:04.196 [info] (11166): IDX(backend): Indexer background runner(3) root directory: file:///Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist (index)
2025-12-12 23:00:04.196 [info] (11166): IDX(backend): Indexing(3) started
2025-12-12 23:00:04.527 [info] (11166): FG(backend): Found 511 source files
2025-12-12 23:00:04.531 [info] (11166): IDX(backend): scanned(3) 161 files over 1 exec env
2025-12-12 23:00:04.614 [info] (11166): IDX(backend): indexed(3) 161 files over 1 exec env
2025-12-12 23:00:04.630 [info] (11166): IDX(backend): Indexing finished(3).
2025-12-12 23:00:06.391 [info] (11166): Applying 0 edits to document file:///OMITTED for document transformation.
2025-12-12 23:00:07.991 [info] (11166): Applying 0 edits to document file:///OMITTED for document transformation.
2025-12-12 23:00:08.322 [info] (11166): Applying 0 edits to document file:///OMITTED for document transformation.
2025-12-12 23:00:08.700 [info] (11166): Applying 0 edits to document file:///OMITTED for document transformation.
2025-12-12 23:00:08.746 [error] Unhandled Rejection in Pylance: A [Error]: request cancelled
2025-12-12 23:00:08.747 [error]     at t.throwIfCancellationRequested (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/pyright.bundle.js:1:2396887)
2025-12-12 23:00:08.747 [error]     at _0x33b4cd._throwIfOutOfDate (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:587355)
2025-12-12 23:00:08.747 [error]     at _0x33b4cd.getSourceMapper (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:574316)
2025-12-12 23:00:08.747 [error]     at new _0x4e1586 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1888279)
2025-12-12 23:00:08.747 [error]     at new _0x1a90a0 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1088942)
2025-12-12 23:00:08.747 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2391281
2025-12-12 23:00:08.747 [error]     at _0x47daa6 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1633668)
2025-12-12 23:00:08.747 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2391170
2025-12-12 23:00:08.747 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:365928
2025-12-12 23:00:08.747 [error]     at _0x33b4cd.runEditModeAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:572863)
2025-12-12 23:00:08.747 [error]     at _0xac4ccf.runEditModeAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1412151)
2025-12-12 23:00:08.747 [error]     at _0x1a7312._runCoreAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:365483)
2025-12-12 23:00:08.747 [error]     at _0x35ea16.handleHover (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2390810)
2025-12-12 23:00:08.747 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/vendor.bundle.js:2:2210000 {
2025-12-12 23:00:08.747 [error]   code: -32800,
2025-12-12 23:00:08.747 [error]   data: undefined,
2025-12-12 23:00:08.747 [error]   isTypeCacheInvalid: false
2025-12-12 23:00:08.747 [error] }
2025-12-12 23:00:08.764 [error] Server process exited with code 10.
2025-12-12 23:00:08.765 [info] Connection to server got closed. Server will restart.
2025-12-12 23:00:09.134 [info] (11179): Server root directory: file:///Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist
2025-12-12 23:00:09.135 [info] (11179): Pylance language server 2025.10.4 (pyright version 1.1.407, commit 906e40aa) starting
2025-12-12 23:00:09.137 [info] (11179): Starting service instance "backend" for workspace "/Users/soroush/github-clones/backend"
2025-12-12 23:00:09.144 [info] Client: Failed to provide MCP server definitions: Error: Unhandled method python/mcpPort
2025-12-12 23:00:09.166 [info] (11179): FG(backend): Loading pyproject.toml file at /Users/soroush/github-clones/backend/pyproject.toml
2025-12-12 23:00:09.167 [info] (11179): FG(backend): Setting pythonPath for service "backend": "/Users/soroush/github-clones/backend/.venv/bin/python3"
2025-12-12 23:00:09.168 [info] (11179): FG(backend): No include entries specified; assuming /Users/soroush/github-clones/backend
2025-12-12 23:00:09.168 [info] (11179): FG(backend): Auto-excluding **/node_modules
2025-12-12 23:00:09.168 [info] (11179): FG(backend): Auto-excluding **/__pycache__
2025-12-12 23:00:09.168 [info] (11179): FG(backend): Auto-excluding **/.*
2025-12-12 23:00:09.187 [info] (11179): FG(backend): Assuming Python version 3.12.11.final.0
2025-12-12 23:00:09.227 [info] (11179): Settings have not changed. Skipping update.
2025-12-12 23:00:09.490 [info] (11179): Applying 0 edits to document file:///OMITTED for document transformation.
2025-12-12 23:00:10.411 [info] (11179): FG(backend): Found 511 source files
2025-12-12 23:00:10.415 [info] (11179): PQ(backend): Priority queue background worker(2) root directory: file:///Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist
2025-12-12 23:00:10.416 [info] (11179): PQ(backend): Priority queue background worker(2) started
2025-12-12 23:00:10.416 [info] (11179): IDX(backend): Indexer background runner(3) root directory: file:///Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist (index)
2025-12-12 23:00:10.416 [info] (11179): IDX(backend): Indexing(3) started
2025-12-12 23:00:10.416 [info] (11179): IDX(backend): scanned(3) 161 files over 1 exec env
2025-12-12 23:00:10.485 [info] (11179): Applying 0 edits to document file:///OMITTED for document transformation.
2025-12-12 23:00:10.548 [error] Unhandled Rejection in Pylance: A [Error]: request cancelled
2025-12-12 23:00:10.548 [error]     at t.throwIfCancellationRequested (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/pyright.bundle.js:1:2396887)
2025-12-12 23:00:10.548 [error]     at _0x33b4cd._throwIfOutOfDate (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:587355)
2025-12-12 23:00:10.548 [error]     at _0x33b4cd.getSourceMapper (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:574316)
2025-12-12 23:00:10.548 [error]     at new _0x4e1586 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1888279)
2025-12-12 23:00:10.548 [error]     at new _0x1a90a0 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1088942)
2025-12-12 23:00:10.548 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2391281
2025-12-12 23:00:10.548 [error]     at _0x47daa6 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1633668)
2025-12-12 23:00:10.548 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2391170
2025-12-12 23:00:10.548 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:365928
2025-12-12 23:00:10.548 [error]     at _0x33b4cd.runEditModeAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:572863)
2025-12-12 23:00:10.548 [error]     at _0xac4ccf.runEditModeAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1412151)
2025-12-12 23:00:10.548 [error]     at _0x1a7312._runCoreAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:365483)
2025-12-12 23:00:10.548 [error]     at _0x35ea16.handleHover (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2390810)
2025-12-12 23:00:10.548 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/vendor.bundle.js:2:2210000 {
2025-12-12 23:00:10.548 [error]   code: -32800,
2025-12-12 23:00:10.549 [error]   data: undefined,
2025-12-12 23:00:10.549 [error]   isTypeCacheInvalid: false
2025-12-12 23:00:10.549 [error] }
2025-12-12 23:00:10.569 [error] Server process exited with code 10.
2025-12-12 23:00:10.570 [info] Connection to server got closed. Server will restart.
2025-12-12 23:00:10.922 [info] (11188): Server root directory: file:///Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist
2025-12-12 23:00:10.922 [info] (11188): Pylance language server 2025.10.4 (pyright version 1.1.407, commit 906e40aa) starting
2025-12-12 23:00:10.925 [info] (11188): Starting service instance "backend" for workspace "/Users/soroush/github-clones/backend"
2025-12-12 23:00:10.933 [info] Client: Failed to provide MCP server definitions: Error: Unhandled method python/mcpPort
2025-12-12 23:00:10.953 [info] (11188): FG(backend): Loading pyproject.toml file at /Users/soroush/github-clones/backend/pyproject.toml
2025-12-12 23:00:10.954 [info] (11188): FG(backend): Setting pythonPath for service "backend": "/Users/soroush/github-clones/backend/.venv/bin/python3"
2025-12-12 23:00:10.954 [info] (11188): FG(backend): No include entries specified; assuming /Users/soroush/github-clones/backend
2025-12-12 23:00:10.955 [info] (11188): FG(backend): Auto-excluding **/node_modules
2025-12-12 23:00:10.955 [info] (11188): FG(backend): Auto-excluding **/__pycache__
2025-12-12 23:00:10.955 [info] (11188): FG(backend): Auto-excluding **/.*
2025-12-12 23:00:10.974 [info] (11188): FG(backend): Assuming Python version 3.12.11.final.0
2025-12-12 23:00:11.014 [info] (11188): Settings have not changed. Skipping update.
2025-12-12 23:00:11.373 [info] (11188): PQ(backend): Priority queue background worker(2) root directory: file:///Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist
2025-12-12 23:00:11.373 [info] (11188): PQ(backend): Priority queue background worker(2) started
2025-12-12 23:00:11.436 [info] (11188): IDX(backend): Indexer background runner(3) root directory: file:///Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist (index)
2025-12-12 23:00:11.436 [info] (11188): IDX(backend): Indexing(3) started
2025-12-12 23:00:11.785 [info] (11188): FG(backend): Found 511 source files
2025-12-12 23:00:11.790 [info] (11188): IDX(backend): scanned(3) 161 files over 1 exec env
2025-12-12 23:00:11.867 [info] (11188): IDX(backend): indexed(3) 161 files over 1 exec env
2025-12-12 23:00:11.883 [info] (11188): IDX(backend): Indexing finished(3).
2025-12-12 23:00:17.221 [info] (11188): Applying 0 edits to document file:///OMITTED for document transformation.
2025-12-12 23:00:17.285 [error] Unhandled Rejection in Pylance: A [Error]: request cancelled
2025-12-12 23:00:17.285 [error]     at t.throwIfCancellationRequested (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/pyright.bundle.js:1:2396887)
2025-12-12 23:00:17.285 [error]     at _0x33b4cd._throwIfOutOfDate (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:587355)
2025-12-12 23:00:17.285 [error]     at _0x33b4cd.getSourceMapper (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:574316)
2025-12-12 23:00:17.285 [error]     at new _0x4e1586 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1888279)
2025-12-12 23:00:17.285 [error]     at new _0x1a90a0 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1088942)
2025-12-12 23:00:17.285 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2391281
2025-12-12 23:00:17.285 [error]     at _0x47daa6 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1633668)
2025-12-12 23:00:17.285 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2391170
2025-12-12 23:00:17.285 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:365928
2025-12-12 23:00:17.285 [error]     at _0x33b4cd.runEditModeAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:572863)
2025-12-12 23:00:17.285 [error]     at _0xac4ccf.runEditModeAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1412151)
2025-12-12 23:00:17.285 [error]     at _0x1a7312._runCoreAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:365483)
2025-12-12 23:00:17.285 [error]     at _0x35ea16.handleHover (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2390810)
2025-12-12 23:00:17.285 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/vendor.bundle.js:2:2210000 {
2025-12-12 23:00:17.285 [error]   code: -32800,
2025-12-12 23:00:17.285 [error]   data: undefined,
2025-12-12 23:00:17.285 [error]   isTypeCacheInvalid: false
2025-12-12 23:00:17.285 [error] }
2025-12-12 23:00:17.301 [error] Server process exited with code 10.
2025-12-12 23:00:17.302 [info] Connection to server got closed. Server will restart.
2025-12-12 23:00:17.678 [info] (11197): Server root directory: file:///Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist
2025-12-12 23:00:17.679 [info] (11197): Pylance language server 2025.10.4 (pyright version 1.1.407, commit 906e40aa) starting
2025-12-12 23:00:17.681 [info] (11197): Starting service instance "backend" for workspace "/Users/soroush/github-clones/backend"
2025-12-12 23:00:17.688 [info] Client: Failed to provide MCP server definitions: Error: Unhandled method python/mcpPort
2025-12-12 23:00:17.710 [info] (11197): FG(backend): Loading pyproject.toml file at /Users/soroush/github-clones/backend/pyproject.toml
2025-12-12 23:00:17.711 [info] (11197): FG(backend): Setting pythonPath for service "backend": "/Users/soroush/github-clones/backend/.venv/bin/python3"
2025-12-12 23:00:17.711 [info] (11197): FG(backend): No include entries specified; assuming /Users/soroush/github-clones/backend
2025-12-12 23:00:17.712 [info] (11197): FG(backend): Auto-excluding **/node_modules
2025-12-12 23:00:17.712 [info] (11197): FG(backend): Auto-excluding **/__pycache__
2025-12-12 23:00:17.712 [info] (11197): FG(backend): Auto-excluding **/.*
2025-12-12 23:00:17.731 [info] (11197): FG(backend): Assuming Python version 3.12.11.final.0
2025-12-12 23:00:17.771 [info] (11197): Settings have not changed. Skipping update.
2025-12-12 23:00:17.939 [info] (11197): Applying 0 edits to document file:///OMITTED for document transformation.
2025-12-12 23:00:17.974 [error] Unhandled Rejection in Pylance: A [Error]: request cancelled
2025-12-12 23:00:17.974 [error]     at t.throwIfCancellationRequested (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/pyright.bundle.js:1:2396887)
2025-12-12 23:00:17.974 [error]     at _0x33b4cd._throwIfOutOfDate (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:587355)
2025-12-12 23:00:17.974 [error]     at _0x33b4cd.getSourceMapper (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:574316)
2025-12-12 23:00:17.974 [error]     at new _0x4e1586 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1888279)
2025-12-12 23:00:17.974 [error]     at new _0x1a90a0 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1088942)
2025-12-12 23:00:17.974 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2391281
2025-12-12 23:00:17.974 [error]     at _0x47daa6 (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1633668)
2025-12-12 23:00:17.974 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2391170
2025-12-12 23:00:17.974 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:365928
2025-12-12 23:00:17.974 [error]     at _0x33b4cd.runEditModeAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:572863)
2025-12-12 23:00:17.974 [error]     at _0xac4ccf.runEditModeAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:1412151)
2025-12-12 23:00:17.974 [error]     at _0x1a7312._runCoreAsync (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:365483)
2025-12-12 23:00:17.974 [error]     at _0x35ea16.handleHover (/Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/server.bundle.js:1:2390810)
2025-12-12 23:00:17.974 [error]     at /Users/soroush/.vscode/extensions/ms-python.vscode-pylance-2025.10.4/dist/vendor.bundle.js:2:2210000 {
2025-12-12 23:00:17.974 [error]   code: -32800,
2025-12-12 23:00:17.974 [error]   data: undefined,
2025-12-12 23:00:17.974 [error]   isTypeCacheInvalid: false
2025-12-12 23:00:17.974 [error] }
2025-12-12 23:00:17.998 [error] Server process exited with code 10.
2025-12-12 23:00:17.999 [error] Pylance has crashed 5 times in the last 3 minutes. Pylance will not be restarted. Please check [this link](https://aka.ms/AApf7ox) for more details.
```

**Comment by rchiodo** [comment]
Thanks for the issue. We hope to fix this in our next prerelease build.

**Comment by rchiodo** [comment]
This shouldn't have been closed yet.

**Comment by pergpau** [comment]
This bug has made Pylance basically unusable for me, hoping for a release soon 🙏

**Comment by hgbao** [comment]
If anyone is experiencing the same issue, reverting to version 2025.9.1 appears to be the only solution (for now)

**Comment by rchiodo** [comment]
It's a known issue. We hope to release a build today.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2025.12.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202512100-13-January-2026-PreRelease)

**Comment by cbritogonzalez** [comment]
Issue still present in this version of vscode:

Version: 1.109.0 (user setup)
Commit: bdd88df003631aaa0bcbe057cb0a940b80a476fa
Date: 2026-02-04T02:01:38.288Z
Electron: 39.3.0
ElectronBuildId: 13168319
Chromium: 142.0.7444.265
Node.js: 22.21.1
V8: 14.2.231.22-electron.0
OS: Windows_NT x64 10.0.26200

this version of pylance
Client: Pylance client (2025.10.4) started with python extension (2026.0.0)

**Comment by rchiodo** [comment]
@cbritogonzalez can you open a new issue? The callstack of the crash is needed for us to investigate. That should be in the "Python Language Server" output tab.
