### ISSUE TITLE
No docstrings in signature help when function is stubbed

### ISSUE THREAD

**Issue by sebastianzolg** [microsoft/pylance-release#784]
After switching over to Pylance (as suggested by the VS Code pop-up), I immediately discovered a big discrepancy between docstring support/formatting of Jedi and Pylance.
I've read several issues spread over various repos to find out the current state of docstring support. Honestly, I lost track.
Is it just me, or is this a little bit confusing? 

From reading past issues, I came up with a few questions:

**1) Why are there no additional docstrings for the most basic methods like `print()`**

![image](https://user-images.githubusercontent.com/12109119/103232709-85b40e00-493b-11eb-81b9-dd2550fcae23.png)

**2) What kind of formatting can I expect from docstrings displayed by Pylance?**
_I saw long and unreadable examples without any line break._

**3) What is the discussion of "docstring only work for 3rd party libraries and not builtins" all about?** 

**4) Why do we need _stubs_ for libraries like Pandas to show docstrings?** 
_I know that from reading other issues._

What can I expect from docstring support in the latest version?

**My Setup:**
OS: Windows 10
Python: 3.9.1
Python exts.: v2020.12.424452561
Pylance exts.: v2020.12.2

**Comment by judej** [comment]
@sebastianzolg, thanks for the questions. Responding to them:
1. The docstrings for built-ins are scraped from the built-in modules. So, what we show is what we are able to retrieve from there. 
2. We are working on formatting and they will show up as enhancements in the future. There are a couple of issues open on this for one: microsoft/pylance-release#83
3. There should be docstrings - as you have seen with `print()` 
4. We extract the docstrings from type stubs or from source. So, in the case of Pandas for example, since the modules are compiled, we look for docstrings in the stub files.

Support for docstrings will improve as we support more formats and as type stubs get more docstrings. 

Hope you are enjoying Pylance and please let me know if there are any other questions I can answer

**Comment by sebastianzolg** [comment]
Thank you very much, @judej, for your detailed answer. Very much appreciated!
It all makes sense to me, but I have one question left, and it might be the root cause of my confusion:

**Why are the Jedi results in Jupyter Lab so much better than Pylance in VSCode?**

**_Jupyter Lab (Jedi)_**
![image](https://user-images.githubusercontent.com/12109119/103282763-112ead00-49d7-11eb-81d7-d093c0aec03b.png)

**_VS Code (Pylance)_**
![image](https://user-images.githubusercontent.com/12109119/103282787-2277b980-49d7-11eb-9c14-d89a879605c0.png)

**Comment by jakebailey** [comment]
I believe that's the signature help tooltip; I think it "looks worse" because we aren't including the function docstring in that view. You'd see the same thing if you hit Ctrl+Space within the `()` of the call in a regular file.

**Comment by sebastianzolg** [comment]
Thanks for your answer, @jakebailey ! 
Are docstrings different from signature help tooltips? You see, I'm confused about what the expected behavior should be.
In simple words: Is the goal of Pylance to match Jupyter Lab and Jedi's look and feel, or are you planning to go a different direction? Of course, I'd love to see an ETA on the improvements. 

Again, thank you very much for taking the time to explain this to me.

**Comment by jakebailey** [comment]
"docstring" is just the text out of the python code triple quoted string; tooltip is the entire tooltip which can include information from the analysis as well as a docstring.

If you hover over `print`, you should see more info, but IIRC the tooltips as a whole in the new notebook system are not all there.

**Comment by konstantin-schekotihin** [comment]
> If you hover over `print`, you should see more info, but IIRC the tooltips as a whole in the new notebook system are not all there.

If I hover over `figure` in shows "Loading..." forever

![image](https://user-images.githubusercontent.com/10268680/106260799-1757b980-6221-11eb-840b-472093fd1325.png)

**Comment by jakebailey** [comment]
@konstantin-schekotihin Just to confirm, is the above while in a juypter notebook, or in a regular file?

**Comment by konstantin-schekotihin** [comment]
@jakebailey In a Jupyter notebook. The mouse is over plt.figure()

**Comment by jakebailey** [comment]
Your issue is likely microsoft/vscode-jupyter#4218, then, which will be fixed in their next release.

**Comment by jakebailey** [comment]
Retitling this to match the original report, which was not having docstrings in the signature help.

**Comment by jakebailey** [comment]
The issue here is that we haven't piped the source mapper through the signature help, which means we don't pull docstrings from real source if a stub is available. Hover and completion have done this, but signature help is missing it and is pulling info only from the immediately available AST nodes.

**Comment by inetfuture** [comment]
I'm confused too, below are what I got with JediLSP：

![Screen Shot 2021-04-13 at 5 17 32 PM](https://user-images.githubusercontent.com/1363189/114529045-6c8b5080-9bfe-11eb-9ae7-c006f6e21487.png)


![Screen Shot 2021-04-13 at 5 14 46 PM](https://user-images.githubusercontent.com/1363189/114528926-4fef1880-9bfe-11eb-96ef-c1ceefcfc209.png)




below are what I got with Pylance:

![Screen Shot 2021-04-13 at 5 09 37 PM](https://user-images.githubusercontent.com/1363189/114529094-7745e580-9bfe-11eb-8da5-44b1862f0e92.png)


![Screen Shot 2021-04-13 at 5 10 53 PM](https://user-images.githubusercontent.com/1363189/114528871-3ea60c00-9bfe-11eb-9263-988345a4eedc.png)

JediLSP is showing docstring tooltip for both `os` and `time`, Pylance only showing docstring for `os`.

These two modules are both builtin modules, why the difference? Will Pylance fix this? When?

My environment:

- macOS 11.2.3
- Python 3.9.2
- VS Code 1.55.1
- ms-python.python 2021.3.1
- ms-python.vscode-pylance 2021.4.0

**Comment by jakebailey** [comment]
That issue is unrelated. See #465 for what you're describing.

**Comment by jakebailey** [comment]
This was actually fixed in 2021.3.3, but we didn't close this issue.

![image](https://user-images.githubusercontent.com/5341706/114594218-dc6efa80-9c41-11eb-91f3-238d9346374e.png)

**Comment by Jakob-Bjorner-CapsicoHealth** [comment]
The original problem persists. There is still no docstring in the jupyter notebook for any functions, only the method header in the suggestions given from pylance.

**Comment by jakebailey** [comment]
Please file a new issue with an example and screenshot of what you're describing. I'm not sure your issue is related to this one.

**Comment by Jakob-Bjorner-CapsicoHealth** [comment]
> Please file a new issue with an example and screenshot of what you're describing. I'm not sure your issue is related to this one.

I am getting the same thing as in the first image presented. 
![image](https://user-images.githubusercontent.com/84546157/123523511-de5d2d00-d678-11eb-84f6-e9517932a151.png)
where as I would like to see the docstring inside this popup which is available in standard .py files through pylance.

**Comment by jakebailey** [comment]
That looks like the old Jupyter notebook UI, which I don't believe supports docstrings on signature help.

**Comment by Jakob-Bjorner-CapsicoHealth** [comment]
> That looks like the old Jupyter notebook UI, which I don't believe supports docstrings on signature help.

is there a way to convert to the new UI in the non-insider edition of vs code. And why would the old UI be made the default for opening ipynb files if it isn't fully up to date? This was a new install of vs code that I tried it on.

**Comment by jakebailey** [comment]
It's not the default because it's a work in progress. VS Code is still working on native notebook support; the old Jupyter UI was made from scratch.

I _think_ you can do:

```
    "jupyter.experiments.optInto": [
        "__NativeNotebookEditor__"
    ],
```

Which will force you into the newer UI.

**Comment by tdomhan** [comment]
I have the same issue. While jedi can show both the signature and the type annotation pylance just shows the latter. 

jedi:
<img width="800" alt="Screenshot 2021-11-06 at 08 03 27" src="https://user-images.githubusercontent.com/363737/140601169-30d7cb20-82ba-43bc-91d4-c46fbfc4b4f5.png">
pylance:
<img width="802" alt="Screenshot 2021-11-06 at 08 02 40" src="https://user-images.githubusercontent.com/363737/140601170-bed46d6f-2911-4576-9a33-b3a6b6075802.png">

**Comment by deem-lab** [comment]
I have the same issue nearly a year later. If I need to edit my .json settings, can you direct me to some basic instructions on how to do so?
