### ISSUE TITLE
Underlines in docstrings are wrongly prefixed by backslash in docstrings

### ISSUE THREAD

**Issue by Lancercmd** [microsoft/pylance-release#805]
## Environment data

-   Language Server version: 2020.12.2
-   OS and version: Windows 10 20H2 19042.685
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.1 poertry

## Expected behaviour

Underlines in docstrings show as underlines in normal

## Actual behaviour

Underlines in docstrings are wrongly prefixed by backslash in docstrings

## Logs

```
N/A
```

## Code Snippet / Additional information

```python
def test_a(arg):
    '''
    Function
        
        test_a

    Usage

        test_a(arg)
    '''
```

**Comment by jakebailey** [comment]
This was fixed with the big docstring refactor, but wasn't closed for some reason. See:

![image](https://user-images.githubusercontent.com/5341706/109084162-19942300-76bc-11eb-9dc6-a1b942c074c4.png)

**Comment by savchenko** [comment]
FWIW, this is still happening and has trickled down to https://github.com/DetachHead/basedpyright/issues/1688
