### ISSUE TITLE
Pylance Not Working, Jedi Active

### ISSUE THREAD

**Issue by iwoloschin** [microsoft/pylance-release#81]
## Environment data
-   Language Server version: Unknown, Won't Load
-   OS and version: macOS 10.15.5
-   Python version (& distribution if applicable, e.g. Anaconda): Homebrew Python 3.8.3

## Expected behaviour

Pylance actually loads as the language server.

## Actual behaviour

Pylance is not active, instead Jedi remains active.

## Logs

There are no Pylance logs since Pylance is not starting.

## Code Snippet / Additional information

Again, no code snippet because Pylance isn't even running. A python file is open and Jedi is launching.

**Comment by Minituff** [comment]
In my VScode settings GUI, I see that Jedi is selected under the dropdown. 
However, in my settings.json I have this configuration:
`    "python.languageServer": "Pylance", // Pylance is valid even if it throws an error`

This seems have everything working fine on my end.

**Comment by iwoloschin** [comment]
Yup, I see that too, but then I also see a line about starting Jedi in the Python Output and there is no Python Language Server output.

**Comment by jakebailey** [comment]
Could you open up the about screen in VS Code and copy its output? It should be under "Help" then "About" at the top menu.

You may also find more info in the developer tools. Logs from the Python output window would be helpful.

**Comment by iwoloschin** [comment]
VS Code Info:
```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

Here's some output when I open a silly little python project that I use to make myself street sweeping reminders:
```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'DeprecatePythonPath - experiment'
User belongs to experiment group 'RunByLine - control'
User belongs to experiment group 'CustomEditorSupport - control'
> conda --version
> conda info --json
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Python interpreter path: ~/.virtualenvs/streetsweeper/bin/python
Starting Jedi Python language engine.
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> conda --version
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/Github/street_sweeper
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/Github/street_sweeper
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/Github/street_sweeper
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/Github/street_sweeper
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/Github/street_sweeper
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/Github/street_sweeper
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/Github/street_sweeper
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/Github/street_sweeper
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/completion.py
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/completion.py
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/Github/street_sweeper/street_sweeper.py
cwd: ~/Github/street_sweeper
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/Github/street_sweeper/street_sweeper.py
cwd: ~/Github/street_sweeper
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py pydocstyle ~/Github/street_sweeper/street_sweeper.py
cwd: ~/Github/street_sweeper
> ~/.virtualenvs/streetsweeper/bin/python ~/.vscode/extensions/ms-python.python-2020.7.89046-dev/pythonFiles/pyvsc-run-isolated.py pydocstyle ~/Github/street_sweeper/street_sweeper.py
cwd: ~/Github/street_sweeper
##########Linting Output - pydocstyle##########
##########Linting Output - flake8##########
44,80,E,E501:line too long (94 > 79 characters)
89,80,E,E501:line too long (92 > 79 characters)
108,80,E,E501:line too long (96 > 79 characters)
111,80,E,E501:line too long (93 > 79 characters)
128,80,E,E501:line too long (86 > 79 characters)
```
You can probably ignore the linting output :).

**Comment by jakebailey** [comment]
Can you check all of your config files to ensure one of them isn't overriding this setting? We're currently expecting that this be set in the global user config, but you may also have something set in the workspace config or similar that's overriding it.

I'd still appreciate it if you could check the developer tools log, which you can also find in the Help menu. Some errors only show up there.

**Comment by iwoloschin** [comment]
I'm nearly certain I do not have a workspace config file for that workspace. Would another workspace's config file potentially overwrite this, even if there is only one workspace open?

I'll try to look for the developer logs later. I didn't realize that was separate from the python logs.

**Comment by jakebailey** [comment]
> Would another workspace's config file potentially overwrite this, even if there is only one workspace open?

No, it shouldn't. Places it could be configured include `.vscode/settings.json` or a `.code-workspace` file, but if you don't have either then there's more to debug. Jedi gets loaded as the backup, so something is failing to activate.

What version of the core Python extension are you using?

**Comment by iwoloschin** [comment]
I believe it's version `v2020.7.89046-dev`. I don't think I've ever enabled a dev channel, though perhaps I did? I normally just let it keep itself updated by itself.

**Comment by AndrewLester** [comment]
I believe this issue is happening with me too, so I checked the developer tools log and found this:
`Error Python Extension: 2020-07-10 02:04:04: Attempted to download with skipDownload true.` 
I did not see this message after uninstalling Pylance and reloading the window (therefore using the Microsoft Python language server).

<details>
  <summary>Full stack trace:</summary>
  console.ts:137 [Extension Host] Error Python Extension: 2020-07-10 02:18:10: Attempted to download with skipDownload true.

t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
</details>

**Comment by jakebailey** [comment]
I've been looking into this, and the `skipDownload` message is a red herring and isn't hurting anything, so the not starting must be something else.

Are you using an officially supported build of VS Code?

**Comment by kamocyc** [comment]
For me, after I removed python-related extension folders (pyright, python, pylance) from ``~/.vscode/extensions``
and reinstalled Python and Pylance exntesions, then it worked.

By the way, there were a pyright folder (which I uninstalled before) and two pylance folders for different versions. I suspect it might be related to the problem.

**Comment by iwoloschin** [comment]
I'm using the latest official build. In fact, since opening this ticket I'm now using 1.47.0 and still seeing the same issue.

```
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

I didn't see anything in the developer logs about Pylance. Is there a specific line I should look for? If not I'll try to spin up a fresh environment with only a single virtual environment to post here, otherwise it's a pretty long log.

**Comment by iwoloschin** [comment]
Manually removing the python extension from `~/.vscode/extensions` and reinstalled fixed the issue. The Python extension is now at `v2020.7.1`, I'm not sure if that has anything to do with it.

@jakebailey I'll leave this open for now, if you consider this fixed please feel free to close!

**Comment by AndrewLester** [comment]
Yes, for me it was fixed after my Pylance extension automatically updated, which leads me to believe my issue was really #86. My apologies

**Comment by jakebailey** [comment]
Yeah, when VS Code updates an extension it downloads to a new folder and just uses another one. Removing an extension doesn't actually delete it either, which saves download time.

I'm not sure why deleting them would help (other than to force updates), but thanks for letting us know.

**Comment by makeworld-the-better-one** [comment]
I'm still seeing Jedi as the language server in the GUI settings after installing Pylance 2020.07.1 (for the first time). In `settings.json` I don't even have a `python.languageServer` setting.

**Comment by jakebailey** [comment]
The former is expected (see #16), but the setting should be available as it's declared by the Python extension.
